# Generated by Django 5.0.4 on 2025-07-16 13:04

import django.db.models.deletion
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='نام')),
                ('progress', models.PositiveSmallIntegerField(default=0, verbose_name='پیشرفت')),
                ('expected', models.PositiveSmallIntegerField(default=0, help_text='هر روز آپدیت می\u200cشود', verbose_name='پیشرفت مطلوب')),
            ],
            options={
                'verbose_name': 'استان',
                'verbose_name_plural': 'استانها',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='StProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(choices=[(1404, 1404)], default=1404, verbose_name='سال برنامه\u200cای')),
                ('title', models.CharField(max_length=170, verbose_name='عنوان')),
                ('note', models.TextField(blank=True, null=True, verbose_name='شرح برنامه')),
                ('progress', models.PositiveSmallIntegerField(default=0, verbose_name='پیشرفت')),
                ('expected', models.PositiveSmallIntegerField(default=0, help_text='هر روز آپدیت می\u200cشود', verbose_name='پیشرفت مطلوب')),
                ('accepted', models.BooleanField(blank=True, null=True, verbose_name='تأیید شده')),
                ('accept_date', django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ تأیید')),
                ('accept_note', models.TextField(blank=True, null=True, verbose_name='شرح تأیید')),
                ('create_time', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='st.state', verbose_name='استان')),
            ],
            options={
                'verbose_name': 'برنامه',
                'verbose_name_plural': 'برنامه\u200cها',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='StPhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='فعالیت')),
                ('step', models.SmallIntegerField(blank=True, null=True, verbose_name='ترتیب اقدام')),
                ('importance', models.SmallIntegerField(default=1, verbose_name='اهمیت')),
                ('cost', models.BigIntegerField(default=0, help_text='میلیون تومان', verbose_name='هزینه')),
                ('start', django_jalali.db.models.jDateField(verbose_name='آغاز')),
                ('finish', django_jalali.db.models.jDateField(verbose_name='پایان')),
                ('goal', models.CharField(max_length=100, verbose_name='هدف کمی')),
                ('progress', models.PositiveSmallIntegerField(default=0, verbose_name='پیشرفت')),
                ('expected', models.PositiveSmallIntegerField(default=0, verbose_name='پیشرفت مطلوب')),
                ('create_time', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('modify_time', django_jalali.db.models.jDateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='st.stproject', verbose_name='برنامه')),
            ],
            options={
                'verbose_name': 'اقدام',
                'verbose_name_plural': 'اقدامات',
                'ordering': ['project', 'step'],
            },
        ),
        migrations.CreateModel(
            name='StReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress_claimed', models.PositiveSmallIntegerField(verbose_name='پیشرفت اعلام شده')),
                ('claim_note', models.TextField(verbose_name='شرح گزارش')),
                ('claim_date', django_jalali.db.models.jDateField(auto_now_add=True, verbose_name='تاریخ گزارش')),
                ('accepted', models.BooleanField(blank=True, null=True, verbose_name='تأیید')),
                ('progress_accepted', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='پیشرفت مورد تأیید')),
                ('accept_note', models.TextField(blank=True, null=True, verbose_name='شرح تأیید')),
                ('accept_date', django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ تأیید')),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='st.stphase', verbose_name='فاز')),
            ],
            options={
                'verbose_name': 'گزارش',
                'verbose_name_plural': 'گزارش پیشرفت',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='StReportAppendix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='report_files', verbose_name='فایل')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appendices', to='st.streport', verbose_name='گزارش')),
            ],
            options={
                'verbose_name': 'پیوست گزارش',
                'verbose_name_plural': 'پیوست گزارش',
                'ordering': ['id'],
            },
        ),
    ]
