# Generated by Django 5.0.4 on 2025-11-19 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0106_remove_user_state'),
        ('st', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stproject',
            name='state',
        ),
        migrations.RemoveField(
            model_name='stphase',
            name='project',
        ),
        migrations.RemoveField(
            model_name='streport',
            name='phase',
        ),
        migrations.RemoveField(
            model_name='streportappendix',
            name='report',
        ),
        migrations.DeleteModel(
            name='State',
        ),
        migrations.DeleteModel(
            name='StProject',
        ),
        migrations.DeleteModel(
            name='StPhase',
        ),
        migrations.DeleteModel(
            name='StReport',
        ),
        migrations.DeleteModel(
            name='StReportAppendix',
        ),
    ]
