# Generated by Django 5.0.2 on 2024-02-22 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unit',
            options={'ordering': ['id'], 'verbose_name': 'واحد', 'verbose_name_plural': 'واحدهای سازمانی'},
        ),
    ]
