# Generated by Django 5.0.2 on 2024-02-22 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_unit_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='post',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.post', verbose_name='پست'),
        ),
    ]
