# Generated by Django 5.0.2 on 2024-04-06 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_user_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='can_reserve_food',
            field=models.BooleanField(default=False, verbose_name='رزرو غذا'),
        ),
        migrations.AddField(
            model_name='post',
            name='can_reserve_guest',
            field=models.BooleanField(default=False, verbose_name='رزرو غذای میهمان'),
        ),
    ]
