# Generated by Django 5.0.2 on 2024-04-06 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_post_can_reserve_food_post_can_reserve_guest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Key',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='کلید')),
                ('value', models.CharField(max_length=20, verbose_name='مقدار')),
            ],
            options={
                'verbose_name': 'کلید',
                'verbose_name_plural': 'کلیدهای سامانه',
                'ordering': ['id'],
            },
        ),
    ]
