# Generated by Django 5.0.4 on 2024-04-08 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='can_reserve_guest',
            new_name='has_visitant',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='can_register_project',
            new_name='pm',
        ),
        migrations.RemoveField(
            model_name='post',
            name='can_reserve_food',
        ),
        migrations.RemoveField(
            model_name='post',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='post',
            name='is_supervisor',
        ),
    ]
