# Generated by Django 5.0.4 on 2024-04-09 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_can_reserve_guest_post_has_visitant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_deputy',
            field=models.BooleanField(default=False, verbose_name='عضو شورای معاونان'),
        ),
        migrations.AlterField(
            model_name='post',
            name='pm',
            field=models.BooleanField(default=False, verbose_name='مشاهده ماژول برنامه و بودجه'),
        ),
    ]
