# Generated by Django 5.0.4 on 2024-04-09 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_post_is_deputy_alter_post_pm'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='مانند مدیریتهای ذیل معاونت', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.unit', verbose_name='واحد مافوق'),
        ),
    ]
