# Generated by Django 5.0.4 on 2024-04-21 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_unit_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='position',
            field=models.CharField(choices=[('آفاق 3', 'آفاق 3'), ('آفاق 6', 'آفاق 6'), ('آفاق 12', 'آفاق 12'), ('آفاق 13', 'آفاق133'), ('آفاق 14', 'آفاق143'), ('آفاق 15', 'آفاق153'), ('آفاق 16', 'آفاق163'), ('آفاق 17', 'آفاق173'), ('آفاق 18', 'آفاق183'), ('سعادت\u200cآباد', 'سعادت\u200cآباد'), ('قم', 'قم')], default='آفاق 3', help_text='ساختمان و طبقه', max_length=20, verbose_name='موقعیت'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='is_deputy',
            field=models.BooleanField(default=False, verbose_name='مدیر واحد'),
        ),
        migrations.AlterField(
            model_name='post',
            name='is_manager',
            field=models.BooleanField(default=False, verbose_name='مدیر اداره'),
        ),
    ]
