# Generated by Django 5.0.4 on 2024-04-24 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_post_position_alter_post_is_deputy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='subsidy',
            field=models.BooleanField(default=True, verbose_name='سوبسید غذا'),
        ),
        migrations.AlterField(
            model_name='post',
            name='position',
            field=models.CharField(choices=[('آفاق 3', 'آفاق 3'), ('آفاق 6', 'آفاق 6'), ('آفاق 12', 'آفاق 12'), ('آفاق 13', 'آفاق 13'), ('آفاق 14', 'آفاق 14'), ('آفاق 15', 'آفاق 15'), ('آفاق 16', 'آفاق 16'), ('آفاق 17', 'آفاق 17'), ('آفاق 18', 'آفاق 18'), ('سعادت\u200cآباد', 'سعادت\u200cآباد'), ('قم', 'قم')], help_text='ساختمان و طبقه', max_length=20, verbose_name='موقعیت'),
        ),
    ]
