# Generated by Django 5.0.4 on 2024-04-27 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_post_subsidy_alter_post_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='personnel_code',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='کد پرسنلی'),
        ),
    ]
