# Generated by Django 5.0.4 on 2024-04-28 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_user_personnel_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='position',
            field=models.CharField(choices=[('آفاق 1', 'آفاق 1'), ('آفاق 3', 'آفاق 3'), ('آفاق 6', 'آفاق 6'), ('آفاق 12', 'آفاق 12'), ('آفاق 13', 'آفاق 13'), ('آفاق 14', 'آفاق 14'), ('آفاق 15', 'آفاق 15'), ('آفاق 16', 'آفاق 16'), ('آفاق 17', 'آفاق 17'), ('آفاق 18', 'آفاق 18'), ('سعادت\u200cآباد', 'سعادت\u200cآباد'), ('قم', 'قم')], help_text='ساختمان و طبقه', max_length=20, verbose_name='موقعیت'),
        ),
        migrations.AlterField(
            model_name='user',
            name='personnel_code',
            field=models.PositiveSmallIntegerField(default=1, unique=True, verbose_name='کد پرسنلی'),
            preserve_default=False,
        ),
    ]
