# Generated by Django 5.0.4 on 2024-04-28 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_post_position_alter_user_personnel_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='bonus_quota',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='سقف تشویقی واحد'),
        ),
        migrations.AddField(
            model_name='unit',
            name='overtime_bonus_open',
            field=models.BooleanField(default=False, verbose_name='قفل ویرایش اضافه کار و تشویقی'),
        ),
        migrations.AddField(
            model_name='unit',
            name='overtime_quota',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='سقف اضافه کار واحد'),
        ),
    ]
