# Generated by Django 5.0.4 on 2024-04-29 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_unit_bonus_quota_unit_overtime_bonus_open_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='bonus_quota',
            field=models.PositiveIntegerField(default=0, verbose_name='سقف تشویقی واحد'),
        ),
    ]
