# Generated by Django 5.0.4 on 2024-04-29 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_unit_bonus_quota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='bonus_quota',
            field=models.PositiveBigIntegerField(default=0, verbose_name='سقف تشویقی واحد'),
        ),
    ]
