# Generated by Django 5.0.4 on 2024-04-30 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_user_personnel_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='personnel_code',
            field=models.PositiveSmallIntegerField(blank=True, null=True, unique=True, verbose_name='کد پرسنلی'),
        ),
    ]
