# Generated by Django 5.0.4 on 2024-05-01 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_user_personnel_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='timesheet_less',
            field=models.BooleanField(default=False, verbose_name='نیاز به گزارش تایم\u200cشیت ندارد'),
        ),
    ]
