# Generated by Django 5.0.4 on 2024-05-13 07:41

import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_post_timesheet_less'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proclamation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان')),
                ('body', models.TextField(verbose_name='متن')),
                ('create_date', django_jalali.db.models.jDateField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('publish_date', django_jalali.db.models.jDateField(verbose_name='تاریخ انتشار')),
                ('expire_date', django_jalali.db.models.jDateField(verbose_name='تاریخ انقضا')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.unit', verbose_name='واحد')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'اطلاعیه',
                'verbose_name_plural': 'اطلاعیه',
                'ordering': ['-id'],
            },
        ),
    ]
