# Generated by Django 5.0.4 on 2024-05-13 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_proclamation'),
    ]

    operations = [
        migrations.AddField(
            model_name='proclamation',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='پیوست'),
        ),
    ]
