# Generated by Django 5.0.4 on 2024-05-13 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_proclamation_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tell',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='خط مستقیم'),
        ),
        migrations.AddField(
            model_name='post',
            name='tell_local',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='تلفن داخلی'),
        ),
    ]
