# Generated by Django 5.0.4 on 2024-05-25 04:40

import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_post_tell_post_tell_local'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proclamation',
            name='file',
        ),
        migrations.CreateModel(
            name='ProclamationAppendix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان')),
                ('file', models.FileField(blank=True, null=True, upload_to='', verbose_name='پیوست')),
                ('proclamation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.proclamation', verbose_name='اطلاعیه')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ProclamationSeen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', django_jalali.db.models.jDateField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('proclamation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.proclamation', verbose_name='اطلاعیه')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'اطلاعیه - مشاهده',
                'verbose_name_plural': 'اطلاعیه - مشاهده',
                'ordering': ['-id'],
            },
        ),
    ]
