# Generated by Django 5.0.4 on 2024-05-26 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_remove_proclamation_file_proclamationappendix_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proclamationappendix',
            options={'ordering': ['id'], 'verbose_name': 'پیوست\u200cهای اطلاعیه', 'verbose_name_plural': 'پیوست\u200cهای اطلاعیه'},
        ),
        migrations.AlterField(
            model_name='proclamationappendix',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='فایل'),
        ),
        migrations.AlterField(
            model_name='proclamationappendix',
            name='proclamation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appendices', to='core.proclamation', verbose_name='اطلاعیه'),
        ),
    ]
