# Generated by Django 5.0.4 on 2024-06-09 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_proclamationappendix_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='is_deputy',
            field=models.BooleanField(default=False, verbose_name='عضو شورای معاونان'),
        ),
        migrations.AlterField(
            model_name='post',
            name='is_manager',
            field=models.BooleanField(default=False, verbose_name='مدیر'),
        ),
        migrations.AlterField(
            model_name='post',
            name='position',
            field=models.CharField(choices=[('آفاق 1', 'آفاق 1'), ('آفاق 3', 'آفاق 3'), ('آفاق 4', 'آفاق 4'), ('آفاق 6', 'آفاق 6'), ('آفاق 12', 'آفاق 12'), ('آفاق 13', 'آفاق 13'), ('آفاق 14', 'آفاق 14'), ('آفاق 15', 'آفاق 15'), ('آفاق 16', 'آفاق 16'), ('آفاق 17', 'آفاق 17'), ('آفاق 18', 'آفاق 18'), ('سعادت\u200cآباد', 'سعادت\u200cآباد'), ('قم', 'قم')], help_text='ساختمان و طبقه', max_length=20, verbose_name='موقعیت'),
        ),
    ]
