# Generated by Django 5.0.4 on 2024-06-11 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_post_is_deputy_alter_post_is_manager_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='has_lunch',
            field=models.BooleanField(default=True, verbose_name='دسترسی رزرو غذا'),
        ),
    ]
