# Generated by Django 5.0.4 on 2024-06-26 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_post_has_lunch'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='can_see_invoice',
            field=models.BooleanField(default=False, verbose_name='مشاهده برگه تنخواه'),
        ),
    ]
