# Generated by Django 5.0.4 on 2024-08-06 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_post_can_see_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='proclamation',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='پوستر'),
        ),
        migrations.AlterField(
            model_name='proclamation',
            name='body',
            field=models.TextField(blank=True, null=True, verbose_name='متن'),
        ),
    ]
