# Generated by Django 5.0.4 on 2024-08-13 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_proclamation_poster_alter_proclamation_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proclamation',
            name='title',
            field=models.CharField(max_length=100, verbose_name='عنوان'),
        ),
    ]
