# Generated by Django 5.0.4 on 2024-08-26 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_proclamation_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='level',
            field=models.CharField(choices=[('رئیس', 'رئیس'), ('معاون', 'معاون'), ('مدیرکل', 'مدیرکل'), ('مدیر', 'مدیر'), ('مشاور', 'مشاور'), ('کارشناس', 'کارشناس'), ('متصدی', 'متصدی')], default='کارشناس', max_length=10, verbose_name='رده شغلی'),
            preserve_default=False,
        ),
    ]
