# Generated by Django 5.0.4 on 2024-09-01 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_post_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='level',
            field=models.CharField(choices=[('رئیس', 'رئیس'), ('معاون', 'معاون'), ('مدیرکل', 'مدیرکل'), ('مدیر', 'مدیر'), ('مشاور', 'مشاور'), ('کارشناس', 'کارشناس'), ('مسئول دفتر', 'مسئول دفتر'), ('کاردان', 'کاردان'), ('تأسیسات', 'تأسیسات'), ('خدمات', 'خدمات'), ('راننده', 'راننده'), ('حفاظت فیزیکی', 'حفاظت فیزیکی')], max_length=15, verbose_name='رده شغلی'),
        ),
    ]
