# Generated by Django 5.0.4 on 2024-09-01 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_alter_post_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='color',
            field=models.CharField(choices=[('teal-lighten-4', 'سبزآبی'), ('blue-lighten-4', 'آبی'), ('cyan-lighten-4', 'فیروزه\u200cای'), ('green-lighten-4', 'سبز'), ('amber-lighten-4', 'نارنجی'), ('pink-lighten-5', 'صورتی'), ('purple-lighten-5', 'بنفش'), ('blue-grey-lighten-4', 'خاکستری')], default='cyan-lighten-4', max_length=20, verbose_name='رنگ'),
        ),
    ]
