# Generated by Django 5.0.4 on 2024-09-01 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_unit_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='interim',
            field=models.BooleanField(default=False, verbose_name='کاربر موقت'),
        ),
    ]
