# Generated by Django 5.0.4 on 2024-09-15 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_user_interim'),
        ('prj', '0016_remove_mission_body_remove_mission_units'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='color',
        ),
        migrations.AddField(
            model_name='unit',
            name='missions',
            field=models.ManyToManyField(blank=True, related_name='units', to='prj.mission', verbose_name='واحدهای متولی'),
        ),
        migrations.AlterField(
            model_name='post',
            name='level',
            field=models.CharField(choices=[('رئیس', 'رئیس'), ('معاون', 'معاون'), ('مدیرکل', 'مدیرکل'), ('معاون مدیرکل', 'معاون مدیرکل'), ('مدیر', 'مدیر'), ('مشاور', 'مشاور'), ('کارشناس', 'کارشناس'), ('مسئول دفتر', 'مسئول دفتر'), ('کاردان', 'کاردان'), ('تأسیسات', 'تأسیسات'), ('خدمات', 'خدمات'), ('راننده', 'راننده'), ('حفاظت فیزیکی', 'حفاظت فیزیکی')], max_length=15, verbose_name='رده شغلی'),
        ),
    ]
