# Generated by Django 5.0.4 on 2024-09-15 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_remove_unit_color_unit_missions_alter_post_level'),
        ('prj', '0016_remove_mission_body_remove_mission_units'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='missions',
            field=models.ManyToManyField(blank=True, related_name='units', to='prj.mission', verbose_name='مأموریت\u200cها'),
        ),
    ]
