# Generated by Django 5.0.4 on 2024-10-02 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_alter_unit_missions'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_permanent',
            field=models.BooleanField(default=False, verbose_name='کارمند رسمی'),
        ),
    ]
