# Generated by Django 5.0.4 on 2024-10-16 03:58

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_user_is_permanent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='interim',
            new_name='is_interim',
        ),
        migrations.AddField(
            model_name='user',
            name='is_soldier',
            field=models.BooleanField(default=False, verbose_name='سرباز امریه'),
        ),
        migrations.AlterField(
            model_name='proclamation',
            name='body',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='متن'),
        ),
    ]
