# Generated by Django 5.0.4 on 2024-10-20 10:26

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_rename_interim_user_is_interim_user_is_soldier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proclamation',
            name='publish_date',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ انتشار'),
        ),
    ]
