# Generated by Django 5.0.4 on 2024-10-20 10:27

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_alter_proclamation_publish_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proclamation',
            name='expire_date',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ انقضا'),
        ),
        migrations.AlterField(
            model_name='proclamation',
            name='publish_date',
            field=django_jalali.db.models.jDateField(default='1403-1-1', verbose_name='تاریخ انتشار'),
            preserve_default=False,
        ),
    ]
