# Generated by Django 5.0.4 on 2024-10-26 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_alter_proclamation_expire_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='کلید'),
        ),
        migrations.AlterField(
            model_name='key',
            name='value',
            field=models.CharField(max_length=50, verbose_name='مقدار'),
        ),
    ]
