# Generated by Django 5.0.4 on 2024-10-26 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_alter_key_id_alter_key_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='attendance',
            field=models.PositiveSmallIntegerField(default=0, help_text='ویژه مشاوران', verbose_name='جمع ساعات حضور'),
        ),
        migrations.AddField(
            model_name='user',
            name='contract_type',
            field=models.CharField(choices=[('پروژه', 'پروژه'), ('مشاوره', 'مشاوره'), ('همکاری', 'همکاری')], default='پروژه', max_length=10, verbose_name='نوع قرارداد'),
            preserve_default=False,
        ),
    ]
