# Generated by Django 5.0.4 on 2024-10-26 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_user_attendance_user_contract_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='attendance',
            new_name='attendance_min',
        ),
    ]
