# Generated by Django 5.0.4 on 2024-10-27 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_rename_attendance_user_attendance_min'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='attendance_min',
        ),
        migrations.RemoveField(
            model_name='user',
            name='contract_type',
        ),
    ]
