# Generated by Django 5.0.4 on 2024-10-28 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_remove_user_attendance_min_remove_user_contract_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='key',
            name='key',
            field=models.CharField(default='a', max_length=50, unique=True, verbose_name='کلید'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='key',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
