# Generated by Django 5.0.4 on 2024-10-28 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_key_key_alter_key_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='key',
            name='description',
            field=models.CharField(default='a', max_length=200, verbose_name='شرح'),
            preserve_default=False,
        ),
    ]
