# Generated by Django 5.0.4 on 2024-10-28 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_key_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_permanent',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_soldier',
        ),
    ]
