# Generated by Django 5.0.4 on 2024-10-28 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_remove_user_is_permanent_remove_user_is_soldier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='subsidy',
        ),
    ]
