# Generated by Django 5.0.4 on 2024-11-17 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_remove_post_subsidy'),
    ]

    operations = [
        migrations.AddField(
            model_name='proclamation',
            name='type',
            field=models.CharField(choices=[('اطلاعیه', 'اطلاعیه'), ('آیین\u200cنامه', 'آیین\u200cنامه'), ('آموزش', 'آموزش')], default='اطلاعیه', max_length=10, verbose_name='نوع'),
        ),
    ]
