# Generated by Django 5.0.4 on 2024-11-17 03:52

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_proclamation_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proclamation',
            name='publish_date',
        ),
        migrations.AlterField(
            model_name='proclamation',
            name='create_date',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
    ]
