# Generated by Django 5.0.4 on 2024-11-17 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_remove_proclamation_publish_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proclamation',
            old_name='create_date',
            new_name='create_time',
        ),
    ]
