# Generated by Django 5.0.4 on 2024-11-24 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_rename_create_date_proclamation_create_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proclamation',
            name='type',
            field=models.CharField(choices=[('اطلاعیه', 'اطلاعیه'), ('آیین\u200cنامه', 'آیین\u200cنامه'), ('آموزش فاوا', 'آموزش فاوا'), ('آموزش حراست', 'آموزش حراست'), ('اخبار فضای مجازی', 'اخبار فضای مجازی')], default='اطلاعیه', max_length=20, verbose_name='نوع'),
        ),
    ]
