# Generated by Django 5.0.4 on 2024-11-25 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_alter_proclamation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='proclamation',
            name='display_duration',
            field=models.PositiveBigIntegerField(blank=True, choices=[(7, 'یک هفته'), (15, 'دو هفته'), (30, 'یک ماه')], null=True, verbose_name='مدت نمایش'),
        ),
        migrations.AlterField(
            model_name='proclamation',
            name='type',
            field=models.CharField(choices=[('اطلاعیه', 'اطلاعیه'), ('آیین\u200cنامه', 'آیین\u200cنامه'), ('آموزش', 'آموزش'), ('اخبار فضای مجازی', 'اخبار فضای مجازی')], default='اطلاعیه', max_length=20, verbose_name='نوع'),
        ),
    ]
