# Generated by Django 5.0.4 on 2024-12-07 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_proclamation_display_duration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProclamationGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='', verbose_name='فایل')),
                ('proclamation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.proclamation', verbose_name='اطلاعیه')),
            ],
            options={
                'verbose_name': 'تصاویر اطلاعیه',
                'verbose_name_plural': 'تصاویر اطلاعیه',
                'ordering': ['id'],
            },
        ),
    ]
