# Generated by Django 5.0.4 on 2024-12-07 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_proclamationgallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proclamationgallery',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='فایل'),
        ),
        migrations.AlterField(
            model_name='proclamationgallery',
            name='proclamation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='core.proclamation', verbose_name='اطلاعیه'),
        ),
    ]
