# Generated by Django 5.0.4 on 2024-12-10 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_alter_proclamationgallery_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proclamation',
            name='type',
            field=models.CharField(choices=[('اطلاعیه', 'اطلاعیه'), ('آیین\u200cنامه', 'آیین\u200cنامه'), ('آموزش', 'آموزش'), ('اخبار فضای مجازی', 'اخبار فضای مجازی'), ('محفل تخصصی', 'محفل تخصصی')], default='اطلاعیه', max_length=20, verbose_name='نوع'),
        ),
        migrations.AlterField(
            model_name='proclamationgallery',
            name='file',
            field=models.ImageField(default='a', upload_to='', verbose_name='فایل'),
            preserve_default=False,
        ),
    ]
