# Generated by Django 5.0.4 on 2024-12-10 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_alter_proclamation_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='level',
            field=models.CharField(choices=[('رئیس', 'رئیس'), ('معاون و مدیرکل مستقل', 'معاون و مدیرکل مستقل'), ('مدیرکل تابعه', 'مدیرکل تابعه'), ('معاون مدیرکل', 'معاون مدیرکل'), ('مدیر', 'مدیر'), ('مشاور', 'مشاور'), ('کارشناس', 'کارشناس'), ('مسئول دفتر', 'مسئول دفتر'), ('کاردان', 'کاردان'), ('تأسیسات', 'تأسیسات'), ('خدمات', 'خدمات'), ('راننده', 'راننده'), ('حفاظت فیزیکی', 'حفاظت فیزیکی')], max_length=20, verbose_name='رده شغلی'),
        ),
    ]
