# Generated by Django 5.0.4 on 2024-12-18 07:44

import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_alter_post_level'),
        ('pm', '0052_alter_flow_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان')),
                ('body', models.CharField(max_length=200, verbose_name='متن')),
                ('url', models.CharField(max_length=200, verbose_name='لینک مربوطه')),
                ('created_time', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='زمان ثبت')),
                ('seen_time', django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='زمان دیده شدن')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pm.task', verbose_name='کار مربوطه')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'یادآور',
                'verbose_name_plural': 'یادآور',
                'ordering': ('-id',),
            },
        ),
    ]
