# Generated by Django 5.0.4 on 2024-12-24 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_notification_job_chat_alter_notification_task_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nc',
            field=models.CharField(blank=True, null=True, verbose_name='کد ملی'),
        ),
    ]
