# Generated by Django 5.0.4 on 2024-12-30 06:10

import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_user_nc'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='تاریخ تولد'),
        ),
        migrations.AlterField(
            model_name='proclamation',
            name='type',
            field=models.CharField(choices=[('اطلاعیه', 'اطلاعیه'), ('آیین\u200cنامه', 'آیین\u200cنامه'), ('آموزش', 'آموزش'), ('اخبار فضای مجازی', 'اخبار فضای مجازی'), ('محفل تخصصی', 'محفل تخصصی'), ('پینگ', 'پینگ')], default='اطلاعیه', max_length=20, verbose_name='نوع'),
        ),
    ]
