# Generated by Django 5.0.4 on 2024-12-30 06:11

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_user_birth_date_alter_proclamation_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ تولد'),
        ),
    ]
