# Generated by Django 5.0.4 on 2025-01-27 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_alter_user_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proclamation',
            name='type',
            field=models.CharField(choices=[('اطلاعیه', 'اطلاعیه'), ('آیین\u200cنامه', 'آیین\u200cنامه'), ('نکات حفاظتی', 'نکات حفاظتی'), ('اخبار فضای مجازی', 'اخبار فضای مجازی'), ('محفل تخصصی', 'محفل تخصصی'), ('پینگ', 'پینگ')], default='اطلاعیه', max_length=20, verbose_name='نوع'),
        ),
    ]
