# Generated by Django 5.0.4 on 2025-02-05 06:05

import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_alter_proclamation_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=13, verbose_name='شماره موبایل')),
                ('text', models.TextField(blank=True, null=True, verbose_name='متن پیامک')),
                ('create_time', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='زمان ارسال')),
                ('sent', models.BooleanField(verbose_name='نتیجه ارسال')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پیامک',
                'verbose_name_plural': 'پیامک',
                'ordering': ['-id'],
            },
        ),
    ]
