# Generated by Django 5.0.4 on 2025-02-11 04:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_sms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sms',
            name='mobile',
            field=models.CharField(editable=False, max_length=13, verbose_name='شماره موبایل'),
        ),
        migrations.AlterField(
            model_name='sms',
            name='sent',
            field=models.BooleanField(editable=False, verbose_name='نتیجه ارسال'),
        ),
        migrations.AlterField(
            model_name='sms',
            name='text',
            field=models.TextField(blank=True, editable=False, null=True, verbose_name='متن پیامک'),
        ),
        migrations.AlterField(
            model_name='sms',
            name='user',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
    ]
