# Generated by Django 5.0.4 on 2025-02-18 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_alter_sms_mobile_alter_sms_sent_alter_sms_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='note1404',
            field=models.TextField(blank=True, null=True, verbose_name='نکات اصلاحی'),
        ),
    ]
