# Generated by Django 5.0.4 on 2025-04-07 05:59

import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_unit_note1404'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['is_superuser', 'id'], 'verbose_name': 'کاربر', 'verbose_name_plural': 'کاربر'},
        ),
        migrations.AddField(
            model_name='post',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='staffs', to='core.unit', verbose_name='محل خدمت'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='has_lunch',
            field=models.BooleanField(default=False, verbose_name='دسترسی رزرو غذا'),
        ),
        migrations.AlterField(
            model_name='proclamation',
            name='type',
            field=models.CharField(choices=[('اطلاعیه', 'اطلاعیه'), ('آیین\u200cنامه', 'آیین\u200cنامه'), ('نکات حفاظتی', 'نکات حفاظتی'), ('اخبار فضای مجازی', 'اخبار فضای مجازی'), ('محفل تخصصی', 'محفل تخصصی'), ('پینگ', 'پینگ'), ('درنگی نورانی', 'درنگی نورانی')], default='اطلاعیه', max_length=20, verbose_name='نوع'),
        ),
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_directory_account', models.CharField(max_length=20)),
                ('pc_name', models.CharField(max_length=20)),
                ('cpu', models.CharField(max_length=20)),
                ('motherboard', models.CharField(max_length=30)),
                ('ram', models.PositiveSmallIntegerField(choices=[(4, 4), (8, 8), (16, 16)])),
                ('vga', models.CharField(max_length=20)),
                ('hdd', models.CharField(blank=True, max_length=5, null=True)),
                ('ssd', models.CharField(blank=True, max_length=5, null=True)),
                ('os', models.CharField(choices=[('Windows 7', 'Windows 7'), ('Windows 10', 'Windows 10'), ('Windows 11', 'Windows 11'), ('Linux', 'Linux')], max_length=20)),
                ('notes', models.CharField(blank=True, max_length=200, null=True)),
                ('create_date', django_jalali.db.models.jDateField(auto_now_add=True)),
                ('update_date', django_jalali.db.models.jDateField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
