# Generated by Django 5.0.4 on 2025-04-08 03:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cn', '0041_alter_pay_options'),
        ('core', '0066_alter_computer_user'),
        ('pm', '0061_alter_field_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cn.contract', verbose_name='قرارداد'),
        ),
        migrations.AddField(
            model_name='notification',
            name='flow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pm.flow', verbose_name='فرآیند'),
        ),
    ]
