# Generated by Django 5.0.4 on 2025-04-08 03:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_notification_contract_notification_flow'),
        ('pm', '0061_alter_field_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='flow',
        ),
        migrations.AddField(
            model_name='notification',
            name='node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pm.node', verbose_name='گره فرآیند'),
        ),
    ]
