# Generated by Django 5.0.4 on 2025-04-12 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0068_remove_notification_flow_notification_node'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='ip',
            field=models.CharField(default='0.0.0.0', max_length=15),
            preserve_default=False,
        ),
    ]
