# Generated by Django 5.0.4 on 2025-04-23 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0069_computer_ip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='location',
        ),
        migrations.AddField(
            model_name='post',
            name='locations',
            field=models.ManyToManyField(blank=True, related_name='staffs', to='core.unit', verbose_name='محل خدمت'),
        ),
        migrations.AlterField(
            model_name='proclamation',
            name='type',
            field=models.CharField(choices=[('اطلاعیه', 'اطلاعیه'), ('آیین\u200cنامه', 'آیین\u200cنامه'), ('نکات حفاظتی', 'نکات حفاظتی'), ('اخبار فضای مجازی', 'اخبار فضای مجازی'), ('محفل تخصصی', 'محفل تخصصی'), ('پینگ', 'پینگ'), ('درنگی نورانی', 'درنگی نورانی'), ('سرمایه انسانی', 'سرمایه انسانی')], default='اطلاعیه', max_length=20, verbose_name='نوع'),
        ),
    ]
