# Generated by Django 5.0.4 on 2025-04-26 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_remove_post_location_post_locations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='joined',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='proclamation',
            name='type',
            field=models.CharField(choices=[('اطلاعیه', 'اطلاعیه'), ('آیین\u200cنامه', 'آیین\u200cنامه'), ('ضوابط حراست', 'ضوابط حراست'), ('اخبار فضای مجازی', 'اخبار فضای مجازی'), ('محفل تخصصی', 'محفل تخصصی'), ('پینگ', 'پینگ'), ('درنگی نورانی', 'درنگی نورانی'), ('سرمایه انسانی', 'سرمایه انسانی')], default='اطلاعیه', max_length=20, verbose_name='نوع'),
        ),
    ]
