# Generated by Django 5.0.4 on 2025-05-25 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0071_computer_joined_alter_proclamation_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proclamation',
            name='type',
            field=models.CharField(choices=[('اطلاعیه', 'اطلاعیه'), ('آیین\u200cنامه', 'آیین\u200cنامه'), ('ضوابط حراست', 'ضوابط حراست'), ('اخبار فضای مجازی', 'اخبار فضای مجازی'), ('محفل تخصصی', 'محفل تخصصی'), ('پینگ', 'پینگ'), ('درنگی نورانی', 'درنگی نورانی'), ('سرمایه انسانی', 'سرمایه انسانی'), ('سرخط', 'سرخط'), ('فناوری اطلاعات', 'فناوری اطلاعات')], default='اطلاعیه', max_length=20, verbose_name='نوع'),
        ),
    ]
