# Generated by Django 5.0.4 on 2025-05-27 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0072_alter_proclamation_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='ram',
            field=models.PositiveSmallIntegerField(choices=[(2, 2), (4, 4), (8, 8), (16, 16), (32, 32), (64, 64)]),
        ),
    ]
