# Generated by Django 5.0.4 on 2025-06-02 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0073_alter_computer_ram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='has_visitant',
            field=models.BooleanField(default=False, verbose_name='ثبت جلسه در تقویم'),
        ),
    ]
