# Generated by Django 5.0.4 on 2025-06-09 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0074_alter_post_has_visitant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='can_see_invoice',
        ),
        migrations.RemoveField(
            model_name='post',
            name='has_lunch',
        ),
        migrations.RemoveField(
            model_name='post',
            name='has_visitant',
        ),
        migrations.RemoveField(
            model_name='post',
            name='pm',
        ),
        migrations.RemoveField(
            model_name='post',
            name='timesheet_less',
        ),
    ]
