# Generated by Django 5.0.4 on 2025-07-16 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0075_remove_post_can_see_invoice_remove_post_has_lunch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bg',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='عکس زمینه'),
        ),
        migrations.AddField(
            model_name='user',
            name='color',
            field=models.CharField(default='#93c0d7', max_length=7, verbose_name='رنگ تم'),
        ),
        migrations.AddField(
            model_name='user',
            name='them',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='تم'),
        ),
    ]
