# Generated by Django 5.0.4 on 2025-08-05 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0076_user_bg_user_color_user_them'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='نام')),
                ('bg', models.ImageField(upload_to='', verbose_name='عکس زمینه')),
                ('main', models.CharField(default='#93c0d7', max_length=7, verbose_name='رنگ اصلی')),
                ('tint1', models.CharField(default='#93c0d7', max_length=7, verbose_name='رنگ 1')),
                ('tint2', models.CharField(default='#93c0d7', max_length=7, verbose_name='رنگ 2')),
                ('tint3', models.CharField(default='#93c0d7', max_length=7, verbose_name='رنگ 3')),
            ],
            options={
                'verbose_name': 'تم',
                'verbose_name_plural': 'تم\u200cهای پیشفرض',
                'ordering': ['id'],
            },
        ),
        migrations.RemoveField(
            model_name='user',
            name='color',
        ),
        migrations.AddField(
            model_name='user',
            name='main',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='رنگ اصلی'),
        ),
        migrations.AddField(
            model_name='user',
            name='tint1',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='رنگ 1'),
        ),
        migrations.AddField(
            model_name='user',
            name='tint2',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='رنگ 2'),
        ),
        migrations.AddField(
            model_name='user',
            name='tint3',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='رنگ 3'),
        ),
    ]
