# Generated by Django 5.0.4 on 2025-08-05 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0077_theme_remove_user_color_user_main_user_tint1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='them',
        ),
    ]
