# Generated by Django 5.0.4 on 2025-08-05 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0078_remove_user_them'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='them',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.theme', verbose_name='تم'),
        ),
    ]
