# Generated by Django 5.0.4 on 2025-08-05 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0079_user_them'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='them',
            new_name='theme',
        ),
    ]
