# Generated by Django 5.0.4 on 2025-08-19 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0080_rename_them_user_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='bg',
            field=models.ImageField(upload_to='theme_bg', verbose_name='عکس زمینه'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='main',
            field=models.CharField(max_length=7, verbose_name='رنگ اصلی'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='tint1',
            field=models.CharField(max_length=7, verbose_name='رنگ 1'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='tint2',
            field=models.CharField(max_length=7, verbose_name='رنگ 2'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='tint3',
            field=models.CharField(max_length=7, verbose_name='رنگ 3'),
        ),
        migrations.AlterField(
            model_name='user',
            name='bg',
            field=models.ImageField(blank=True, null=True, upload_to='user_bg', verbose_name='عکس زمینه'),
        ),
    ]
