# Generated by Django 5.0.4 on 2025-08-26 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0081_alter_theme_bg_alter_theme_main_alter_theme_tint1_and_more'),
        ('st', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='st.state', verbose_name='کاربر استان'),
        ),
    ]
