# Generated by Django 5.0.4 on 2025-09-14 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0082_user_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='proclamation',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='proclamation/thumbnail/', verbose_name='تصویر کوچک'),
        ),
        migrations.AlterField(
            model_name='proclamation',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='proclamation/poster', verbose_name='پوستر'),
        ),
    ]
