# Generated by Django 5.0.4 on 2025-09-15 11:55

import core.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0083_proclamation_thumbnail_alter_proclamation_poster'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان')),
                ('svg', models.TextField(verbose_name='آیکون svg')),
                ('levels', core.models.ModifiedArrayField(base_field=models.CharField(choices=[('رئیس', 'رئیس'), ('معاون و مدیرکل مستقل', 'معاون و مدیرکل مستقل'), ('مدیرکل تابعه', 'مدیرکل تابعه'), ('معاون مدیرکل', 'معاون مدیرکل'), ('مدیر', 'مدیر'), ('مشاور', 'مشاور'), ('کارشناس', 'کارشناس'), ('مسئول دفتر', 'مسئول دفتر'), ('کاردان', 'کاردان'), ('تأسیسات', 'تأسیسات'), ('خدمات', 'خدمات'), ('راننده', 'راننده'), ('حفاظت فیزیکی', 'حفاظت فیزیکی')], max_length=20), blank=True, default=list, help_text='خالی یعنی همه مجازند', size=None, verbose_name='رده\u200cهای سازمانی')),
                ('should_has_post', models.BooleanField(default=True, verbose_name='فقط کاربران دارای پست')),
                ('interim_not_allowed', models.BooleanField(default=False, verbose_name='فقط کاربران دائم (غیر موقت)')),
                ('groups', models.ManyToManyField(default=list, help_text='خالی یعنی همه مجازند', to='auth.group', verbose_name='گروه\u200cهای مجاز')),
                ('posts', models.ManyToManyField(default=list, help_text='خالی یعنی همه مجازند', to='core.post', verbose_name='پستهای مجاز')),
                ('users', models.ManyToManyField(default=list, help_text='خالی یعنی همه مجازند', to=settings.AUTH_USER_MODEL, verbose_name='کاربران مجاز')),
            ],
            options={
                'verbose_name': 'منو',
                'verbose_name_plural': 'منو',
                'ordering': ['id'],
            },
        ),
    ]
