# Generated by Django 5.0.4 on 2025-09-16 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0085_alter_menu_groups_alter_menu_posts_alter_menu_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='menu_order',
            field=models.CharField(default='16-17-5-6-3-14-8-7-9-12-10-11-13-18-1-15', editable=False, max_length=100, verbose_name='ترتیب نمایش آیتمهای منو'),
        ),
    ]
