# Generated by Django 5.0.4 on 2025-09-16 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0086_user_menu_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='key',
            field=models.CharField(max_length=20, null=True, verbose_name='کلید'),
        ),
    ]
