# Generated by Django 5.0.4 on 2025-09-16 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0087_menu_key'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['key'], 'verbose_name': 'منو', 'verbose_name_plural': 'منو'},
        ),
        migrations.RemoveField(
            model_name='menu',
            name='id',
        ),
        migrations.AlterField(
            model_name='menu',
            name='key',
            field=models.CharField(default='a', max_length=20, primary_key=True, serialize=False, verbose_name='کلید'),
            preserve_default=False,
        ),
    ]
