# Generated by Django 5.0.4 on 2025-09-16 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0088_alter_menu_options_remove_menu_id_alter_menu_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='posts',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='users',
        ),
    ]
