# Generated by Django 5.0.4 on 2025-09-16 12:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0089_remove_menu_groups_remove_menu_posts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='groups',
            field=models.ManyToManyField(blank=True, default=list, help_text='خالی یعنی همه مجازند', to='auth.group', verbose_name='گروه\u200cهای مجاز'),
        ),
        migrations.AddField(
            model_name='menu',
            name='posts',
            field=models.ManyToManyField(blank=True, default=list, help_text='خالی یعنی همه مجازند', to='core.post', verbose_name='پستهای مجاز'),
        ),
        migrations.AddField(
            model_name='menu',
            name='users',
            field=models.ManyToManyField(blank=True, default=list, help_text='خالی یعنی همه مجازند', to=settings.AUTH_USER_MODEL, verbose_name='کاربران مجاز'),
        ),
    ]
