# Generated by Django 5.0.4 on 2025-09-17 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0090_menu_groups_menu_posts_menu_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='menu_order',
            field=models.CharField(default='chat,flow,task,calendar,food,timesheet,food-manager,flow-manager,invoice,project,report,contract,allocation,pay,proclamation,article', editable=False, max_length=200, verbose_name='ترتیب نمایش آیتمهای منو'),
        ),
    ]
