# Generated by Django 5.0.4 on 2025-09-20 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0091_alter_user_menu_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='icon',
            field=models.CharField(default='a', max_length=10, verbose_name='آیکون'),
            preserve_default=False,
        ),
    ]
