# Generated by Django 5.0.4 on 2025-09-20 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0092_menu_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='icon',
            field=models.CharField(max_length=50, verbose_name='آیکون'),
        ),
    ]
