# Generated by Django 5.0.4 on 2025-09-21 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0093_alter_menu_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='svg',
        ),
    ]
