# Generated by Django 5.0.4 on 2025-10-07 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0094_remove_menu_svg'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='pay',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cn.pay', verbose_name='پرداخت قرارداد'),
        ),
    ]
