# Generated by Django 5.0.4 on 2025-10-19 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0095_notification_pay'),
    ]

    operations = [
        migrations.AddField(
            model_name='proclamation',
            name='main_page_order',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
