# Generated by Django 5.0.4 on 2025-10-19 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0096_proclamation_main_page_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proclamation',
            name='main_page_order',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='الویت نمابش در صفحه اول'),
        ),
    ]
