# Generated by Django 5.0.4 on 2025-10-25 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0097_alter_proclamation_main_page_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='proclamation',
            name='view_count',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد بازدید'),
        ),
    ]
