# Generated by Django 5.0.4 on 2025-10-25 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0098_proclamation_view_count'),
    ]

    operations = [
      #
    ]
