# Generated by Django 5.0.4 on 2025-10-25 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0099_alter_proclamationseen_unique_together'),
    ]

    operations = [
       #
    ]
