# Generated by Django 5.0.4 on 2025-10-27 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0101_loginattempt'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoginAttempt',
        ),
    ]
