# Generated by Django 5.0.4 on 2025-11-02 13:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0102_delete_loginattempt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان')),
            ],
            options={
                'verbose_name': 'داشبورد',
                'verbose_name_plural': 'داشبورد',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DashboardAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_global', models.BooleanField(default=False, help_text='برای مشاهده فقط واحد خودش، تیک را بردارید', verbose_name='مشاهده اطلاعات کل مرکز')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.dashboard', verbose_name='داشبورد')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'دسترسی داشبورد',
                'verbose_name_plural': 'دسترسی داشبورد',
                'ordering': ['id'],
                'unique_together': {('dashboard', 'user')},
            },
        ),
    ]
