# Generated by Django 5.0.4 on 2025-11-19 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0104_useractivitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivitylog',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
