# Generated by Django 5.0.4 on 2025-11-19 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0105_useractivitylog_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='state',
        ),
    ]
