# Generated by Django 5.0.4 on 2025-12-03 07:12

import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0106_remove_user_state'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useractivitylog',
            options={'ordering': ['-timestamp'], 'verbose_name': 'لاگ فعالیت کاربر', 'verbose_name_plural': 'لاگ فعالیت کاربر'},
        ),
        migrations.CreateModel(
            name='UserAuthLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ و زمان ورود')),
                ('logout_at', django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='تاریخ و زمان خروچ')),
                ('ip', models.CharField(max_length=20)),
                ('token', models.CharField(max_length=50)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('is_suspicious', models.BooleanField(default=False, verbose_name='مشکوک اصت نباز به اطلاع')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_histories', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
