# Generated by Django 5.0.4 on 2025-12-03 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0107_alter_useractivitylog_options_userauthlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivitylog',
            name='session_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
