# Generated by Django 5.0.4 on 2025-12-03 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0108_alter_useractivitylog_session_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='userauthlog',
            name='is_login',
            field=models.BooleanField(default=False),
        ),
    ]
