# Generated by Django 5.0.4 on 2025-12-03 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0109_userauthlog_is_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userauthlog',
            name='is_login',
        ),
    ]
