# Generated by Django 5.0.4 on 2025-12-03 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0110_remove_userauthlog_is_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='userauthlog',
            name='notified',
            field=models.BooleanField(default=False),
        ),
    ]
