# Generated by Django 5.0.4 on 2025-12-03 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0111_userauthlog_notified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userauthlog',
            name='notified',
        ),
    ]
