# Generated by Django 5.0.4 on 2026-01-12 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0112_remove_userauthlog_notified'),
    ]

    operations = [
        migrations.AddField(
            model_name='sms',
            name='status',
            field=models.CharField(choices=[('sent', 'Sent'), ('sending', 'Sending'), ('failed', 'Failed')], default='sending', max_length=10),
        ),
        migrations.AddField(
            model_name='sms',
            name='token',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
