# Generated by Django 5.0.4 on 2026-01-20 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0113_sms_status_sms_token'),
    ]

    operations = [

    ]
