# Generated by Django 5.0.4 on 2026-01-27 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0114_user_signature'),
    ]

    operations = [

    ]
