# Generated by Django 5.0.4 on 2026-01-31 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0115_logintheme'),
    ]

    operations = [

    ]
