# Generated by Django 5.0.4 on 2026-01-31 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0116_remove_user_signature'),
    ]

    operations = [

    ]
