# Generated by Django 5.0.4 on 2026-02-09 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0117_user_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='slug',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='اسلاگ'),
        ),
    ]
