# Generated by Django 5.0.4 on 2024-07-01 04:19

import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prj', '0011_project_year'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='یا عنوان یکی از فازهای قرارداد است یا «تسویه بیمه» یا «تسویه حسن انجام کار»', max_length=200, verbose_name='عنوان پرداخت')),
                ('bill_requested', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='مبلغ درخواست شده')),
                ('date', django_jalali.db.models.jDateField(verbose_name='تاریخ')),
                ('note', models.TextField(blank=True, null=True, verbose_name='شرح')),
                ('insurance', models.PositiveBigIntegerField(default=0, help_text='از هر پرداخت پنج درصد کسر می\u200cشود، مگر اینکه «تسویه بیمه» باشد یا مفاصا قبلاً ارائه شده باشد', verbose_name='بیمه')),
                ('performance', models.PositiveBigIntegerField(default=0, help_text='از هر پرداخت کسر می\u200cشود، مگر اینکه «تسویه حسن انجام کار» باشد', verbose_name='حسن انجام کار')),
                ('tax', models.PositiveBigIntegerField(default=0, help_text='اضافه می\u200cشود', verbose_name='مالیات بر ارزش افزوده')),
                ('bill', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='قابل پرداخت')),
                ('insurance_settled', models.BooleanField(default=False, verbose_name='بیمه تسویه شد')),
                ('performance_settled', models.BooleanField(default=False, verbose_name='حسن انجام کار تسویه شد')),
                ('status', models.CharField(choices=[('ثبت درخواست', 'ثبت درخواست'), ('تأیید (معاونت توسعه)', 'تأیید (معاونت توسعه)'), ('بررسی (مدیریت قراردادها)', 'بررسی (مدیریت قراردادها)'), ('دستور پرداخت (اداره\u200cکل اداری و مالی)', 'دستور پرداخت (اداره\u200cکل اداری و مالی)'), ('پرداخت', 'پرداخت'), ('خاتمه', 'خاتمه')], max_length=50, verbose_name='وضعیت')),
                ('create_time', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'پرداخت',
                'verbose_name_plural': 'پرداخت',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(max_length=100, unique=True, verbose_name='شماره قرارداد')),
                ('type', models.CharField(choices=[('پژوهشی', 'پژوهشی'), ('اجرایی', 'اجرایی')], max_length=10, verbose_name='نوع قرارداد')),
                ('genre', models.CharField(choices=[('حقوقی', 'حقوقی'), ('حقیقی', 'حقیقی')], max_length=5, verbose_name='شخصیت مجری')),
                ('contractor', models.CharField(max_length=200, verbose_name='مجری')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان و موضوع قرارداد')),
                ('register_date', django_jalali.db.models.jDateField(verbose_name='تاریخ تنظیم قرارداد')),
                ('start_date', django_jalali.db.models.jDateField(verbose_name='تاریخ آغاز قرارداد')),
                ('finish_date', django_jalali.db.models.jDateField(verbose_name='تاریخ پایان قرارداد')),
                ('price', models.PositiveBigIntegerField(verbose_name='مبلغ قرارداد')),
                ('performance_percent', models.PositiveSmallIntegerField(default=10, help_text='از همه پرداخت\u200cها کم می\u200cشود، قبل از اعمال ارزش افزوده', verbose_name='درصد حسن انجام کار')),
                ('value_added_percent', models.PositiveSmallIntegerField(default=0, help_text='به همه پرداخت\u200cها اضافه می\u200cشود', verbose_name='درصد ارزش افزوده')),
                ('body', models.TextField(default='<p></p>', verbose_name='متن قرارداد')),
                ('status', models.CharField(choices=[('ثبت درخواست', 'ثبت درخواست'), ('تأیید (معاونت توسعه)', 'تأیید (معاونت توسعه)'), ('بررسی (مدیریت قراردادها)', 'بررسی (مدیریت قراردادها)'), ('دستور پرداخت (اداره\u200cکل اداری و مالی)', 'دستور پرداخت (اداره\u200cکل اداری و مالی)'), ('پرداخت', 'پرداخت'), ('خاتمه', 'خاتمه')], max_length=50, verbose_name='وضعیت')),
                ('create_time', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prj.project', verbose_name='پروژه')),
                ('registrar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ثبت کننده قرارداد')),
            ],
            options={
                'verbose_name': 'قرارداد',
                'verbose_name_plural': 'قراردادها',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ContractTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ثبت درخواست', 'ثبت درخواست'), ('تأیید (معاونت توسعه)', 'تأیید (معاونت توسعه)'), ('بررسی (مدیریت قراردادها)', 'بررسی (مدیریت قراردادها)'), ('دستور پرداخت (اداره\u200cکل اداری و مالی)', 'دستور پرداخت (اداره\u200cکل اداری و مالی)'), ('پرداخت', 'پرداخت'), ('خاتمه', 'خاتمه')], max_length=50, verbose_name='وضعیت')),
                ('create_time', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('seen_time', django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='زمان مشاهده')),
                ('done_time', django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='زمان اقدام')),
                ('message', models.TextField(blank=True, null=True, verbose_name='پیام')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cn.contract', verbose_name='قرارداد')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'مراحل قرارداد',
                'verbose_name_plural': 'مراحل قرارداد',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ContractAppendix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('پروپوزال', 'پروپوزال'), ('مدارک هویتی', 'مدارک هویتی'), ('مدرک تحصیلی', 'مدرک تحصیلی'), ('ضمانتنامه', 'ضمانتنامه'), ('فرم استعلام', 'فرم استعلام'), ('ضمانتنامه', 'ضمانتنامه'), ('پیوست فنی', 'پیوست فنی'), ('فرم قرارداد', 'فرم قرارداد'), ('صورتجلسه کمیته پژوهش', 'صورتجلسه کمیته پژوهش'), ('فرم تأمین اعتبار', 'فرم تأمین اعتبار'), ('متن قرارداد', 'متن قرارداد'), ('توافقنامه عدم افشا', 'توافقنامه عدم افشا'), ('الحاقیه', 'الحاقیه'), ('گزارش', 'گزارش'), ('سند هزینه', 'سند هزینه'), ('مفاصا', 'مفاصا'), ('سایر', 'سایر')], max_length=20, verbose_name='نوع')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان')),
                ('file', models.FileField(upload_to='', verbose_name='فایل')),
                ('create_time', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appendices', to='cn.contract', verbose_name='قرارداد')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('pay', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cn.pay', verbose_name='پرداخت')),
            ],
            options={
                'verbose_name': 'پیوست',
                'verbose_name_plural': 'پیوست\u200cهای قرارداد',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PayTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ثبت درخواست', 'ثبت درخواست'), ('تأیید (معاونت توسعه)', 'تأیید (معاونت توسعه)'), ('بررسی (مدیریت قراردادها)', 'بررسی (مدیریت قراردادها)'), ('دستور پرداخت (اداره\u200cکل اداری و مالی)', 'دستور پرداخت (اداره\u200cکل اداری و مالی)'), ('پرداخت', 'پرداخت'), ('خاتمه', 'خاتمه')], max_length=50, verbose_name='وضعیت')),
                ('create_time', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('seen_time', django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='زمان مشاهده')),
                ('done_time', django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='زمان اقدام')),
                ('message', models.TextField(blank=True, null=True, verbose_name='پیام')),
                ('pay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cn.pay', verbose_name='پرداخت')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'مراحل پرداخت',
                'verbose_name_plural': 'مراحل پرداخت',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('percent', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='درصد')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cn.contract', verbose_name='قرارداد')),
            ],
            options={
                'verbose_name': 'مرحله قرارداد',
                'verbose_name_plural': 'مراحل قرارداد',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='pay',
            name='step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pays', to='cn.step', verbose_name='مرحله قرارداد'),
        ),
        migrations.CreateModel(
            name='Supplement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(max_length=100, unique=True, verbose_name='شماره الحاقیه')),
                ('date', django_jalali.db.models.jDateField(verbose_name='تاریخ الحاقیه')),
                ('price', models.BigIntegerField(blank=True, null=True, verbose_name='مبلغ الحاقیه')),
                ('start_date', django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ آغاز جدید')),
                ('finish_date', django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ پایان جدید')),
                ('description', models.TextField(blank=True, null=True, verbose_name='شرح الحاقیه')),
                ('create_date', django_jalali.db.models.jDateField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cn.contract', verbose_name='قرارداد')),
            ],
            options={
                'verbose_name': 'الحاقیه',
                'verbose_name_plural': 'الحاقیه\u200cها',
                'ordering': ('id',),
            },
        ),
    ]
