# Generated by Django 5.0.4 on 2024-07-01 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cn', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pay',
            name='contract',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cn.contract', verbose_name='قرارداد'),
            preserve_default=False,
        ),
    ]
