# Generated by Django 5.0.4 on 2024-07-07 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cn', '0002_pay_contract'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contracttask',
            options={'ordering': ['id'], 'verbose_name': 'مرحله', 'verbose_name_plural': 'مراحل پیشرفت قرارداد'},
        ),
        migrations.AlterModelOptions(
            name='step',
            options={'ordering': ['id'], 'verbose_name': 'فاز', 'verbose_name_plural': 'فازهای قرارداد'},
        ),
        migrations.AlterField(
            model_name='contract',
            name='no',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='شماره قرارداد'),
        ),
    ]
