# Generated by Django 5.0.4 on 2024-07-17 05:06

import django.db.models.deletion
import django.utils.timezone
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cn', '0003_alter_contracttask_options_alter_step_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contracttask',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='contracttask',
            name='done_time',
        ),
        migrations.RemoveField(
            model_name='contracttask',
            name='seen_time',
        ),
        migrations.AddField(
            model_name='contracttask',
            name='time',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='زمان'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('ثبت درخواست', 'ثبت درخواست'), ('بررسی اعتبار', 'بررسی اعتبار'), ('کنترل مستندات', 'کنترل مستندات'), ('کمیته پژوهش', 'کمیته پژوهش'), ('بررسی نهایی', 'بررسی نهایی'), ('تأمین اعتبار', 'تأمین اعتبار'), ('تهیه پیش\u200cنویس', 'تهیه پیش\u200cنویس'), ('تأیید پیش\u200cنویس', 'تأیید پیش\u200cنویس'), ('امضای قرارداد', 'امضای قرارداد'), ('خاتمه', 'خاتمه')], default='ثبت درخواست', max_length=50, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='contracttask',
            name='status',
            field=models.CharField(choices=[('ثبت درخواست', 'ثبت درخواست'), ('بررسی اعتبار', 'بررسی اعتبار'), ('کنترل مستندات', 'کنترل مستندات'), ('کمیته پژوهش', 'کمیته پژوهش'), ('بررسی نهایی', 'بررسی نهایی'), ('تأمین اعتبار', 'تأمین اعتبار'), ('تهیه پیش\u200cنویس', 'تهیه پیش\u200cنویس'), ('تأیید پیش\u200cنویس', 'تأیید پیش\u200cنویس'), ('امضای قرارداد', 'امضای قرارداد'), ('خاتمه', 'خاتمه')], max_length=50, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='step',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='cn.contract', verbose_name='قرارداد'),
        ),
    ]
