# Generated by Django 5.0.4 on 2024-07-17 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cn', '0004_remove_contracttask_create_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contracttask',
            old_name='message',
            new_name='note',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='status',
        ),
        migrations.RemoveField(
            model_name='contracttask',
            name='status',
        ),
        migrations.AddField(
            model_name='contract',
            name='accept_note',
            field=models.TextField(blank=True, null=True, verbose_name='شرح نظر معاون توسعه'),
        ),
        migrations.AddField(
            model_name='contract',
            name='accepted',
            field=models.BooleanField(blank=True, null=True, verbose_name='نظر معاون توسعه'),
        ),
        migrations.AddField(
            model_name='contract',
            name='committee_accepted',
            field=models.BooleanField(blank=True, null=True, verbose_name='نظر کمیته پژوهش'),
        ),
        migrations.AddField(
            model_name='contract',
            name='committee_note',
            field=models.TextField(blank=True, null=True, verbose_name='شرح نظر کمیته پژوهش'),
        ),
        migrations.AddField(
            model_name='contract',
            name='contractor_no',
            field=models.PositiveBigIntegerField(default=1, verbose_name='کد ملی یا شناسه شرکت'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contract',
            name='control_note',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات کنترل مستندات'),
        ),
        migrations.AddField(
            model_name='contract',
            name='controlled',
            field=models.BooleanField(blank=True, null=True, verbose_name='کنترل مستندات'),
        ),
        migrations.AddField(
            model_name='contract',
            name='draft_accept',
            field=models.BooleanField(blank=True, null=True, verbose_name='تأیید پیش\u200cنویس'),
        ),
        migrations.AddField(
            model_name='contract',
            name='draft_note',
            field=models.TextField(blank=True, null=True, verbose_name='اصلاحات پیش\u200cنویس'),
        ),
        migrations.AddField(
            model_name='contract',
            name='drafted',
            field=models.BooleanField(default=True, verbose_name='تهیه پیش\u200cنویس'),
        ),
        migrations.AddField(
            model_name='contract',
            name='funded',
            field=models.BooleanField(default=True, verbose_name='تأمین اعتبار'),
        ),
        migrations.AddField(
            model_name='contract',
            name='locked',
            field=models.BooleanField(default=False, verbose_name='قفل و ارسال'),
        ),
        migrations.AddField(
            model_name='contract',
            name='need_committee',
            field=models.BooleanField(default=True, verbose_name='نیاز به کمیته پژوهش دارد'),
        ),
        migrations.AddField(
            model_name='contract',
            name='pre_fund_note',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات بررسی اولیه بودجه'),
        ),
        migrations.AddField(
            model_name='contract',
            name='pre_funded',
            field=models.BooleanField(blank=True, null=True, verbose_name='بررسی اولیه بودجه'),
        ),
        migrations.AddField(
            model_name='contract',
            name='published',
            field=models.BooleanField(default=False, verbose_name='انتشار'),
        ),
        migrations.AddField(
            model_name='contracttask',
            name='accept',
            field=models.BooleanField(default=True, verbose_name='تأیید'),
        ),
        migrations.AddField(
            model_name='contracttask',
            name='step',
            field=models.CharField(default=1, max_length=50, verbose_name='مرحله'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contracttask',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='cn.contract', verbose_name='قرارداد'),
        ),
    ]
