# Generated by Django 5.0.4 on 2024-07-17 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cn', '0005_rename_message_contracttask_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='contractor_no',
            field=models.CharField(max_length=20, verbose_name='کد ملی یا شناسه شرکت'),
        ),
    ]
