# Generated by Django 5.0.4 on 2024-07-20 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cn', '0006_alter_contract_contractor_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractappendix',
            name='type',
            field=models.CharField(choices=[('پروپوزال', 'پروپوزال'), ('مدارک هویتی', 'مدارک هویتی'), ('مدرک تحصیلی', 'مدرک تحصیلی'), ('ضمانتنامه', 'ضمانتنامه'), ('فرم استعلام', 'فرم استعلام'), ('پیوست فنی', 'پیوست فنی'), ('فرم قرارداد', 'فرم قرارداد'), ('صورتجلسه کمیته پژوهش', 'صورتجلسه کمیته پژوهش'), ('فرم تأمین اعتبار', 'فرم تأمین اعتبار'), ('متن قرارداد', 'متن قرارداد'), ('توافقنامه عدم افشا', 'توافقنامه عدم افشا'), ('الحاقیه', 'الحاقیه'), ('گزارش', 'گزارش'), ('سند هزینه', 'سند هزینه'), ('مفاصا', 'مفاصا'), ('سایر', 'سایر')], max_length=20, verbose_name='نوع'),
        ),
    ]
