# Generated by Django 5.0.4 on 2024-07-30 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cn', '0007_alter_contractappendix_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='body',
            field=models.TextField(blank=True, null=True, verbose_name='متن قرارداد'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='drafted',
            field=models.BooleanField(default=False, verbose_name='تهیه پیش\u200cنویس'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='funded',
            field=models.BooleanField(default=False, verbose_name='تأمین اعتبار'),
        ),
    ]
