# Generated by Django 5.0.4 on 2024-07-30 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cn', '0008_alter_contract_body_alter_contract_drafted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractappendix',
            name='type',
        ),
    ]
