# Generated by Django 5.0.4 on 2024-08-04 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cn', '0009_remove_contractappendix_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contracttask',
            old_name='step',
            new_name='status',
        ),
        migrations.AlterField(
            model_name='pay',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pays', to='cn.contract', verbose_name='قرارداد'),
        ),
        migrations.AlterField(
            model_name='supplement',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplements', to='cn.contract', verbose_name='قرارداد'),
        ),
    ]
