# Generated by Django 5.0.4 on 2024-08-05 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cn', '0010_rename_step_contracttask_status_alter_pay_contract_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='pre_fund_note',
            new_name='prefund_note',
        ),
        migrations.RenameField(
            model_name='contract',
            old_name='pre_funded',
            new_name='prefunded',
        ),
    ]
