# Generated by Django 5.0.4 on 2024-08-05 03:23

import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cn', '0011_rename_pre_fund_note_contract_prefund_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='need_inquiry',
            field=models.BooleanField(default=True, verbose_name='نیاز به استعلام جدید دارد'),
        ),
        migrations.AddField(
            model_name='contract',
            name='need_inquiry_date',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name=''),
        ),
    ]
