# Generated by Django 5.0.4 on 2024-08-05 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cn', '0012_contract_need_inquiry_contract_need_inquiry_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='draft_accept',
            new_name='draft_accepted',
        ),
    ]
