# Generated by Django 5.0.4 on 2024-08-10 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cn', '0013_rename_draft_accept_contract_draft_accepted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paytask',
            old_name='message',
            new_name='note',
        ),
        migrations.AddField(
            model_name='pay',
            name='accept_note',
            field=models.TextField(blank=True, null=True, verbose_name='شرح تأیید'),
        ),
        migrations.AddField(
            model_name='pay',
            name='control_note',
            field=models.TextField(blank=True, null=True, verbose_name='شرح کنترل مستندات'),
        ),
        migrations.AddField(
            model_name='pay',
            name='fund_note',
            field=models.TextField(blank=True, null=True, verbose_name='شرح دستور پرداخت'),
        ),
        migrations.AddField(
            model_name='pay',
            name='pay_note',
            field=models.TextField(blank=True, null=True, verbose_name='شرح پرداخت'),
        ),
        migrations.AlterField(
            model_name='pay',
            name='status',
            field=models.CharField(choices=[('ثبت درخواست', 'ثبت درخواست'), ('اصلاح درخواست', 'اصلاح درخواست'), ('کنترل مستندات', 'کنترل مستندات'), ('بررسی درخواست', 'بررسی درخواست'), ('دستور پرداخت', 'دستور پرداخت'), ('پرداخت', 'پرداخت'), ('خاتمه', 'خاتمه')], max_length=50, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='paytask',
            name='status',
            field=models.CharField(choices=[('ثبت درخواست', 'ثبت درخواست'), ('اصلاح درخواست', 'اصلاح درخواست'), ('کنترل مستندات', 'کنترل مستندات'), ('بررسی درخواست', 'بررسی درخواست'), ('دستور پرداخت', 'دستور پرداخت'), ('پرداخت', 'پرداخت'), ('خاتمه', 'خاتمه')], max_length=50, verbose_name='وضعیت'),
        ),
    ]
