# Generated by Django 5.0.4 on 2024-08-10 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cn', '0014_rename_message_paytask_note_pay_accept_note_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paytask',
            name='done_time',
        ),
        migrations.RemoveField(
            model_name='paytask',
            name='seen_time',
        ),
        migrations.AlterField(
            model_name='paytask',
            name='pay',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='cn.pay', verbose_name='پرداخت'),
        ),
    ]
