# Generated by Django 5.0.4 on 2024-09-15 06:13

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cn', '0015_remove_paytask_done_time_remove_paytask_seen_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='performance_percent',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='register_date',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='value_added_percent',
        ),
        migrations.AlterField(
            model_name='contract',
            name='need_inquiry_date',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ ثبت درخواست استعلام'),
        ),
    ]
