# Generated by Django 5.0.4 on 2024-09-15 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cn', '0016_remove_contract_performance_percent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='step',
            name='title',
        ),
    ]
