# Generated by Django 5.0.4 on 2024-09-18 05:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cn', '0017_remove_step_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pay',
            name='contract',
        ),
        migrations.RemoveField(
            model_name='pay',
            name='insurance',
        ),
        migrations.RemoveField(
            model_name='pay',
            name='insurance_settled',
        ),
        migrations.RemoveField(
            model_name='pay',
            name='performance',
        ),
        migrations.RemoveField(
            model_name='pay',
            name='performance_settled',
        ),
        migrations.RemoveField(
            model_name='pay',
            name='tax',
        ),
        migrations.AddField(
            model_name='contract',
            name='f_acquittance',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='مفاصا'),
        ),
        migrations.AddField(
            model_name='contract',
            name='f_acquittance_letter',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='نامه درخواست مفاصا'),
        ),
        migrations.AddField(
            model_name='contract',
            name='f_contract',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='متن قرارداد'),
        ),
        migrations.AddField(
            model_name='contract',
            name='f_draft',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='پیش\u200cنویس قرارداد'),
        ),
        migrations.AddField(
            model_name='contract',
            name='f_exchange_letter',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='نامه مبادله قرارداد'),
        ),
        migrations.AddField(
            model_name='contract',
            name='f_non_disclosure_agreement',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='قرارداد عدم افشا'),
        ),
        migrations.AddField(
            model_name='contract',
            name='f_proposal',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='پروپوزال'),
        ),
        migrations.AddField(
            model_name='contract',
            name='f_technical_attachment',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='پیوست فنی'),
        ),
        migrations.AddField(
            model_name='contract',
            name='f_warranty',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='ضمانتنامه'),
        ),
        migrations.CreateModel(
            name='ContractParty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام')),
                ('f_nc', models.FileField(blank=True, null=True, upload_to='', verbose_name='کارت ملی')),
                ('f_bc', models.FileField(blank=True, null=True, upload_to='', verbose_name='شناسنامه')),
                ('f_d', models.FileField(blank=True, null=True, upload_to='', verbose_name='مدرک تحصیلی')),
                ('f_msc', models.FileField(blank=True, null=True, upload_to='', verbose_name='کارت پایان خدمت وظیفه')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appendices', to='cn.contract', verbose_name='قرارداد')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'طرف قرارداد',
                'verbose_name_plural': 'مدارک هویتی طرف قرارداد',
                'ordering': ['id'],
            },
        ),
        migrations.DeleteModel(
            name='ContractAppendix',
        ),
    ]
