# Generated by Django 5.0.4 on 2024-09-18 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cn', '0018_remove_pay_contract_remove_pay_insurance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractparty',
            name='user',
        ),
        migrations.AlterField(
            model_name='contract',
            name='f_non_disclosure_agreement',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='توافقنامه عدم افشا'),
        ),
        migrations.AlterField(
            model_name='contractparty',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parties', to='cn.contract', verbose_name='قرارداد'),
        ),
    ]
