# Generated by Django 5.0.4 on 2024-09-22 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cn', '0019_remove_contractparty_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pay',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='فایل'),
        ),
    ]
