# Generated by Django 5.0.4 on 2024-09-22 07:42

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cn', '0020_pay_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pay',
            name='title',
        ),
        migrations.AlterField(
            model_name='pay',
            name='date',
            field=django_jalali.db.models.jDateField(auto_now_add=True, verbose_name='تاریخ'),
        ),
    ]
