# Generated by Django 5.0.4 on 2024-09-22 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cn', '0021_remove_pay_title_alter_pay_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pay',
            options={'ordering': ['id'], 'verbose_name': 'پرداخت', 'verbose_name_plural': 'پرداخت'},
        ),
        migrations.RemoveField(
            model_name='pay',
            name='status',
        ),
        migrations.AddField(
            model_name='pay',
            name='accepted',
            field=models.BooleanField(blank=True, null=True, verbose_name='پرداخت تأیید شد'),
        ),
        migrations.AddField(
            model_name='pay',
            name='controlled',
            field=models.BooleanField(blank=True, null=True, verbose_name='مستندات بررسی و تأیید شد'),
        ),
        migrations.AddField(
            model_name='pay',
            name='funded',
            field=models.BooleanField(default=False, verbose_name='دستور پرداخت صادر شد'),
        ),
        migrations.AddField(
            model_name='pay',
            name='paid',
            field=models.BooleanField(default=False, verbose_name='پرداخت شد'),
        ),
        migrations.AddField(
            model_name='pay',
            name='sent',
            field=models.BooleanField(default=False, verbose_name='ارسال شد'),
        ),
        migrations.AlterField(
            model_name='paytask',
            name='status',
            field=models.CharField(max_length=50, verbose_name='وضعیت'),
        ),
    ]
