# Generated by Django 5.0.4 on 2024-09-23 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cn', '0022_alter_pay_options_remove_pay_status_pay_accepted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pay',
            name='funded',
            field=models.BooleanField(blank=True, null=True, verbose_name='دستور پرداخت صادر شد'),
        ),
        migrations.AlterField(
            model_name='pay',
            name='paid',
            field=models.BooleanField(blank=True, null=True, verbose_name='پرداخت شد'),
        ),
    ]
