# Generated by Django 5.0.4 on 2024-09-23 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cn', '0023_alter_pay_funded_alter_pay_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pay',
            name='sent',
        ),
    ]
