# Generated by Django 5.0.4 on 2024-10-07 03:14

import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cn', '0024_remove_pay_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='approve_note',
            field=models.TextField(blank=True, null=True, verbose_name='شرح نظر رئیس مرکز'),
        ),
        migrations.AddField(
            model_name='contract',
            name='approved',
            field=models.BooleanField(blank=True, null=True, verbose_name='نظر رئیس مرکز'),
        ),
        migrations.AddField(
            model_name='contract',
            name='period',
            field=models.CharField(blank=True, help_text='در صورت خالی بودن تاریخ آغاز و پایان، این فیلد باید تکمیل شود', null=True, verbose_name='مدت قرارداد'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='finish_date',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ پایان قرارداد'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='start_date',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ آغاز قرارداد'),
        ),
    ]
