# Generated by Django 5.0.4 on 2024-10-16 03:58

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cn', '0025_contract_approve_note_contract_approved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='body',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='متن قرارداد'),
        ),
    ]
