# Generated by Django 5.0.4 on 2024-10-16 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cn', '0026_alter_contract_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='f_newspaper',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='روزنامه رسمی'),
        ),
        migrations.AddField(
            model_name='contract',
            name='f_statute',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='اساسنامه'),
        ),
        migrations.AddField(
            model_name='contract',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='شرح'),
        ),
    ]
