# Generated by Django 5.0.4 on 2024-10-30 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cn', '0027_contract_f_newspaper_contract_f_statute_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='f_etc1',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='سایر 1'),
        ),
        migrations.AddField(
            model_name='contract',
            name='f_etc2',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='سایر 2'),
        ),
        migrations.AddField(
            model_name='contract',
            name='f_etc3',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='سایر 3'),
        ),
    ]
