# Generated by Django 5.0.4 on 2024-10-30 06:58

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cn', '0028_contract_f_etc1_contract_f_etc2_contract_f_etc3'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None, verbose_name='دستور جلسه'),
        ),
    ]
