# Generated by Django 5.0.4 on 2024-11-17 03:24

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cn', '0029_contract_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None, verbose_name='برچسب'),
        ),
    ]
