# Generated by Django 5.0.4 on 2024-11-19 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cn', '0030_alter_contract_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='percent',
            field=models.PositiveBigIntegerField(verbose_name='مبلغ یا درصد'),
        ),
    ]
