# Generated by Django 5.0.4 on 2024-12-07 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cn', '0031_alter_step_percent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان')),
            ],
            options={
                'verbose_name': 'توافقنامه',
                'verbose_name_plural': 'توافقنامه',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='contract',
            name='agreement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cn.agreement', verbose_name='توافقنامه'),
        ),
    ]
