# Generated by Django 5.0.4 on 2025-01-27 04:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cn', '0032_agreement_contract_agreement'),
        ('prj', '0025_project_team'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='prj.project', verbose_name='پروژه'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='registrar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to=settings.AUTH_USER_MODEL, verbose_name='ثبت کننده قرارداد'),
        ),
    ]
