# Generated by Django 5.0.4 on 2025-01-29 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cn', '0033_alter_contract_project_alter_contract_registrar'),
    ]

    operations = [
        migrations.AddField(
            model_name='paytask',
            name='accept',
            field=models.BooleanField(default=True, verbose_name='تأیید'),
        ),
    ]
