# Generated by Django 5.0.4 on 2025-01-29 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cn', '0034_paytask_accept'),
    ]

    operations = [
        migrations.AddField(
            model_name='pay',
            name='commitments',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='انجام کار/تعهدات'),
        ),
        migrations.AddField(
            model_name='pay',
            name='insurance',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='سپرده بیمه'),
        ),
        migrations.AddField(
            model_name='pay',
            name='net',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='خالص پرداختی'),
        ),
        migrations.AddField(
            model_name='pay',
            name='tax',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='مالیات'),
        ),
        migrations.AddField(
            model_name='pay',
            name='value_added',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='ارزش افزوده'),
        ),
    ]
