# Generated by Django 5.0.4 on 2025-02-11 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cn', '0035_pay_commitments_pay_insurance_pay_net_pay_tax_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='cn_note',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='توضیحات خصوصی واحد قراردادها'),
        ),
    ]
