# Generated by Django 5.0.4 on 2025-02-11 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cn', '0036_contract_cn_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='عنوان مرحله'),
        ),
    ]
