# Generated by Django 5.0.4 on 2025-02-11 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cn', '0037_step_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='inquiry',
            field=models.CharField(choices=[('نامشخص', 'نامشخص'), ('نیاز ندارد', 'نیاز ندارد'), ('درانتظار پاسخ استعلام', 'درانتظار پاسخ استعلام'), ('تأیید', 'تأیید'), ('عدم تأیید', 'عدم تأیید')], default='نامشخص', max_length=25, verbose_name='استعلام'),
        ),
    ]
