# Generated by Django 5.0.4 on 2025-02-11 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cn', '0038_contract_inquiry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='need_inquiry',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='need_inquiry_date',
        ),
        migrations.AlterField(
            model_name='step',
            name='title',
            field=models.CharField(default='a', max_length=50, verbose_name='عنوان مرحله'),
            preserve_default=False,
        ),
    ]
