# Generated by Django 5.0.4 on 2025-02-22 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cn', '0039_remove_contract_need_inquiry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='title',
            field=models.CharField(max_length=200, verbose_name='عنوان و موضوع قرارداد'),
        ),
    ]
