# Generated by Django 5.0.4 on 2025-04-08 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cn', '0040_alter_contract_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pay',
            options={'ordering': ['-id'], 'verbose_name': 'پرداخت', 'verbose_name_plural': 'پرداخت'},
        ),
    ]
