# Generated by Django 5.0.4 on 2025-05-06 15:06

import django.db.models.deletion
import django.contrib.postgres.fields
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cn', '0041_alter_pay_options'),
        ('core', '0071_computer_joined_alter_proclamation_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplement',
            options={'ordering': ['id'], 'verbose_name': 'الحاقیه', 'verbose_name_plural': 'الحاقیه\u200cها'},
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, verbose_name='عنوان')),
                ('subtitle', models.CharField(max_length=80, verbose_name='')),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None, verbose_name='برچسب')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='', verbose_name='پوستر')),
                ('summary', models.TextField(verbose_name='چکیده')),
                ('is_available', models.BooleanField(default=True, verbose_name='نمایش داده شود')),
                ('create_time', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('update_time', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='زمان ویرایش')),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cn.contract', verbose_name='قرارداد')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.unit', verbose_name='واحد')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'مقاله',
                'verbose_name_plural': 'مقاله',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ArticleAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, verbose_name='عنوان')),
                ('file', models.FileField(blank=True, null=True, upload_to='', verbose_name='فایل')),
                ('author', models.CharField(blank=True, max_length=80, null=True, verbose_name='مؤلف')),
                ('create_time', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cn.article', verbose_name='مقاله')),
            ],
            options={
                'verbose_name': 'پیوست مقاله',
                'verbose_name_plural': 'پیوست مقاله',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ArticleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, verbose_name='عنوان')),
                ('description', models.TextField(blank=True, null=True, verbose_name='شرح')),
                ('owners', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='ادمین\u200cها')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cn.articlecategory', verbose_name='والد')),
            ],
            options={
                'verbose_name': 'نوع مقاله',
                'verbose_name_plural': 'نوع مقاله',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cn.articlecategory', verbose_name='نوع'),
        ),
        migrations.CreateModel(
            name='ArticleChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='متن')),
                ('create_time', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cn.article', verbose_name='مقاله')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cn.articlechat', verbose_name='والد')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'گفتگو ذیل مقاله',
                'verbose_name_plural': 'گفتگو ذیل مقاله',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ArticleAttachmentPermit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(max_length=100, verbose_name='شرح درخواست')),
                ('accept', models.BooleanField(blank=True, null=True, verbose_name='تأیید')),
                ('create_time', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('update_time', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='زمان ویرایش')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cn.article', verbose_name='مقاله')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'درخواست بارگیری پیوست مقاله',
                'verbose_name_plural': 'درخواست بارگیری پیوست مقاله',
                'ordering': ['id'],
                'unique_together': {('article', 'user')},
            },
        ),
        migrations.CreateModel(
            name='ArticleChatLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.BooleanField(blank=True, null=True, verbose_name='پسند')),
                ('create_time', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cn.articlechat', verbose_name='گفتگو')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پسند گفتگو ذسل مقاله',
                'verbose_name_plural': 'پسند گفتگو ذسل مقاله',
                'ordering': ['id'],
                'unique_together': {('chat', 'user')},
            },
        ),
        migrations.CreateModel(
            name='ArticleRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='امتیاز')),
                ('create_time', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cn.article', verbose_name='مقاله')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'امتیاز مقاله',
                'verbose_name_plural': 'امتیاز مقاله',
                'ordering': ['id'],
                'unique_together': {('article', 'user')},
            },
        ),
    ]
