# Generated by Django 5.0.4 on 2025-05-14 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cn', '0042_alter_supplement_options_article_articleattachment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cn.articlecategory', verbose_name='والد'),
        ),
    ]
