# Generated by Django 5.0.4 on 2025-05-17 11:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cn', '0044_alter_article_subtitle_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articleattachment',
            options={'ordering': ['id'], 'verbose_name': 'پیوست', 'verbose_name_plural': 'مقاله - پیوست'},
        ),
        migrations.AlterModelOptions(
            name='articleattachmentpermit',
            options={'ordering': ['id'], 'verbose_name': 'درخواست', 'verbose_name_plural': 'مقاله - درخواست فایل'},
        ),
        migrations.AlterModelOptions(
            name='articlecategory',
            options={'ordering': ['id'], 'verbose_name': 'نوع', 'verbose_name_plural': 'مقاله - نوع'},
        ),
        migrations.AlterModelOptions(
            name='articlechat',
            options={'ordering': ['id'], 'verbose_name': 'گفتگو', 'verbose_name_plural': 'مقاله - گفتگو'},
        ),
        migrations.AlterModelOptions(
            name='articlechatlike',
            options={'ordering': ['id'], 'verbose_name': 'پسند', 'verbose_name_plural': ' مقاله - پسند گفتگو'},
        ),
        migrations.AlterModelOptions(
            name='articlerate',
            options={'ordering': ['id'], 'verbose_name': 'امتیاز مقاله', 'verbose_name_plural': 'مقاله - امتیاز'},
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='cn.articlecategory', verbose_name='نوع'),
        ),
        migrations.AlterField(
            model_name='article',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='articlecategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='cn.articlecategory', verbose_name='والد'),
        ),
    ]
