# Generated by Django 5.0.4 on 2025-05-17 12:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cn', '0047_alter_articlechat_parent_alter_articlechat_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='articleattachmentpermit',
            name='attachment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='permits', to='cn.articleattachment', verbose_name='فایل مقاله'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='articleattachmentpermit',
            unique_together={('attachment', 'user')},
        ),
        migrations.RemoveField(
            model_name='articleattachmentpermit',
            name='article',
        ),
    ]
