# Generated by Django 5.0.4 on 2025-05-19 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cn', '0048_alter_articleattachmentpermit_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='contract',
        ),
        migrations.AddField(
            model_name='article',
            name='step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cn.step', verbose_name='فاز قرارداد'),
        ),
    ]
