# Generated by Django 5.0.4 on 2025-05-19 10:10

import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cn', '0049_remove_article_contract_article_step'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticlePermit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(max_length=100, verbose_name='شرح درخواست')),
                ('accept', models.BooleanField(blank=True, null=True, verbose_name='تأیید')),
                ('create_time', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('update_time', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='زمان ویرایش')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permits', to='cn.article', verbose_name='مقاله')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'درخواست',
                'verbose_name_plural': 'مقاله - درخواست فایل',
                'ordering': ['id'],
                'unique_together': {('article', 'user')},
            },
        ),
        migrations.DeleteModel(
            name='ArticleAttachmentPermit',
        ),
    ]
