# Generated by Django 5.0.4 on 2025-05-25 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cn', '0050_articlepermit_delete_articleattachmentpermit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlepermit',
            options={'ordering': ['id'], 'verbose_name': 'درخواست', 'verbose_name_plural': 'مقاله - درخواست'},
        ),
        migrations.AlterField(
            model_name='articlechat',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='cn.articlechat', verbose_name='والد'),
        ),
        migrations.AlterField(
            model_name='articlechatlike',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='cn.articlechat', verbose_name='گفتگو'),
        ),
    ]
