# Generated by Django 5.0.4 on 2025-05-27 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cn', '0051_alter_articlepermit_options_alter_articlechat_parent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlechat',
            name='parent',
        ),
        migrations.AlterField(
            model_name='articleattachment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='article_attachments', verbose_name='فایل'),
        ),
    ]
