# Generated by Django 5.0.4 on 2025-05-27 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cn', '0053_alter_articlechat_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlechatlike',
            name='like',
            field=models.BooleanField(default=True, verbose_name='پسند'),
        ),
    ]
