# Generated by Django 5.0.4 on 2025-06-09 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cn', '0056_alter_articlerate_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlechat',
            options={'ordering': ['-id'], 'verbose_name': 'گفتگو', 'verbose_name_plural': 'مقاله - گفتگو'},
        ),
    ]
