# Generated by Django 5.0.4 on 2025-07-09 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cn', '0057_alter_articlechat_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='article_poster', verbose_name='پوستر'),
        ),
    ]
