# Generated by Django 5.0.4 on 2025-07-13 11:34

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cn', '0058_alter_article_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='finish_date',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ پایان'),
        ),
        migrations.AddField(
            model_name='step',
            name='start_date',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ آغاز'),
        ),
    ]
