# Generated by Django 5.0.4 on 2025-07-16 09:11

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cn', '0059_step_finish_date_step_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='finish_date',
            field=django_jalali.db.models.jDateField(default='1404-01-01', verbose_name='تاریخ پایان'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='step',
            name='start_date',
            field=django_jalali.db.models.jDateField(default='1404-01-01', verbose_name='تاریخ آغاز'),
            preserve_default=False,
        ),
    ]
