# Generated by Django 5.0.4 on 2025-09-29 08:11

import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cn', '0060_alter_step_finish_date_alter_step_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='archived',
            field=models.BooleanField(default=False, help_text='قراردادهای رد شده + قراردادهای خاتمه یافته', verbose_name='بایگانی شده'),
        ),
        migrations.AddField(
            model_name='contract',
            name='committee_accept',
            field=models.CharField(blank=True, choices=[('تأیید', 'تأیید'), ('عدم تأیید', 'عدم تأیید'), ('عودت جهت اصلاح', 'عودت جهت اصلاح')], max_length=14, null=True, verbose_name='نظر کمیته پژوهش'),
        ),
        migrations.AddField(
            model_name='contract',
            name='convention_accept',
            field=models.CharField(blank=True, choices=[('تأیید', 'تأیید'), ('عدم تأیید', 'عدم تأیید'), ('عودت جهت اصلاح', 'عودت جهت اصلاح')], max_length=14, null=True, verbose_name='نظر واحد قراردادها'),
        ),
        migrations.AddField(
            model_name='contract',
            name='convention_note',
            field=models.TextField(blank=True, null=True, verbose_name='شرح واحد قراردادها'),
        ),
        migrations.AddField(
            model_name='contract',
            name='deputy_accept',
            field=models.CharField(blank=True, choices=[('تأیید', 'تأیید'), ('عدم تأیید', 'عدم تأیید'), ('عودت جهت اصلاح', 'عودت جهت اصلاح')], max_length=14, null=True, verbose_name='نظر معاون توسعه'),
        ),
        migrations.AddField(
            model_name='contract',
            name='deputy_note',
            field=models.TextField(blank=True, null=True, verbose_name='شرح معاون توسعه'),
        ),
        migrations.AddField(
            model_name='contract',
            name='draft_accept',
            field=models.BooleanField(blank=True, null=True, verbose_name='نظر واحد متقاضی درمورد پیش\u200cنویس'),
        ),
        migrations.AddField(
            model_name='contract',
            name='fund_accept',
            field=models.CharField(blank=True, choices=[('تأیید', 'تأیید'), ('عدم تأیید', 'عدم تأیید'), ('عودت جهت اصلاح', 'عودت جهت اصلاح')], max_length=14, null=True, verbose_name='نظر واحد بودجه'),
        ),
        migrations.AddField(
            model_name='contract',
            name='fund_note',
            field=models.TextField(blank=True, null=True, verbose_name='شرح واحد بودجه'),
        ),
        migrations.AddField(
            model_name='contract',
            name='head_accept',
            field=models.CharField(blank=True, choices=[('تأیید', 'تأیید'), ('عدم تأیید', 'عدم تأیید'), ('عودت جهت اصلاح', 'عودت جهت اصلاح')], max_length=14, null=True, verbose_name='نظر رئیس'),
        ),
        migrations.AddField(
            model_name='contract',
            name='head_note',
            field=models.TextField(blank=True, null=True, verbose_name='شرح رئیس'),
        ),
        migrations.AddField(
            model_name='contract',
            name='manager_accept',
            field=models.CharField(blank=True, choices=[('تأیید', 'تأیید'), ('عدم تأیید', 'عدم تأیید'), ('عودت جهت اصلاح', 'عودت جهت اصلاح')], max_length=14, null=True, verbose_name='نظر مدیر واحد'),
        ),
        migrations.AddField(
            model_name='contract',
            name='manager_note',
            field=models.TextField(blank=True, null=True, verbose_name='شرح مدیر واحد'),
        ),
        migrations.AddField(
            model_name='contract',
            name='receive_from_contractor_date',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ دریافت از پیمانکار'),
        ),
        migrations.AddField(
            model_name='contract',
            name='secretariat_date',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ دبیرخانه'),
        ),
        migrations.AddField(
            model_name='contract',
            name='secretariat_no',
            field=models.IntegerField(blank=True, null=True, verbose_name='شماره دبیرخانه'),
        ),
        migrations.AddField(
            model_name='contract',
            name='send_to_contractor_date',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ ارسال به پیمانکار'),
        ),
        migrations.AddField(
            model_name='contract',
            name='signature_date',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ امضای مقام مجاز'),
        ),
        migrations.AddField(
            model_name='contract',
            name='warranty_type',
            field=models.CharField(blank=True, choices=[('سفته', 'سفته'), ('ضمانتنامه', 'ضمانتنامه'), ('سپرده انجام کار', 'سپرده انجام کار')], max_length=15, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='pay',
            name='clerk_accept',
            field=models.CharField(blank=True, choices=[('تأیید', 'تأیید'), ('عدم تأیید', 'عدم تأیید'), ('عودت جهت اصلاح', 'عودت جهت اصلاح')], max_length=14, null=True, verbose_name='نظر کارشناس مالی'),
        ),
        migrations.AddField(
            model_name='pay',
            name='clerk_note',
            field=models.TextField(blank=True, null=True, verbose_name='شرح کارشناس مالی'),
        ),
        migrations.AddField(
            model_name='pay',
            name='convention_accept',
            field=models.CharField(blank=True, choices=[('تأیید', 'تأیید'), ('عدم تأیید', 'عدم تأیید'), ('عودت جهت اصلاح', 'عودت جهت اصلاح')], max_length=14, null=True, verbose_name='نظر واحد قراردادها'),
        ),
        migrations.AddField(
            model_name='pay',
            name='convention_note',
            field=models.TextField(blank=True, null=True, verbose_name='شرح واحد قراردادها'),
        ),
        migrations.AddField(
            model_name='pay',
            name='deputy_accept',
            field=models.CharField(blank=True, choices=[('تأیید', 'تأیید'), ('عدم تأیید', 'عدم تأیید'), ('عودت جهت اصلاح', 'عودت جهت اصلاح')], max_length=14, null=True, verbose_name='نظر معاون توسعه'),
        ),
        migrations.AddField(
            model_name='pay',
            name='deputy_note',
            field=models.TextField(blank=True, null=True, verbose_name='شرح معاون توسعه'),
        ),
        migrations.AddField(
            model_name='pay',
            name='finance_accept',
            field=models.CharField(blank=True, choices=[('تأیید', 'تأیید'), ('عدم تأیید', 'عدم تأیید'), ('عودت جهت اصلاح', 'عودت جهت اصلاح')], max_length=14, null=True, verbose_name='نظر مدیرکل مالی'),
        ),
        migrations.AddField(
            model_name='pay',
            name='finance_note',
            field=models.TextField(blank=True, null=True, verbose_name='شرح مدیرکل مالی'),
        ),
        migrations.AddField(
            model_name='pay',
            name='fund_accept',
            field=models.CharField(blank=True, choices=[('تأیید', 'تأیید'), ('عدم تأیید', 'عدم تأیید'), ('عودت جهت اصلاح', 'عودت جهت اصلاح')], max_length=14, null=True, verbose_name='نظر واحد بودجه'),
        ),
        migrations.AddField(
            model_name='pay',
            name='manager_accept',
            field=models.CharField(blank=True, choices=[('تأیید', 'تأیید'), ('عدم تأیید', 'عدم تأیید'), ('عودت جهت اصلاح', 'عودت جهت اصلاح')], max_length=14, null=True, verbose_name='نظر مدیر واحد'),
        ),
        migrations.AddField(
            model_name='pay',
            name='manager_note',
            field=models.TextField(blank=True, null=True, verbose_name='شرح مدیر واحد'),
        ),
        migrations.AddField(
            model_name='supplement',
            name='convention_accept',
            field=models.CharField(blank=True, choices=[('تأیید', 'تأیید'), ('عدم تأیید', 'عدم تأیید'), ('عودت جهت اصلاح', 'عودت جهت اصلاح')], max_length=14, null=True, verbose_name='نظر واحد قراردادها'),
        ),
        migrations.AddField(
            model_name='supplement',
            name='convention_note',
            field=models.TextField(blank=True, null=True, verbose_name='شرح واحد قراردادها'),
        ),
        migrations.AddField(
            model_name='supplement',
            name='deputy_accept',
            field=models.CharField(blank=True, choices=[('تأیید', 'تأیید'), ('عدم تأیید', 'عدم تأیید'), ('عودت جهت اصلاح', 'عودت جهت اصلاح')], max_length=14, null=True, verbose_name='نظر معاون توسعه'),
        ),
        migrations.AddField(
            model_name='supplement',
            name='deputy_note',
            field=models.TextField(blank=True, null=True, verbose_name='شرح معاون توسعه'),
        ),
        migrations.AddField(
            model_name='supplement',
            name='manager_accept',
            field=models.CharField(blank=True, choices=[('تأیید', 'تأیید'), ('عدم تأیید', 'عدم تأیید'), ('عودت جهت اصلاح', 'عودت جهت اصلاح')], max_length=14, null=True, verbose_name='نظر مدیر واحد'),
        ),
        migrations.AddField(
            model_name='supplement',
            name='manager_note',
            field=models.TextField(blank=True, null=True, verbose_name='شرح مدیر واحد'),
        ),
        migrations.AddField(
            model_name='supplement',
            name='receive_from_contractor_date',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ دریافت از پیمانکار'),
        ),
        migrations.AddField(
            model_name='supplement',
            name='secretariat_date',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ دبیرخانه'),
        ),
        migrations.AddField(
            model_name='supplement',
            name='secretariat_no',
            field=models.IntegerField(blank=True, null=True, verbose_name='شماره دبیرخانه'),
        ),
        migrations.AddField(
            model_name='supplement',
            name='send_to_contractor_date',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ ارسال به پیمانکار'),
        ),
        migrations.AddField(
            model_name='supplement',
            name='signature_date',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ امضای مقام مجاز'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='committee_note',
            field=models.TextField(blank=True, null=True, verbose_name='شرح کمیته پژوهش'),
        ),
        migrations.AlterField(
            model_name='pay',
            name='fund_note',
            field=models.TextField(blank=True, null=True, verbose_name='شرح واحد بودجه'),
        ),
    ]
