# Generated by Django 5.0.4 on 2025-09-29 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cn', '0061_contract_archived_contract_committee_accept_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pay',
            name='slip',
            field=models.FileField(blank=True, null=True, upload_to='invoice', verbose_name='فیش واریز'),
        ),
    ]
