# Generated by Django 5.0.4 on 2025-10-01 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cn', '0062_pay_slip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='committee_accept',
            field=models.CharField(choices=[('نامشخص', 'نامشخص'), ('تأیید', 'تأیید'), ('عدم تأیید', 'عدم تأیید'), ('عودت جهت اصلاح', 'عودت جهت اصلاح')], default='نامشخص', max_length=14, verbose_name='نظر کمیته پژوهش'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='convention_accept',
            field=models.CharField(choices=[('نامشخص', 'نامشخص'), ('تأیید', 'تأیید'), ('عدم تأیید', 'عدم تأیید'), ('عودت جهت اصلاح', 'عودت جهت اصلاح')], default='نامشخص', max_length=14, verbose_name='نظر واحد قراردادها'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='deputy_accept',
            field=models.CharField(choices=[('نامشخص', 'نامشخص'), ('تأیید', 'تأیید'), ('عدم تأیید', 'عدم تأیید'), ('عودت جهت اصلاح', 'عودت جهت اصلاح')], default='نامشخص', max_length=14, verbose_name='نظر معاون توسعه'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='f_acquittance',
            field=models.FileField(blank=True, default=None, null=True, upload_to='', verbose_name='مفاصا'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='f_acquittance_letter',
            field=models.FileField(blank=True, default=None, null=True, upload_to='', verbose_name='نامه درخواست مفاصا'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='f_contract',
            field=models.FileField(blank=True, default=None, null=True, upload_to='', verbose_name='متن قرارداد'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='f_draft',
            field=models.FileField(blank=True, default=None, null=True, upload_to='', verbose_name='پیش\u200cنویس قرارداد'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='f_etc1',
            field=models.FileField(blank=True, default=None, null=True, upload_to='', verbose_name='سایر 1'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='f_etc2',
            field=models.FileField(blank=True, default=None, null=True, upload_to='', verbose_name='سایر 2'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='f_etc3',
            field=models.FileField(blank=True, default=None, null=True, upload_to='', verbose_name='سایر 3'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='f_exchange_letter',
            field=models.FileField(blank=True, default=None, null=True, upload_to='', verbose_name='نامه مبادله قرارداد'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='f_newspaper',
            field=models.FileField(blank=True, default=None, null=True, upload_to='', verbose_name='روزنامه رسمی'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='f_non_disclosure_agreement',
            field=models.FileField(blank=True, default=None, null=True, upload_to='', verbose_name='توافقنامه عدم افشا'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='f_proposal',
            field=models.FileField(blank=True, default=None, null=True, upload_to='', verbose_name='پروپوزال'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='f_statute',
            field=models.FileField(blank=True, default=None, null=True, upload_to='', verbose_name='اساسنامه'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='f_technical_attachment',
            field=models.FileField(blank=True, default=None, null=True, upload_to='', verbose_name='پیوست فنی'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='f_warranty',
            field=models.FileField(blank=True, default=None, null=True, upload_to='', verbose_name='ضمانتنامه'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='fund_accept',
            field=models.CharField(choices=[('نامشخص', 'نامشخص'), ('تأیید', 'تأیید'), ('عدم تأیید', 'عدم تأیید'), ('عودت جهت اصلاح', 'عودت جهت اصلاح')], default='نامشخص', max_length=14, verbose_name='نظر واحد بودجه'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='head_accept',
            field=models.CharField(choices=[('نامشخص', 'نامشخص'), ('تأیید', 'تأیید'), ('عدم تأیید', 'عدم تأیید'), ('عودت جهت اصلاح', 'عودت جهت اصلاح')], default='نامشخص', max_length=14, verbose_name='نظر رئیس'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='manager_accept',
            field=models.CharField(choices=[('نامشخص', 'نامشخص'), ('تأیید', 'تأیید'), ('عدم تأیید', 'عدم تأیید'), ('عودت جهت اصلاح', 'عودت جهت اصلاح')], default='نامشخص', max_length=14, verbose_name='نظر مدیر واحد'),
        ),
        migrations.AlterField(
            model_name='pay',
            name='clerk_accept',
            field=models.CharField(choices=[('نامشخص', 'نامشخص'), ('تأیید', 'تأیید'), ('عدم تأیید', 'عدم تأیید'), ('عودت جهت اصلاح', 'عودت جهت اصلاح')], default='نامشخص', max_length=14, verbose_name='نظر کارشناس مالی'),
        ),
        migrations.AlterField(
            model_name='pay',
            name='convention_accept',
            field=models.CharField(choices=[('نامشخص', 'نامشخص'), ('تأیید', 'تأیید'), ('عدم تأیید', 'عدم تأیید'), ('عودت جهت اصلاح', 'عودت جهت اصلاح')], default='نامشخص', max_length=14, verbose_name='نظر واحد قراردادها'),
        ),
        migrations.AlterField(
            model_name='pay',
            name='deputy_accept',
            field=models.CharField(choices=[('نامشخص', 'نامشخص'), ('تأیید', 'تأیید'), ('عدم تأیید', 'عدم تأیید'), ('عودت جهت اصلاح', 'عودت جهت اصلاح')], default='نامشخص', max_length=14, verbose_name='نظر معاون توسعه'),
        ),
        migrations.AlterField(
            model_name='pay',
            name='finance_accept',
            field=models.CharField(choices=[('نامشخص', 'نامشخص'), ('تأیید', 'تأیید'), ('عدم تأیید', 'عدم تأیید'), ('عودت جهت اصلاح', 'عودت جهت اصلاح')], default='نامشخص', max_length=14, verbose_name='نظر مدیرکل مالی'),
        ),
        migrations.AlterField(
            model_name='pay',
            name='fund_accept',
            field=models.CharField(choices=[('نامشخص', 'نامشخص'), ('تأیید', 'تأیید'), ('عدم تأیید', 'عدم تأیید'), ('عودت جهت اصلاح', 'عودت جهت اصلاح')], default='نامشخص', max_length=14, verbose_name='نظر واحد بودجه'),
        ),
        migrations.AlterField(
            model_name='pay',
            name='manager_accept',
            field=models.CharField(choices=[('نامشخص', 'نامشخص'), ('تأیید', 'تأیید'), ('عدم تأیید', 'عدم تأیید'), ('عودت جهت اصلاح', 'عودت جهت اصلاح')], default='نامشخص', max_length=14, verbose_name='نظر مدیر واحد'),
        ),
        migrations.AlterField(
            model_name='supplement',
            name='convention_accept',
            field=models.CharField(choices=[('نامشخص', 'نامشخص'), ('تأیید', 'تأیید'), ('عدم تأیید', 'عدم تأیید'), ('عودت جهت اصلاح', 'عودت جهت اصلاح')], default='نامشخص', max_length=14, verbose_name='نظر واحد قراردادها'),
        ),
        migrations.AlterField(
            model_name='supplement',
            name='deputy_accept',
            field=models.CharField(choices=[('نامشخص', 'نامشخص'), ('تأیید', 'تأیید'), ('عدم تأیید', 'عدم تأیید'), ('عودت جهت اصلاح', 'عودت جهت اصلاح')], default='نامشخص', max_length=14, verbose_name='نظر معاون توسعه'),
        ),
        migrations.AlterField(
            model_name='supplement',
            name='manager_accept',
            field=models.CharField(choices=[('نامشخص', 'نامشخص'), ('تأیید', 'تأیید'), ('عدم تأیید', 'عدم تأیید'), ('عودت جهت اصلاح', 'عودت جهت اصلاح')], default='نامشخص', max_length=14, verbose_name='نظر مدیر واحد'),
        ),
    ]
