# Generated by Django 5.0.4 on 2025-10-06 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cn', '0063_remove_contract_accept_note_remove_contract_accepted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contracttask',
            name='answer',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='پاسخ'),
        ),
    ]
