# Generated by Django 5.0.4 on 2025-10-06 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cn', '0064_add_answer_to_contracttask'),
    ]

    operations = [
        migrations.AddField(
            model_name='paytask',
            name='answer',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='پاسخ'),
        ),
    ]
