# Generated by Django 5.0.4 on 2025-10-06 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cn', '0065_add_answer_to_paytask'),
    ]

    operations = [
        migrations.AddField(
            model_name='pay',
            name='locked',
            field=models.BooleanField(default=True, help_text='وقتی درخواست در مراحل بررسی رد شود این قفل باز میشود تا درخواست قابل ویرایش و اصلاح باشد', verbose_name='قفل و ارسال'),
        ),
    ]
