# Generated by Django 5.0.4 on 2025-10-07 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cn', '0067_add_registrar_to_pay'),
    ]

    operations = [
        migrations.AddField(
            model_name='pay',
            name='head_accept',
            field=models.CharField(choices=[('نامشخص', 'نامشخص'), ('تأیید', 'تأیید'), ('عدم تأیید', 'عدم تأیید'), ('عودت جهت اصلاح', 'عودت جهت اصلاح')], default='نامشخص', max_length=14, verbose_name='نظر رئیس مرکز'),
        ),
        migrations.AddField(
            model_name='pay',
            name='need_head',
            field=models.BooleanField(default=False, verbose_name='نیاز به تأیید رئیس مرکز دارد'),
        ),
    ]
