# Generated by Django 5.0.4 on 2025-10-08 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cn', '0068_add_need_head_and_head_accept_to_pay'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='price',
            field=models.BigIntegerField(default=0, verbose_name='مبلغ'),
        ),
    ]
