# Generated by Django 5.0.4 on 2025-10-11 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cn', '0070_remove_contract_accept_note_remove_contract_accepted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paytask',
            name='accept',
        ),
    ]
