# Generated by Django 5.0.4 on 2025-10-14 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cn', '0071_remove_paytask_accept'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='title',
            field=models.CharField(max_length=200, unique=True, verbose_name='عنوان و موضوع قرارداد'),
        ),
    ]
