# Generated by Django 5.0.4 on 2025-11-10 07:13

import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cn', '0072_alter_contract_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='has_value_added',
            field=models.BooleanField(blank=True, null=True, verbose_name='مشمول مالیات بر ارزش افزوده'),
        ),
        migrations.AddField(
            model_name='contract',
            name='warranty_end_date',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ پایان ضمانت'),
        ),
        migrations.AddField(
            model_name='contract',
            name='warranty_start_date',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ آغاز ضمانت'),
        ),
    ]
