# Generated by Django 5.0.4 on 2025-11-10 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cn', '0073_contract_has_value_added_contract_warranty_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pay',
            name='audit',
            field=models.CharField(choices=[('نامشخص', 'نامشخص'), ('تأیید', 'تأیید'), ('عدم تأیید', 'عدم تأیید'), ('عودت جهت اصلاح', 'عودت جهت اصلاح')], default='نامشخص', max_length=14, verbose_name='ممیزی اسناد'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='warranty_type',
            field=models.CharField(blank=True, choices=[('سفته', 'سفته'), ('ضمانتنامه', 'ضمانتنامه'), ('سپرده انجام کار', 'سپرده انجام کار')], max_length=15, null=True, verbose_name='نوع ضمانتنامه'),
        ),
    ]
