# Generated by Django 5.0.4 on 2025-11-19 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cn', '0074_pay_audit_alter_contract_warranty_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='warranty_type',
            field=models.CharField(blank=True, choices=[('سفته', 'سفته'), ('ضمانتنامه بانکی', 'ضمانتنامه بانکی'), ('ضمانتنامه اداری', 'ضمانتنامه اداری'), ('سپرده انجام کار', 'سپرده انجام کار')], max_length=15, null=True, verbose_name='نوع ضمانتنامه'),
        ),
    ]
