# Generated by Django 5.0.4 on 2026-01-12 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cn', '0075_alter_contract_warranty_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='fund_accept',
            field=models.CharField(choices=[('نامشخص', 'نامشخص'), ('تأیید', 'تأیید'), ('عدم تأیید', 'عدم تأیید'), ('عودت جهت اصلاح', 'عودت جهت اصلاح')], default='نامشخص', max_length=14, verbose_name='تأیید دفتر برنامه و بودجه'),
        ),
        migrations.AlterField(
            model_name='pay',
            name='fund_accept',
            field=models.CharField(choices=[('نامشخص', 'نامشخص'), ('تأیید', 'تأیید'), ('عدم تأیید', 'عدم تأیید'), ('عودت جهت اصلاح', 'عودت جهت اصلاح')], default='نامشخص', max_length=14, verbose_name='تأیید دفتر برنامه و بودجه'),
        ),
    ]
