# Generated by Django 5.0.4 on 2024-04-29 03:03

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prj', '0010_alter_phase_cost_alter_phase_hr'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(choices=[(1400, 1400), (1401, 1401), (1402, 1402), (1403, 1403)], verbose_name='سال')),
                ('month', models.PositiveSmallIntegerField(choices=[(1, 'فروردین'), (2, 'اردیبهشت'), (3, 'خرداد'), (4, 'تیر'), (5, 'مرداد'), (6, 'شهریور'), (7, 'مهر'), (8, 'آبان'), (9, 'آذر'), (10, 'دی'), (11, 'بهمن'), (12, 'اسفند')], verbose_name='ماه')),
                ('gross_work', models.DurationField(default=datetime.timedelta(0), help_text='با احتساب مرخصی\u200cها', verbose_name='کارکرد ناخالص')),
                ('work', models.DurationField(default=datetime.timedelta(0), help_text='بدون احتساب مرخصی\u200cها', verbose_name='کارکرد خالص')),
                ('paid_leave', models.DurationField(default=datetime.timedelta(0), verbose_name='مرخصی استحقاقی')),
                ('sick_leave', models.DurationField(default=datetime.timedelta(0), verbose_name='مرخصی استعلاجی')),
                ('sick_leave2', models.DurationField(default=datetime.timedelta(0), verbose_name='مرخصی استعلاجی 2')),
                ('mission', models.DurationField(default=datetime.timedelta(0), verbose_name='مأموریت')),
                ('delay', models.DurationField(default=datetime.timedelta(0), verbose_name='کسر کار')),
                ('absence', models.PositiveSmallIntegerField(default=0, verbose_name='غیبت')),
                ('work_overtime', models.DurationField(default=datetime.timedelta(0), verbose_name='اضافه\u200cکار واقعی')),
                ('overtime1', models.PositiveSmallIntegerField(default=0, help_text='ثبت توسط مدیر اداره', verbose_name='اضافه\u200cکار تشویقی 1')),
                ('overtime2', models.PositiveSmallIntegerField(default=0, help_text='ثبت توسط مدیر واحد', verbose_name='اضافه کار تشویقی 2')),
                ('bonus1', models.PositiveIntegerField(default=0, help_text='ثبت توسط مدیر اداره', verbose_name='کارآیی 1')),
                ('bonus2', models.PositiveIntegerField(default=0, help_text='ثبت توسط مدیر واحد', verbose_name='کارآیی 2')),
                ('attendance_min', models.PositiveSmallIntegerField(default=0, help_text='ویژه مشاوران', verbose_name='حداقل ساعت حضور')),
                ('attendance', models.PositiveSmallIntegerField(default=0, help_text='ویژه مشاوران', verbose_name='جمع ساعات حضور')),
                ('percent', models.PositiveSmallIntegerField(default=0, help_text='ویژه مشاوران', verbose_name='درصد تأیید کارکرد')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'کارکرد',
                'verbose_name_plural': 'کارکرد',
                'ordering': ['id'],
                'unique_together': {('user', 'year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='Timesheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.PositiveSmallIntegerField(default=0, verbose_name='درصد')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prj.project', verbose_name='پروژه')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.work', verbose_name='کارکرد')),
            ],
            options={
                'verbose_name': 'تایم شیت',
                'verbose_name_plural': 'تایم شیت',
                'ordering': ['id'],
                'unique_together': {('work', 'project')},
            },
        ),
    ]
