# Generated by Django 5.0.4 on 2024-04-29 03:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_unit_bonus_quota_unit_overtime_bonus_open_and_more'),
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.post', verbose_name='پست'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='work',
            name='bonus1',
            field=models.PositiveIntegerField(default=0, help_text='ثبت توسط مدیر اداره', verbose_name='کارآیی اولیه'),
        ),
        migrations.AlterField(
            model_name='work',
            name='bonus2',
            field=models.PositiveIntegerField(default=0, help_text='ثبت توسط مدیر واحد', verbose_name='کارآیی'),
        ),
        migrations.AlterField(
            model_name='work',
            name='overtime1',
            field=models.PositiveSmallIntegerField(default=0, help_text='ثبت توسط مدیر اداره', verbose_name='اضافه\u200cکار تشویقی اولیه'),
        ),
        migrations.AlterField(
            model_name='work',
            name='overtime2',
            field=models.PositiveSmallIntegerField(default=0, help_text='ثبت توسط مدیر واحد', verbose_name='اضافه کار تشویقی'),
        ),
    ]
