# Generated by Django 5.0.4 on 2024-04-29 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_work_post_alter_work_bonus1_alter_work_bonus2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='contract',
            field=models.CharField(choices=[('پروژه', 'پروژه'), ('مشاوره', 'مشاوره'), ('همکاری', 'همکاری')], default='پروژه', max_length=10, verbose_name='نوع قرارداد'),
            preserve_default=False,
        ),
    ]
