# Generated by Django 5.0.4 on 2024-04-29 03:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_unit_bonus_quota_unit_overtime_bonus_open_and_more'),
        ('hr', '0003_work_contract'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.post', verbose_name='پست'),
        ),
        migrations.AlterField(
            model_name='work',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
    ]
