# Generated by Django 5.0.4 on 2024-04-29 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_alter_work_post_alter_work_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='sick_leave2',
        ),
        migrations.AddField(
            model_name='work',
            name='telecommuting',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='دورکاری'),
        ),
    ]
