# Generated by Django 5.0.4 on 2024-04-29 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0005_remove_work_sick_leave2_work_telecommuting'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='sick_leave2',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='مرخصی استعلاجی 2'),
        ),
    ]
