# Generated by Django 5.0.4 on 2024-04-29 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_unit_bonus_quota'),
        ('hr', '0006_work_sick_leave2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.post', verbose_name='پست'),
        ),
    ]
