# Generated by Django 5.0.4 on 2024-04-30 02:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0007_alter_work_post'),
        ('prj', '0010_alter_phase_cost_alter_phase_hr'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheet',
            name='note',
            field=models.TextField(blank=True, help_text='برای حالتی که پروژه خالی است', null=True, verbose_name='شرح'),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prj.project', verbose_name='پروژه'),
        ),
    ]
