# Generated by Django 5.0.4 on 2024-04-30 02:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0008_timesheet_note_alter_timesheet_project'),
        ('prj', '0010_alter_phase_cost_alter_phase_hr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='prj.project', verbose_name='پروژه'),
            preserve_default=False,
        ),
    ]
