# Generated by Django 5.0.4 on 2024-04-30 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0009_alter_timesheet_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='work',
            old_name='percent',
            new_name='percent1',
        ),
    ]
