# Generated by Django 5.0.4 on 2024-04-30 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0010_rename_percent_work_percent1'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='percent2',
            field=models.PositiveSmallIntegerField(default=0, help_text='ویژه مشاوران', verbose_name='درصد تأیید کارکرد'),
        ),
    ]
