# Generated by Django 5.0.4 on 2024-05-01 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0011_work_percent2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='bonus2',
        ),
        migrations.RemoveField(
            model_name='work',
            name='overtime2',
        ),
        migrations.RemoveField(
            model_name='work',
            name='percent2',
        ),
        migrations.RemoveField(
            model_name='work',
            name='sick_leave',
        ),
        migrations.AlterField(
            model_name='work',
            name='percent1',
            field=models.PositiveSmallIntegerField(default=0, help_text='ثبت توسط مدیر اداره', verbose_name='درصد تأیید کارکرد مشاور'),
        ),
    ]
