# Generated by Django 5.0.4 on 2024-05-01 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0012_remove_work_bonus2_remove_work_overtime2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='work',
            old_name='bonus1',
            new_name='bonus',
        ),
        migrations.RenameField(
            model_name='work',
            old_name='overtime1',
            new_name='overtime',
        ),
        migrations.RenameField(
            model_name='work',
            old_name='percent1',
            new_name='percent',
        ),
        migrations.RenameField(
            model_name='work',
            old_name='sick_leave2',
            new_name='sick_leave',
        ),
    ]
