# Generated by Django 5.0.4 on 2024-05-01 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0013_rename_bonus1_work_bonus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='bonus',
            field=models.PositiveIntegerField(default=0, verbose_name='کارآیی'),
        ),
        migrations.AlterField(
            model_name='work',
            name='overtime',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='اضافه\u200cکار تشویقی'),
        ),
        migrations.AlterField(
            model_name='work',
            name='percent',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='درصد تأیید کارکرد مشاور'),
        ),
        migrations.AlterField(
            model_name='work',
            name='sick_leave',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='مرخصی استعلاجی'),
        ),
    ]
