# Generated by Django 5.0.4 on 2024-07-17 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0015_inquiry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Inquiry',
        ),
    ]
