# Generated by Django 5.0.4 on 2024-07-17 07:42

import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0016_delete_inquiry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.PositiveBigIntegerField(verbose_name='کد ملی یا شناسه شرکت')),
                ('genre', models.CharField(choices=[('حقوقی', 'حقوقی'), ('حقیقی', 'حقیقی')], max_length=5, verbose_name='شخصیت مجری')),
                ('title', models.CharField(max_length=100, verbose_name='نام فرد یا شرکت')),
                ('subject', models.CharField(max_length=100, verbose_name='عنوان پست یا موضوع قرارداد')),
                ('file', models.FileField(upload_to='', verbose_name='فرم')),
                ('register_date', django_jalali.db.models.jDateField(auto_now_add=True, verbose_name='تاریخ درخواست')),
                ('result', models.BooleanField(blank=True, null=True, verbose_name='نتیجه استعلام')),
                ('result_date', django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ نتیجه')),
            ],
            options={
                'verbose_name': 'استعلام',
                'verbose_name_plural': 'استعلام',
                'ordering': ['register_date'],
            },
        ),
    ]
