# Generated by Django 5.0.4 on 2024-07-17 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0017_inquiry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inquiry',
            options={'ordering': ['result_date', 'register_date'], 'verbose_name': 'استعلام', 'verbose_name_plural': 'استعلام'},
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='no',
            field=models.CharField(max_length=20, verbose_name='کد ملی یا شناسه شرکت'),
        ),
    ]
