# Generated by Django 5.0.4 on 2024-07-17 11:57

import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0018_alter_inquiry_options_alter_inquiry_no'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inquiry',
            name='file',
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='subject',
        ),
        migrations.AddField(
            model_name='inquiry',
            name='lock_date',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ ثبت'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='locked',
            field=models.BooleanField(default=False, verbose_name='ثبت شده'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='post',
            field=models.CharField(blank=True, help_text='برای شخصیت حقیقی و نوع جذب', max_length=100, null=True, verbose_name='عنوان پست'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='result_note',
            field=models.TextField(blank=True, null=True, verbose_name='شرح استعلام'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='send_date',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ ارسال'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='send_note',
            field=models.TextField(blank=True, null=True, verbose_name='شرح ارسال'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='sent',
            field=models.BooleanField(blank=True, null=True, verbose_name='ارسال شده'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='type',
            field=models.CharField(choices=[('جذب', 'جذب'), ('قرارداد', 'قرارداد')], default='قرارداد', max_length=10, verbose_name='نوع'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inquiry',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='InquiryAppendix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان')),
                ('file', models.FileField(upload_to='', verbose_name='فایل')),
                ('create_time', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('inquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appendices', to='hr.inquiry', verbose_name='استعلام')),
            ],
            options={
                'verbose_name': 'پیوست',
                'verbose_name_plural': 'پیوست\u200cهای استعلام',
                'ordering': ['id'],
            },
        ),
    ]
