# Generated by Django 5.0.4 on 2024-07-17 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_post_can_see_invoice'),
        ('hr', '0019_remove_inquiry_file_remove_inquiry_subject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='unit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.unit', verbose_name='واحد سازمانی'),
            preserve_default=False,
        ),
    ]
