# Generated by Django 5.0.4 on 2024-07-22 03:30

import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0020_inquiry_unit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inquiry',
            name='lock_date',
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='locked',
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='result_note',
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='send_date',
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='send_note',
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='sent',
        ),
        migrations.AddField(
            model_name='inquiry',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='شرح'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='reply',
            field=models.TextField(blank=True, null=True, verbose_name='شرح واحد حراست'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='status',
            field=models.CharField(choices=[('پیش\u200cنویس', 'پیش\u200cنویس'), ('ارسال درخواست', 'ارسال درخواست'), ('عودت جهت اصلاح', 'عودت جهت اصلاح'), ('استعلام', 'استعلام'), ('خاتمه', 'خاتمه')], default='پیش\u200cنویس', max_length=15, verbose_name='وضعیت'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='InquiryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('پیش\u200cنویس', 'پیش\u200cنویس'), ('ارسال درخواست', 'ارسال درخواست'), ('عودت جهت اصلاح', 'عودت جهت اصلاح'), ('استعلام', 'استعلام'), ('خاتمه', 'خاتمه')], max_length=15, verbose_name='وضعیت')),
                ('time', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='زمان')),
                ('inquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.inquiry', verbose_name='استعلام')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': '',
                'ordering': ['-id'],
            },
        ),
    ]
