# Generated by Django 5.0.4 on 2024-07-22 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0021_remove_inquiry_lock_date_remove_inquiry_locked_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inquiry',
            name='unit',
        ),
    ]
