# Generated by Django 5.0.4 on 2024-07-23 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0022_remove_inquiry_unit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inquiry',
            options={'ordering': ['-register_date'], 'verbose_name': 'استعلام', 'verbose_name_plural': 'استعلام'},
        ),
        migrations.AddField(
            model_name='inquirylog',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='شرح'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='status',
            field=models.CharField(choices=[('پیش\u200cنویس', 'پیش\u200cنویس'), ('ارسال درخواست', 'ارسال درخواست'), ('عودت جهت اصلاح', 'عودت جهت اصلاح'), ('استعلام', 'استعلام'), ('خاتمه', 'خاتمه')], default='پیش\u200cنویس', max_length=15, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='inquirylog',
            name='inquiry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='hr.inquiry', verbose_name='استعلام'),
        ),
    ]
