# Generated by Django 5.0.4 on 2024-07-24 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0023_alter_inquiry_options_inquirylog_note_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inquiry',
            options={'ordering': ['-id'], 'verbose_name': 'استعلام', 'verbose_name_plural': 'استعلام'},
        ),
        migrations.AlterModelOptions(
            name='inquirylog',
            options={'ordering': ['id'], 'verbose_name': '', 'verbose_name_plural': ''},
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='status',
            field=models.CharField(choices=[('پیش\u200cنویس', 'پیش\u200cنویس'), ('بررسی درخواست', 'بررسی درخواست'), ('اصلاح درخواست', 'اصلاح درخواست'), ('استعلام', 'استعلام'), ('خاتمه', 'خاتمه')], default='پیش\u200cنویس', max_length=15, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='inquirylog',
            name='status',
            field=models.CharField(choices=[('پیش\u200cنویس', 'پیش\u200cنویس'), ('بررسی درخواست', 'بررسی درخواست'), ('اصلاح درخواست', 'اصلاح درخواست'), ('استعلام', 'استعلام'), ('خاتمه', 'خاتمه')], max_length=15, verbose_name='وضعیت'),
        ),
    ]
