# Generated by Django 5.0.4 on 2024-08-06 04:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_proclamation_poster_alter_proclamation_body'),
        ('hr', '0024_alter_inquiry_options_alter_inquirylog_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.post', verbose_name='پست'),
            preserve_default=False,
        ),
    ]
