# Generated by Django 5.0.4 on 2024-08-11 04:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_proclamation_poster_alter_proclamation_body'),
        ('hr', '0025_alter_work_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='unit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.unit', verbose_name='واحد سازمانی'),
            preserve_default=False,
        ),
    ]
