# Generated by Django 5.0.4 on 2024-09-28 09:27

import django.utils.timezone
import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0026_inquiry_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inquirylog',
            name='inquiry',
        ),
        migrations.RemoveField(
            model_name='inquirylog',
            name='user',
        ),
        migrations.RenameField(
            model_name='inquiry',
            old_name='result',
            new_name='response',
        ),
        migrations.RenameField(
            model_name='inquiry',
            old_name='result_date',
            new_name='response_date',
        ),
        migrations.RenameField(
            model_name='inquiry',
            old_name='reply',
            new_name='response_note',
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='status',
        ),
        migrations.AddField(
            model_name='inquiry',
            name='present_date',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ تکمیل پرونده'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='request_date',
            field=django_jalali.db.models.jDateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='تاریخ درخواست'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='register_date',
            field=django_jalali.db.models.jDateField(auto_now_add=True, verbose_name='تاریخ ثبت'),
        ),
        migrations.DeleteModel(
            name='InquiryAppendix',
        ),
        migrations.DeleteModel(
            name='InquiryLog',
        ),
    ]
