# Generated by Django 5.0.4 on 2024-09-29 10:02

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0027_remove_inquirylog_inquiry_remove_inquirylog_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='request_date',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ درخواست'),
        ),
    ]
