# Generated by Django 5.0.4 on 2024-10-28 04:55

import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0028_alter_inquiry_request_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='work_days',
            field=models.PositiveSmallIntegerField(default=30, verbose_name='تعداد روز کارکرد'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_soldier', models.BooleanField(default=False, verbose_name='سرباز امریه')),
                ('is_permanent', models.BooleanField(default=False, verbose_name='کارمند رسمی')),
                ('contract_type', models.CharField(blank=True, choices=[('پروژه', 'پروژه'), ('مشاوره', 'مشاوره'), ('همکاری', 'همکاری')], max_length=10, null=True, verbose_name='نوع قرارداد')),
                ('attendance_min', models.PositiveSmallIntegerField(default=0, help_text='ویژه مشاوران', verbose_name='جمع ساعات حضور')),
                ('subsidy', models.BooleanField(default=True, verbose_name='سوبسید غذا')),
                ('sf1', models.PositiveIntegerField(default=0, verbose_name='حقوق و رتبه پایه')),
                ('sf5', models.PositiveIntegerField(default=0, verbose_name='فوق\u200cالعاده شغل')),
                ('sf6', models.PositiveIntegerField(default=0, verbose_name='فوق\u200cالعاده جذب')),
                ('sf7', models.PositiveIntegerField(default=0, verbose_name='فوق\u200cالعاده ویژه')),
                ('sf8', models.PositiveIntegerField(default=0, verbose_name='حق عائله\u200cمندی')),
                ('sf11', models.PositiveIntegerField(default=0, verbose_name='حق اولاد')),
                ('sf14', models.PositiveIntegerField(default=0, verbose_name='فوق\u200cالعاده مخصوص')),
                ('sf20', models.PositiveIntegerField(default=0, verbose_name='فوق\u200cالعاده مدیریت')),
                ('sf27', models.PositiveIntegerField(default=0, verbose_name='فوق\u200cالعاده مسکن')),
                ('sf38', models.PositiveIntegerField(default=0, verbose_name='فوق العاده ایثارگری ماده 51')),
                ('sf42', models.PositiveIntegerField(default=0, verbose_name='تفاوت بند(ی) تبصره 12-سال 1398')),
                ('sf45', models.PositiveIntegerField(default=0, verbose_name='تفاوت جزء(1)بند الف ت12-سال 1397')),
                ('sf49', models.PositiveIntegerField(default=0, verbose_name='تفاوت تطبیق موضوع ب الف ت12-سال 1399')),
                ('sf51', models.PositiveIntegerField(default=0, verbose_name='تفاوت تطبیق جز(3) بند الف ت 12-سال 1400')),
                ('sf52', models.PositiveIntegerField(default=0, verbose_name='کاهش ناشی از اجرای جز(1) بند الف تبصره12')),
                ('sf64', models.PositiveIntegerField(default=0, verbose_name='تفاوت تطبیق جز (1) بند الف ت 12-سال 1401')),
                ('sf65', models.PositiveIntegerField(default=0, verbose_name='همترازی ایثارگری')),
                ('sf68', models.PositiveIntegerField(default=0, verbose_name='ترمیم حقوق')),
                ('sf69', models.PositiveIntegerField(default=0, verbose_name='تفاوت تطبیق موضوع جز (1) ب الف ت 12 ق ب 1402')),
                ('sf70', models.PositiveIntegerField(default=0, verbose_name='حق الزحمه مشاوره')),
                ('sf_commuting', models.PositiveIntegerField(default=0, verbose_name='بن غیرنقدی - ایاب و ذهاب')),
                ('sf_food', models.PositiveIntegerField(default=0, verbose_name='حق غذا')),
                ('sf_mobile', models.PositiveIntegerField(default=0, verbose_name='کمک هزینه تلفن همراه')),
                ('sf_house', models.PositiveIntegerField(default=0, verbose_name='حق مسکن')),
                ('create_time', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('update_time', django_jalali.db.models.jDateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پروفایل',
                'verbose_name_plural': 'پروفایل ها',
                'db_table': 'profile',
                'ordering': ['id'],
            },
        ),
    ]
