# Generated by Django 5.0.4 on 2024-10-28 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0029_work_work_days_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='subsidy',
            new_name='has_sf_food',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='contract_type',
        ),
        migrations.AddField(
            model_name='profile',
            name='has_sf_mobile',
            field=models.BooleanField(default=False, verbose_name='سوبسید تلفن همراه'),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_advisor',
            field=models.BooleanField(default=False, verbose_name='مشاور'),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_agent',
            field=models.BooleanField(default=False, verbose_name='مأمور'),
        ),
    ]
