# Generated by Django 5.0.4 on 2024-10-28 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0030_rename_subsidy_profile_has_sf_food_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='attendance',
        ),
        migrations.RemoveField(
            model_name='work',
            name='attendance_min',
        ),
        migrations.RemoveField(
            model_name='work',
            name='contract',
        ),
    ]
