# Generated by Django 5.0.4 on 2024-10-28 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0033_alter_profile_options_alter_work_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='post',
        ),
    ]
