# Generated by Django 5.0.4 on 2024-10-29 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0034_remove_work_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='has_work',
            field=models.BooleanField(default=True, verbose_name='ثبت کارآیی در پرتال'),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_sacrificer',
            field=models.BooleanField(default=False, verbose_name='ایثارگران'),
        ),
    ]
