# Generated by Django 5.0.4 on 2024-10-29 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0035_profile_has_work_profile_is_sacrificer'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='sf_management',
            field=models.IntegerField(default=0, verbose_name='حق مدیریت (جبران خدمت)'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sf27',
            field=models.IntegerField(default=0, verbose_name='تفاوت تطبیق'),
        ),
    ]
