# Generated by Django 5.0.4 on 2024-10-30 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0036_profile_sf_management_alter_profile_sf27'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='sf1',
            field=models.IntegerField(default=0, help_text='از راهکاران به\u200cروز می\u200cشود', verbose_name='حقوق و رتبه پایه'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sf11',
            field=models.IntegerField(default=0, help_text='از راهکاران به\u200cروز می\u200cشود', verbose_name='حق اولاد'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sf14',
            field=models.IntegerField(default=0, help_text='از راهکاران به\u200cروز می\u200cشود', verbose_name='فوق\u200cالعاده مخصوص'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sf20',
            field=models.IntegerField(default=0, help_text='از راهکاران به\u200cروز می\u200cشود', verbose_name='فوق\u200cالعاده مدیریت'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sf27',
            field=models.IntegerField(default=0, help_text='از راهکاران به\u200cروز می\u200cشود', verbose_name='تفاوت تطبیق'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sf38',
            field=models.IntegerField(default=0, help_text='از راهکاران به\u200cروز می\u200cشود', verbose_name='فوق العاده ایثارگری ماده 51'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sf42',
            field=models.IntegerField(default=0, help_text='از راهکاران به\u200cروز می\u200cشود', verbose_name='تفاوت بند(ی) تبصره 12-سال 1398'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sf45',
            field=models.IntegerField(default=0, help_text='از راهکاران به\u200cروز می\u200cشود', verbose_name='تفاوت جزء(1)بند الف ت12-سال 1397'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sf49',
            field=models.IntegerField(default=0, help_text='از راهکاران به\u200cروز می\u200cشود', verbose_name='تفاوت تطبیق موضوع ب الف ت12-سال 1399'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sf5',
            field=models.IntegerField(default=0, help_text='از راهکاران به\u200cروز می\u200cشود', verbose_name='فوق\u200cالعاده شغل'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sf51',
            field=models.IntegerField(default=0, help_text='از راهکاران به\u200cروز می\u200cشود', verbose_name='تفاوت تطبیق جز(3) بند الف ت 12-سال 1400'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sf52',
            field=models.IntegerField(default=0, help_text='از راهکاران به\u200cروز می\u200cشود', verbose_name='کاهش ناشی از اجرای جز(1) بند الف تبصره12'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sf6',
            field=models.IntegerField(default=0, help_text='از راهکاران به\u200cروز می\u200cشود', verbose_name='فوق\u200cالعاده جذب'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sf64',
            field=models.IntegerField(default=0, help_text='از راهکاران به\u200cروز می\u200cشود', verbose_name='تفاوت تطبیق جز (1) بند الف ت 12-سال 1401'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sf65',
            field=models.IntegerField(default=0, help_text='از راهکاران به\u200cروز می\u200cشود', verbose_name='همترازی ایثارگری'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sf68',
            field=models.IntegerField(default=0, help_text='از راهکاران به\u200cروز می\u200cشود', verbose_name='ترمیم حقوق'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sf69',
            field=models.IntegerField(default=0, help_text='از راهکاران به\u200cروز می\u200cشود', verbose_name='تفاوت تطبیق موضوع جز (1) ب الف ت 12 ق ب 1402'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sf7',
            field=models.IntegerField(default=0, help_text='از راهکاران به\u200cروز می\u200cشود', verbose_name='فوق\u200cالعاده ویژه'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sf70',
            field=models.IntegerField(default=0, help_text='از راهکاران به\u200cروز می\u200cشود', verbose_name='حق الزحمه مشاوره'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sf8',
            field=models.IntegerField(default=0, help_text='از راهکاران به\u200cروز می\u200cشود', verbose_name='حق عائله\u200cمندی'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sf_commuting',
            field=models.IntegerField(default=0, help_text='از راهکاران به\u200cروز می\u200cشود', verbose_name='بن غیرنقدی - ایاب و ذهاب'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sf_food',
            field=models.IntegerField(default=0, help_text='از راهکاران به\u200cروز می\u200cشود', verbose_name='حق غذا'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sf_house',
            field=models.IntegerField(default=0, help_text='از راهکاران به\u200cروز می\u200cشود', verbose_name='حق مسکن'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sf_mobile',
            field=models.IntegerField(default=0, help_text='از راهکاران به\u200cروز می\u200cشود', verbose_name='کمک هزینه تلفن همراه'),
        ),
    ]
