# Generated by Django 5.0.4 on 2024-11-02 02:58

import django.db.models.deletion
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0037_alter_profile_sf1_alter_profile_sf11_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='type',
            field=models.CharField(choices=[('جذب', 'جذب'), ('قرارداد', 'قرارداد'), ('خرید', 'خرید'), ('سایر', 'سایر')], max_length=10, verbose_name='نوع'),
        ),
        migrations.CreateModel(
            name='InquiryAppendix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان')),
                ('file', models.FileField(upload_to='', verbose_name='فایل')),
                ('create_time', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('inquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appendices', to='hr.inquiry', verbose_name='استعلام')),
            ],
            options={
                'verbose_name': 'پیوست',
                'verbose_name_plural': 'پیوست\u200cهای استعلام',
                'ordering': ['id'],
            },
        ),
    ]
