# Generated by Django 5.0.4 on 2024-11-11 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0038_alter_inquiry_type_inquiryappendix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='response',
            field=models.CharField(blank=True, choices=[('تأیید', 'تأیید'), ('عدم تأیید', 'عدم تأیید'), ('نامشخص', 'نامشخص')], max_length=10, null=True, verbose_name='نتیجه استعلام'),
        ),
    ]
