# Generated by Django 5.0.4 on 2024-11-13 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0039_alter_inquiry_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='amenity_percent',
            field=models.PositiveSmallIntegerField(default=100, verbose_name='درصد رفاهیات'),
        ),
        migrations.AddField(
            model_name='work',
            name='meed',
            field=models.PositiveIntegerField(default=0, verbose_name='پاداش'),
        ),
        migrations.AddField(
            model_name='work',
            name='meed_note',
            field=models.TextField(blank=True, null=True, verbose_name='علت پاداش'),
        ),
    ]
