# Generated by Django 5.0.4 on 2024-11-17 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0040_work_amenity_percent_work_meed_work_meed_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_corporate',
            field=models.BooleanField(default=False, verbose_name='نیروی شرکتی'),
        ),
    ]
