# Generated by Django 5.0.4 on 2024-12-10 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0041_profile_is_corporate'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='table_row_count',
            field=models.PositiveSmallIntegerField(default=10, editable=False, verbose_name='تعداد ردیف جدول'),
        ),
    ]
