# Generated by Django 5.0.4 on 2024-12-10 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0042_profile_table_row_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='table_row_count',
            new_name='page_size',
        ),
    ]
