# Generated by Django 5.0.4 on 2025-02-11 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0043_rename_table_row_count_profile_page_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inquiryappendix',
            name='inquiry',
        ),
        migrations.DeleteModel(
            name='Inquiry',
        ),
        migrations.DeleteModel(
            name='InquiryAppendix',
        ),
    ]
