# Generated by Django 5.0.4 on 2025-02-11 09:31

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0044_remove_inquiryappendix_inquiry_delete_inquiry_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=200, verbose_name='پرسش')),
                ('levels', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('رئیس', 'رئیس'), ('معاون و مدیرکل مستقل', 'معاون و مدیرکل مستقل'), ('مدیرکل تابعه', 'مدیرکل تابعه'), ('معاون مدیرکل', 'معاون مدیرکل'), ('مدیر', 'مدیر'), ('مشاور', 'مشاور'), ('کارشناس', 'کارشناس'), ('مسئول دفتر', 'مسئول دفتر'), ('کاردان', 'کاردان'), ('تأسیسات', 'تأسیسات'), ('خدمات', 'خدمات'), ('راننده', 'راننده'), ('حفاظت فیزیکی', 'حفاظت فیزیکی')], max_length=20), blank=True, size=None, verbose_name='رده\u200cهای سازمانی')),
            ],
            options={
                'verbose_name': 'پرسش',
                'verbose_name_plural': 'پرسش',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strength', models.TextField(verbose_name='نقاط قوت')),
                ('weakness', models.TextField(verbose_name='نکات قابل بهبود')),
                ('who', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_who_set', to=settings.AUTH_USER_MODEL, verbose_name='ارزیابی کننده')),
                ('whom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_whom_set', to=settings.AUTH_USER_MODEL, verbose_name='ارزیابی شونده')),
            ],
            options={
                'verbose_name': 'ارزیابی',
                'verbose_name_plural': 'ارزیابی',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.PositiveSmallIntegerField(verbose_name='پاسخ')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.assessment', verbose_name='ارزیابی')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.question', verbose_name='پرسش')),
            ],
            options={
                'verbose_name': 'پاسخ',
                'verbose_name_plural': 'پاسخ',
                'ordering': ['id'],
            },
        ),
    ]
