# Generated by Django 5.0.4 on 2025-02-11 09:54

import django.utils.timezone
import django_jalali.db.models
import hr.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0045_question_assessment_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='create_time',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assessment',
            name='update_time',
            field=django_jalali.db.models.jDateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='levels',
            field=hr.models.ModifiedArrayField(base_field=models.CharField(choices=[('رئیس', 'رئیس'), ('معاون و مدیرکل مستقل', 'معاون و مدیرکل مستقل'), ('مدیرکل تابعه', 'مدیرکل تابعه'), ('معاون مدیرکل', 'معاون مدیرکل'), ('مدیر', 'مدیر'), ('مشاور', 'مشاور'), ('کارشناس', 'کارشناس'), ('مسئول دفتر', 'مسئول دفتر'), ('کاردان', 'کاردان'), ('تأسیسات', 'تأسیسات'), ('خدمات', 'خدمات'), ('راننده', 'راننده'), ('حفاظت فیزیکی', 'حفاظت فیزیکی')], max_length=20), blank=True, size=None, verbose_name='رده\u200cهای سازمانی'),
        ),
    ]
