# Generated by Django 5.0.4 on 2025-02-11 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0046_assessment_create_time_assessment_update_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='strength',
            field=models.TextField(blank=True, null=True, verbose_name='نقاط قوت'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='weakness',
            field=models.TextField(blank=True, null=True, verbose_name='نکات قابل بهبود'),
        ),
    ]
