# Generated by Django 5.0.4 on 2025-02-11 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0047_alter_assessment_strength_alter_assessment_weakness'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='done',
            field=models.BooleanField(default=False, verbose_name='ارزیابی ثبت شد'),
        ),
    ]
