# Generated by Django 5.0.4 on 2025-02-15 05:38

import hr.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0048_assessment_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='responders',
            field=hr.models.ModifiedArrayField(base_field=models.CharField(choices=[('مافوق', 'مافوق'), ('همتراز', 'همتراز'), ('تحت امر', 'تحت امر'), ('خودارزیابی', 'خودارزیابی')], max_length=10), blank=True, default=list, size=None, verbose_name='پاسخگو'),
        ),
        migrations.AlterField(
            model_name='question',
            name='levels',
            field=hr.models.ModifiedArrayField(base_field=models.CharField(choices=[('رئیس', 'رئیس'), ('معاون و مدیرکل مستقل', 'معاون و مدیرکل مستقل'), ('مدیرکل تابعه', 'مدیرکل تابعه'), ('معاون مدیرکل', 'معاون مدیرکل'), ('مدیر', 'مدیر'), ('مشاور', 'مشاور'), ('کارشناس', 'کارشناس'), ('مسئول دفتر', 'مسئول دفتر'), ('کاردان', 'کاردان'), ('تأسیسات', 'تأسیسات'), ('خدمات', 'خدمات'), ('راننده', 'راننده'), ('حفاظت فیزیکی', 'حفاظت فیزیکی')], max_length=20), blank=True, default=list, size=None, verbose_name='رده\u200cهای سازمانی'),
        ),
    ]
