# Generated by Django 5.0.4 on 2025-02-15 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0049_question_responders_alter_question_levels'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='bio',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='معرفی در یک جمله'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='educations',
            field=models.TextField(blank=True, help_text='فقط در خودارزیابی', null=True, verbose_name='آموزش\u200cهای مورد نیاز'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='note',
            field=models.TextField(blank=True, help_text='فقط در خودارزیابی', null=True, verbose_name='هر چه می\u200cخواهد دل تنگت'),
        ),
    ]
