# Generated by Django 5.0.4 on 2025-02-16 04:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0050_assessment_bio_assessment_educations_assessment_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='hr.assessment', verbose_name='ارزیابی'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='hr.question', verbose_name='پرسش'),
        ),
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together={('assessment', 'question')},
        ),
    ]
