# Generated by Django 5.0.4 on 2025-05-04 08:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0051_alter_answer_assessment_alter_answer_question_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(verbose_name='سال')),
                ('month', models.PositiveSmallIntegerField(verbose_name='ماه')),
                ('insurance', models.PositiveIntegerField(verbose_name='بیمه تکمیلی')),
                ('loan', models.PositiveIntegerField(verbose_name='اقساط وام')),
                ('fund', models.PositiveIntegerField(verbose_name='صندوق کارکنان')),
                ('other', models.PositiveIntegerField(verbose_name='سایر')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'کسورات',
                'verbose_name_plural': 'کسورات',
                'ordering': ['id'],
            },
        ),
    ]
