# Generated by Django 5.0.4 on 2025-05-25 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0052_deduction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='year',
            field=models.PositiveSmallIntegerField(choices=[(1400, 1400), (1401, 1401), (1402, 1402), (1403, 1403), (1404, 1404)], verbose_name='سال'),
        ),
    ]
