# Generated by Django 5.0.4 on 2025-08-31 11:34

import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0053_alter_work_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='sms',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='کد احراز هویت'),
        ),
        migrations.AddField(
            model_name='profile',
            name='sms_sent_time',
            field=django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='زمان ارسال احراز هویت'),
        ),
    ]
