# Generated by Django 5.0.4 on 2025-09-03 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0054_profile_sms_profile_sms_sent_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='year',
            field=models.PositiveSmallIntegerField(choices=[(1403, 1403), (1404, 1404)], default=1403, verbose_name='سال'),
            preserve_default=False,
        ),
    ]
