# Generated by Django 5.0.4 on 2025-09-03 10:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0055_assessment_year'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='assessment',
            unique_together={('year', 'who', 'whom')},
        ),
    ]
