# Generated by Django 5.0.4 on 2025-09-06 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0056_alter_assessment_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='choice_count',
            field=models.PositiveSmallIntegerField(default=6, verbose_name='تعداد گزینه پاسخ'),
        ),
        migrations.AddField(
            model_name='question',
            name='respondent',
            field=models.CharField(blank=True, choices=[('مدیر واحد', 'مدیر واحد'), ('سرپرست مستقیم', 'سرپرست مستقیم'), ('خودارزیابی', 'خودارزیابی'), ('همکار', 'همکار')], max_length=15, null=True, verbose_name='پاسخگو'),
        ),
        migrations.AddField(
            model_name='question',
            name='year',
            field=models.PositiveSmallIntegerField(choices=[(1403, 1403), (1404, 1404)], default=1403, verbose_name='سال'),
            preserve_default=False,
        ),
    ]
