# Generated by Django 5.0.4 on 2025-09-21 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0057_question_choice_count_question_respondent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ad',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Active Directory Username'),
        ),
        migrations.AlterField(
            model_name='question',
            name='respondent',
            field=models.CharField(blank=True, choices=[('مدیر واحد', 'مدیر واحد'), ('سرپرست مستقیم', 'سرپرست مستقیم'), ('نیروی تحت امر', 'نیروی تحت امر'), ('خودارزیابی', 'خودارزیابی'), ('همکار', 'همکار')], max_length=15, null=True, verbose_name='پاسخگو'),
        ),
    ]
