# Generated by Django 5.0.4 on 2025-11-15 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0058_profile_ad_alter_question_respondent'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='performance',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3)], default=2, verbose_name='عملکرد'),
        ),
        migrations.AddField(
            model_name='work',
            name='potential',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3)], default=2, verbose_name='قابلیت ارتقا'),
        ),
        migrations.AddField(
            model_name='work',
            name='rank',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='رتبه عملکردی'),
        ),
    ]
