# Generated by Django 5.0.4 on 2025-11-23 06:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0059_work_performance_work_potential_work_rank'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='performance',
        ),
        migrations.RemoveField(
            model_name='work',
            name='potential',
        ),
        migrations.RemoveField(
            model_name='work',
            name='rank',
        ),
        migrations.CreateModel(
            name='EvaluationGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان')),
                ('members', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='ارزیابی شوندگان')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluations', to=settings.AUTH_USER_MODEL, verbose_name='ارزیابی کننده')),
            ],
            options={
                'verbose_name': 'گروه ارزیابی',
                'verbose_name_plural': 'گروه ارزیابی',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(choices=[(1400, 1400), (1401, 1401), (1402, 1402), (1403, 1403), (1404, 1404)], verbose_name='سال')),
                ('month', models.PositiveSmallIntegerField(choices=[(1, 'فروردین'), (2, 'اردیبهشت'), (3, 'خرداد'), (4, 'تیر'), (5, 'مرداد'), (6, 'شهریور'), (7, 'مهر'), (8, 'آبان'), (9, 'آذر'), (10, 'دی'), (11, 'بهمن'), (12, 'اسفند')], verbose_name='ماه')),
                ('rank', models.PositiveSmallIntegerField(default=0, verbose_name='رتبه عملکردی')),
                ('performance', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=2, verbose_name='عملکرد')),
                ('potential', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3)], default=2, verbose_name='قابلیت ارتقا')),
                ('note', models.CharField(blank=True, max_length=200, null=True, verbose_name='شرح')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ارزیابی شونده')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.evaluationgroup', verbose_name='گروه ارزیابی')),
            ],
            options={
                'verbose_name': 'ارزیابی ماهانه',
                'verbose_name_plural': 'ارزیابی ماهانه',
                'ordering': ['id'],
                'unique_together': {('year', 'month', 'user', 'group')},
            },
        ),
    ]
