# Generated by Django 5.0.4 on 2025-11-23 07:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0061_alter_evaluation_unique_together_evaluation_is_done_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveSmallIntegerField(default=0, verbose_name='رتبه عملکردی')),
                ('performance', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=2, verbose_name='عملکرد')),
                ('potential', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3)], default=2, verbose_name='قابلیت ارتقا')),
                ('note', models.CharField(blank=True, max_length=200, null=True, verbose_name='شرح')),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.evaluation', verbose_name='ارزیابی ماهانه')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ارزیابی شونده')),
            ],
            options={
                'verbose_name': 'ارزیابی',
                'verbose_name_plural': 'ارزیابی',
                'ordering': ['id'],
                'unique_together': {('evaluation', 'user')},
            },
        ),
    ]
