# Generated by Django 5.0.4 on 2025-11-23 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0062_evaluationanswer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['id'], 'verbose_name': 'پاسخ', 'verbose_name_plural': 'ارزیابی 360 درجه - پاسخ'},
        ),
        migrations.AlterModelOptions(
            name='assessment',
            options={'ordering': ['id'], 'verbose_name': 'ارزیابی', 'verbose_name_plural': 'ارزیابی 360 درجه'},
        ),
        migrations.AlterModelOptions(
            name='evaluationgroup',
            options={'ordering': ['id'], 'verbose_name': 'گروه ارزیابی', 'verbose_name_plural': 'ارزیابی ماهانه - گروه ارزیابی'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['id'], 'verbose_name': 'پرسش', 'verbose_name_plural': 'ارزیابی 360 درجه - پرسش'},
        ),
        migrations.AlterField(
            model_name='evaluationanswer',
            name='evaluation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='hr.evaluation', verbose_name='ارزیابی ماهانه'),
        ),
        migrations.AlterField(
            model_name='evaluationanswer',
            name='performance',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name='عملکرد'),
        ),
        migrations.AlterField(
            model_name='evaluationanswer',
            name='potential',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3)], null=True, verbose_name='قابلیت ارتقا'),
        ),
        migrations.AlterField(
            model_name='evaluationanswer',
            name='rank',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='رتبه عملکردی'),
        ),
    ]
