# Generated by Django 5.0.4 on 2025-11-23 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0063_alter_answer_options_alter_assessment_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evaluationanswer',
            options={'ordering': ['evaluation', 'rank'], 'verbose_name': 'ارزیابی', 'verbose_name_plural': 'ارزیابی'},
        ),
        migrations.AlterField(
            model_name='evaluationanswer',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='شرح'),
        ),
    ]
