# Generated by Django 5.0.4 on 2025-11-26 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0064_alter_evaluationanswer_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationgroup',
            name='importance',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=3, verbose_name='ضریب اهمیت'),
        ),
    ]
