# Generated by Django 5.0.4 on 2025-11-29 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0065_evaluationgroup_importance'),
        ('prj', '0031_alter_project_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationAnswerTimesheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.PositiveSmallIntegerField(default=0, verbose_name='درصد')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.evaluationanswer', verbose_name='ارزیابی')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prj.project', verbose_name='پروژه')),
            ],
        ),
    ]
