# Generated by Django 5.0.4 on 2025-12-03 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0066_evaluationanswertimesheet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluationanswertimesheet',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timesheets', to='hr.evaluationanswer', verbose_name='ارزیابی'),
        ),
    ]
