# Generated by Django 5.0.4 on 2026-01-31 11:35

import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0067_alter_evaluationanswertimesheet_answer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeductionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='کد')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
            ],
            options={
                'verbose_name': 'نوع کسور',
                'verbose_name_plural': 'انواع کسورات',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='DeductionWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(verbose_name='سال')),
                ('month', models.PositiveSmallIntegerField(verbose_name='ماه')),
                ('value', models.PositiveIntegerField(default=0, verbose_name='مقدار (عددی)')),
                ('create_time', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('update_time', django_jalali.db.models.jDateTimeField(auto_now=True)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hr.deductiontype', verbose_name='نوع کسور')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'کسورات',
                'verbose_name_plural': 'کسورات',
                'ordering': ['id'],
                'unique_together': {('user', 'year', 'month', 'type')},
            },
        ),
    ]
