# Generated by Django 5.0.4 on 2026-02-10 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0068_deductiontype_deductionwork'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='salary',
            field=models.PositiveIntegerField(default=0, verbose_name='خالص حقوق'),
        ),
    ]
