# Generated by Django 5.0.4 on 2024-11-17 09:01

import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='room_logo', verbose_name='لوگو')),
                ('type', models.CharField(choices=[('chat', 'chat'), ('group', 'group'), ('channel', 'channel')], max_length=7, verbose_name='نوع')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='معرفی')),
                ('create_time', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'اتاق گفتگو',
                'verbose_name_plural': 'اتاق گفتگو',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_owner', models.BooleanField(default=False, verbose_name='مالک گروه است')),
                ('is_manager', models.BooleanField(default=False, verbose_name='مدیر گروه است')),
                ('pin', models.BooleanField(default=False, verbose_name='سنجاق شده')),
                ('create_time', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('my_last_seen_time', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='زمان آخرین مشاهده من')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='chat.room', verbose_name='اتاق گفتگو')),
            ],
            options={
                'verbose_name': 'اتاق گفتگو - اعضا',
                'verbose_name_plural': 'اتاق گفتگو - اعضا',
                'ordering': ['-pin', '-is_owner', '-is_manager', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(blank=True, null=True, verbose_name='متن پیام')),
                ('file', models.FileField(blank=True, null=True, upload_to='chat_files', verbose_name='فایل')),
                ('create_time', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='زمان ارسال')),
                ('parent', models.ForeignKey(blank=True, help_text='برای چتهایی که پاسخ به چت دیگری هستند', null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat.chat', verbose_name='والد')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to=settings.AUTH_USER_MODEL, verbose_name='فرستنده')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='chat.room', verbose_name='اتاق گفتگو')),
            ],
            options={
                'verbose_name': 'گفتگو',
                'verbose_name_plural': 'گفتگو',
                'ordering': ['-id'],
            },
        ),
    ]
