# Generated by Django 5.0.4 on 2024-11-17 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='عنوان'),
        ),
    ]
