# Generated by Django 5.0.4 on 2024-11-18 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_member_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='is_mute',
            field=models.BooleanField(default=False, verbose_name='یادآور خاموش است'),
        ),
    ]
