# Generated by Django 5.0.4 on 2024-12-31 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_member_is_mute'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['-is_pinned', '-is_owner', '-is_manager', 'id'], 'verbose_name': 'اتاق گفتگو - اعضا', 'verbose_name_plural': 'اتاق گفتگو - اعضا'},
        ),
        migrations.RenameField(
            model_name='member',
            old_name='pin',
            new_name='is_pinned',
        ),
    ]
