# Generated by Django 5.0.4 on 2025-01-12 03:43

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_alter_member_options_rename_pin_member_is_pinned'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='modify_time',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='زمان ویرایش'),
        ),
    ]
