# Generated by Django 5.0.2 on 2024-04-06 04:03

import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_post_can_reserve_food_post_can_reserve_guest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='غذا')),
            ],
            options={
                'verbose_name': 'غذا',
                'verbose_name_plural': 'غذا',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Nutrition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', django_jalali.db.models.jDateField(unique=True, verbose_name='ناریخ')),
                ('food1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='nutrition_set1', to='fd.food', verbose_name='غذای اول')),
                ('food2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='nutrition_set2', to='fd.food', verbose_name='غذای دوم')),
            ],
            options={
                'verbose_name': 'برنامه غذایی',
                'verbose_name_plural': 'برنامه غذایی',
                'ordering': ('date',),
            },
        ),
        migrations.CreateModel(
            name='Reserve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', django_jalali.db.models.jDateField(unique=True, verbose_name='ناریخ')),
                ('guest1', models.PositiveSmallIntegerField(default=0, verbose_name='تعداد میهمان 1')),
                ('guest2', models.PositiveSmallIntegerField(default=0, verbose_name='تعداد میهمان 2')),
                ('food', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fd.food', verbose_name='غذای اول')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.post', verbose_name='پست')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'رزرو غذا',
                'verbose_name_plural': 'رزرو غذا',
                'ordering': ['id'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
