# Generated by Django 5.0.4 on 2024-04-07 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fd', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reserve',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='reserve',
            name='date',
        ),
        migrations.RemoveField(
            model_name='reserve',
            name='food',
        ),
    ]
