# Generated by Django 5.0.4 on 2024-04-07 05:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fd', '0002_alter_reserve_unique_together_remove_reserve_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reserve',
            name='food',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 1), (2, 2)], null=True, verbose_name='نوع غذای رزرو شده'),
        ),
        migrations.AddField(
            model_name='reserve',
            name='nutrition',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fd.nutrition', verbose_name='برنامه غذایی'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='reserve',
            unique_together={('user', 'nutrition')},
        ),
    ]
