# Generated by Django 5.0.4 on 2024-04-14 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fd', '0003_reserve_food_reserve_nutrition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserve',
            name='plus1',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='تعداد شخصی 1'),
        ),
        migrations.AddField(
            model_name='reserve',
            name='plus2',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='تعداد شخصی 2'),
        ),
    ]
