# Generated by Django 5.0.4 on 2024-04-15 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fd', '0004_reserve_plus1_reserve_plus2'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserve',
            name='guest_accept',
            field=models.BooleanField(blank=True, null=True, verbose_name='تأیید رزرو میهمان'),
        ),
        migrations.AddField(
            model_name='reserve',
            name='guest_info',
            field=models.TextField(blank=True, null=True, verbose_name='مضخصات میهمانان (نام و عنوان) و موضوع جلسه'),
        ),
    ]
