# Generated by Django 5.0.4 on 2024-04-24 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fd', '0005_reserve_guest_accept_reserve_guest_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserve',
            name='subsidy',
            field=models.BooleanField(default=True, verbose_name='سوبسید غذا'),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='food',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2)], default=0, verbose_name='نوع غذای رزرو شده'),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='guest_info',
            field=models.TextField(blank=True, null=True, verbose_name='مشخصات میهمانان (نام و عنوان) و موضوع جلسه'),
        ),
    ]
