# Generated by Django 5.0.4 on 2024-04-24 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fd', '0006_reserve_subsidy_alter_reserve_food_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutrition',
            name='price1',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='قیمت غذای 1'),
        ),
        migrations.AddField(
            model_name='nutrition',
            name='price2',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='قیمت غذای 2'),
        ),
    ]
