# Generated by Django 5.0.4 on 2024-04-30 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fd', '0007_nutrition_price1_nutrition_price2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='food',
            field=models.PositiveSmallIntegerField(choices=[(0, 'رزرو نکرده'), (1, 'غذای 1'), (2, 'غذای 2')], default=0, verbose_name='نوع غذای رزرو شده'),
        ),
    ]
