# Generated by Django 5.0.4 on 2024-05-14 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fd', '0008_alter_reserve_food'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserve',
            name='guest_session',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'امکان\u200cسنجی مطالعات و پژوهش\u200cهای مرتبط با فضای مجازی'), (2, 'اقدامات لازم جهت توسعه نظارت بر شبکه ملی اطلاعات'), (3, 'اقدامات لازم جهت توسعه فرآیند رصد کلان فضای مجازی'), (4, 'توسعه مرکز مدیریت و فرماندهی سایبری')], max_length=50, null=True, verbose_name='برنامه کلان'),
        ),
    ]
