# Generated by Django 5.0.4 on 2024-05-18 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fd', '0009_reserve_guest_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='guest_session',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'امکان\u200cسنجی مطالعات و پژوهش\u200cهای مرتبط با فضای مجازی'), (2, 'اقدامات لازم جهت توسعه نظارت بر شبکه ملی اطلاعات'), (3, 'اقدامات لازم جهت توسعه فرآیند رصد کلان فضای مجازی'), (4, 'توسعه مرکز مدیریت و فرماندهی سایبری')], null=True, verbose_name='برنامه کلان'),
        ),
    ]
