# Generated by Django 5.0.4 on 2024-09-24 04:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fd', '0010_alter_reserve_guest_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='NutritionFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveSmallIntegerField(default=0, verbose_name='قیمت')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fd.food', verbose_name='غذا')),
                ('nutrition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fd.nutrition', verbose_name='برنامه غذایی')),
            ],
        ),
        migrations.AddField(
            model_name='nutrition',
            name='foods',
            field=models.ManyToManyField(blank=True, through='fd.NutritionFood', to='fd.food', verbose_name=''),
        ),
    ]
