# Generated by Django 5.0.4 on 2024-09-24 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fd', '0011_nutritionfood_nutrition_foods'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserve',
            name='nf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fd.nutritionfood', verbose_name='غذا'),
        ),
        migrations.CreateModel(
            name='ReservePlus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveSmallIntegerField(default=0, verbose_name='تعداد')),
                ('nf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fd.nutritionfood', verbose_name='غذا')),
            ],
        ),
    ]
