# Generated by Django 5.0.4 on 2024-09-24 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fd', '0012_reserve_nf_reserveplus'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserveplus',
            name='reserve',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fd.reserve', verbose_name='رزرو'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='nutritionfood',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nfs', to='fd.food', verbose_name='غذا'),
        ),
        migrations.AlterField(
            model_name='nutritionfood',
            name='nutrition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nfs', to='fd.nutrition', verbose_name='برنامه غذایی'),
        ),
    ]
