# Generated by Django 5.0.4 on 2024-09-25 04:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fd', '0013_reserveplus_reserve_alter_nutritionfood_food_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nutrition',
            name='food1',
        ),
        migrations.RemoveField(
            model_name='nutrition',
            name='food2',
        ),
        migrations.RemoveField(
            model_name='nutrition',
            name='price1',
        ),
        migrations.RemoveField(
            model_name='nutrition',
            name='price2',
        ),
        migrations.RemoveField(
            model_name='reserve',
            name='food',
        ),
        migrations.RemoveField(
            model_name='reserve',
            name='guest1',
        ),
        migrations.RemoveField(
            model_name='reserve',
            name='guest2',
        ),
        migrations.RemoveField(
            model_name='reserve',
            name='guest_accept',
        ),
        migrations.RemoveField(
            model_name='reserve',
            name='guest_info',
        ),
        migrations.RemoveField(
            model_name='reserve',
            name='guest_session',
        ),
        migrations.RemoveField(
            model_name='reserve',
            name='plus1',
        ),
        migrations.RemoveField(
            model_name='reserve',
            name='plus2',
        ),
        migrations.AlterField(
            model_name='reserveplus',
            name='nf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pluses', to='fd.nutritionfood', verbose_name='غذا'),
        ),
        migrations.AlterField(
            model_name='reserveplus',
            name='reserve',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pluses', to='fd.reserve', verbose_name='رزرو'),
        ),
    ]
