# Generated by Django 5.0.4 on 2024-10-12 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fd', '0014_remove_nutrition_food1_remove_nutrition_food2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='عنوان کالا')),
                ('scale', models.CharField(choices=[('بسته', 'بسته'), ('کارتن', 'کارتن'), ('عدد', 'عدد'), ('دست', 'دست'), ('جفت', 'جفت'), ('کیلو', 'کیلو'), ('متر', 'متر'), ('باکس', 'باکس')], max_length=10, verbose_name='واحد شمارش')),
                ('count', models.IntegerField(default=0, verbose_name='تعداد')),
            ],
            options={
                'verbose_name': 'موجودی انبار',
                'verbose_name_plural': 'موجودی انبار',
                'ordering': ['id'],
            },
        ),
    ]
