# Generated by Django 5.0.4 on 2024-10-16 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fd', '0015_warehouse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='scale',
            field=models.CharField(choices=[('بسته', 'بسته'), ('کارتن', 'کارتن'), ('عدد', 'عدد'), ('دست', 'دست'), ('جفت', 'جفت'), ('کیلو', 'کیلو'), ('متر', 'متر'), ('باکس', 'باکس'), ('رول', 'رول'), ('لیتر', 'لیتر')], max_length=10, verbose_name='واحد شمارش'),
        ),
    ]
