# Generated by Django 5.0.4 on 2024-12-24 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fd', '0016_alter_warehouse_scale'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserve',
            name='note',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='نظرسنجی'),
        ),
        migrations.AddField(
            model_name='reserve',
            name='rate',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='امتیاز'),
        ),
    ]
