# Generated by Django 5.0.4 on 2025-02-04 05:44

import django.db.models.deletion
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fd', '0017_reserve_note_reserve_rate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='warehouse',
            options={'ordering': ['id'], 'verbose_name': 'انبار', 'verbose_name_plural': 'انبار'},
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='count',
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0, verbose_name='تعداد')),
                ('date', django_jalali.db.models.jDateField(auto_now_add=True, verbose_name='تاریخ')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fd.warehouse', verbose_name='کالا')),
            ],
            options={
                'verbose_name': 'موجودی انبار',
                'verbose_name_plural': 'موجودی انبار',
                'ordering': ['id'],
            },
        ),
    ]
