# Generated by Django 5.0.4 on 2025-02-04 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fd', '0018_alter_warehouse_options_remove_warehouse_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='count',
            field=models.IntegerField(default=0, verbose_name='تعداد'),
        ),
    ]
