# Generated by Django 5.0.4 on 2025-02-12 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fd', '0019_warehouse_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='place',
            field=models.CharField(blank=True, choices=[('آفاق', 'آفاق'), ('سعادت\u200cآباد', 'سعادت\u200cآباد')], max_length=10, null=True, verbose_name='مکان'),
        ),
    ]
