# Generated by Django 5.0.4 on 2025-05-27 14:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0073_alter_computer_ram'),
        ('fd', '0020_warehouse_place'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='price',
            field=models.PositiveBigIntegerField(blank=True, help_text='برای حالت افزایش', null=True, verbose_name='قیمت'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='type',
            field=models.CharField(choices=[('افزایش', 'افزایش'), ('کاهش', 'کاهش')], default='افزایش', max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventory',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.unit', verbose_name='برای حالت کاهش'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='برای حالت کاهش'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='place',
            field=models.CharField(blank=True, choices=[('آفاق', 'آفاق'), ('سعادت\u200cآباد', 'سعادت\u200cآباد')], max_length=10, null=True, verbose_name='انبار'),
        ),
        migrations.AlterUniqueTogether(
            name='inventory',
            unique_together={('warehouse', 'date')},
        ),
    ]
