# Generated by Django 5.0.4 on 2025-06-02 10:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0074_alter_post_has_visitant'),
        ('fd', '0021_inventory_price_inventory_type_inventory_unit_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inventory',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='type',
            field=models.CharField(choices=[('افزایش', 'افزایش'), ('کاهش', 'کاهش')], max_length=6, verbose_name='نوع'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='unit',
            field=models.ForeignKey(blank=True, help_text='برای حالت کاهش', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.unit', verbose_name='واحد متقاضی'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='user',
            field=models.ForeignKey(blank=True, help_text='برای حالت کاهش', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='کاربر متقاضی'),
        ),
    ]
