# Generated by Django 5.0.4 on 2025-11-17 09:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fd', '0022_alter_inventory_unique_together_alter_inventory_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='nf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fd.nutritionfood', verbose_name='غذا'),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='nutrition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fd.nutrition', verbose_name='برنامه غذایی'),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
    ]
