# Generated by Django 5.0.4 on 2025-11-29 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fd', '0023_alter_reserve_nf_alter_reserve_nutrition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='order_point',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='حد سفارش'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='type',
            field=models.CharField(blank=True, choices=[('سرمایه\u200cای', 'سرمایه\u200cای'), ('مصرفی خوراکی', 'مصرفی خوراکی'), ('مصرفی غیرخوراکی', 'مصرفی غیرخوراکی')], null=True, verbose_name='نوع'),
        ),
    ]
