# Generated by Django 5.0.2 on 2024-02-22 08:41

import django.db.models.deletion
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_alter_unit_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyUpdateLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='آغاز')),
                ('finish', django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='پایان')),
                ('updated_count', models.PositiveSmallIntegerField(default=0, verbose_name='')),
            ],
            options={
                'ordering': ['-start'],
            },
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
            ],
            options={
                'verbose_name': 'سیاست',
                'verbose_name_plural': 'سیاست\u200cها',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('priority', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3)], default=1, verbose_name='اولویت')),
                ('note', models.TextField(blank=True, null=True, verbose_name='شرح برنامه')),
                ('progress', models.PositiveSmallIntegerField(default=0, verbose_name='پیشرفت')),
                ('expected', models.PositiveSmallIntegerField(default=0, help_text='هر روز آپدیت می\u200cشود', verbose_name='پیشرفت مطلوب')),
                ('accepted', models.BooleanField(blank=True, null=True, verbose_name='تأیید شده')),
                ('accept_date', django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ تأیید')),
                ('accept_note', models.TextField(blank=True, null=True, verbose_name='شرح تأیید')),
                ('approved', models.BooleanField(blank=True, null=True, verbose_name='تصویب شده')),
                ('approve_date', django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ تصویب')),
                ('approve_note', models.TextField(blank=True, null=True, verbose_name='شرح تصویب')),
                ('create_time', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('modify_time', django_jalali.db.models.jDateTimeField(auto_now=True)),
                ('mission', models.ManyToManyField(blank=True, to='prj.mission', verbose_name='سیاست')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='core.unit', verbose_name='واحد')),
            ],
            options={
                'verbose_name': 'برنامه',
                'verbose_name_plural': 'برنامه\u200cها',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='فعالیت')),
                ('step', models.SmallIntegerField(blank=True, null=True, verbose_name='ترتیب اقدام')),
                ('importance', models.SmallIntegerField(default=1, verbose_name='اهمیت')),
                ('cost', models.BigIntegerField(default=0, verbose_name='هزینه')),
                ('start', django_jalali.db.models.jDateField(verbose_name='آغاز')),
                ('finish', django_jalali.db.models.jDateField(verbose_name='پایان')),
                ('goal', models.TextField(verbose_name='هدف کمی')),
                ('progress', models.PositiveSmallIntegerField(default=0, verbose_name='پیشرفت')),
                ('expected', models.PositiveSmallIntegerField(default=0, verbose_name='پیشرفت مطلوب')),
                ('create_time', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('modify_time', django_jalali.db.models.jDateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='prj.project', verbose_name='برنامه')),
            ],
            options={
                'verbose_name': 'اقدام',
                'verbose_name_plural': 'اقدامات',
                'ordering': ['project', 'step'],
            },
        ),
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', django_jalali.db.models.jDateField(verbose_name='تاریخ')),
                ('amount', models.PositiveBigIntegerField(verbose_name='مبلغ')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='prj.project', verbose_name='برنامه')),
            ],
            options={
                'verbose_name': 'تخصیص',
                'verbose_name_plural': 'تخصیص',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_note', models.TextField(verbose_name='شرح گزارش')),
                ('claim_date', django_jalali.db.models.jDateField(auto_now_add=True, verbose_name='تاریخ گزارش')),
                ('progress_claimed', models.PositiveSmallIntegerField(verbose_name='پیشرفت اعلام شده')),
                ('accepted', models.BooleanField(blank=True, null=True, verbose_name='تأیید')),
                ('progress_accepted', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='پیشرفت مورد تأیید')),
                ('accept_date', django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ تأیید')),
                ('accept_note', models.TextField(blank=True, null=True, verbose_name='شرح تأیید')),
                ('approved', models.BooleanField(blank=True, null=True, verbose_name='تصویب')),
                ('progress_approved', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='پیشرفت مصوب')),
                ('approve_date', django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ تصویب')),
                ('approve_note', models.TextField(blank=True, null=True, verbose_name='شرح تصویب')),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='prj.phase', verbose_name='فاز')),
            ],
            options={
                'verbose_name': 'گزارش',
                'verbose_name_plural': 'گزارش پیشرفت',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ReportAppendix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='report_files', verbose_name='فایل')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appendices', to='prj.report', verbose_name='گزارش')),
            ],
            options={
                'verbose_name': 'پیوست گزارش',
                'verbose_name_plural': 'پیوست گزارش',
                'ordering': ['id'],
            },
        ),
    ]
