# Generated by Django 5.0.2 on 2024-02-22 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prj', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phase',
            name='method',
            field=models.CharField(choices=[('برون\u200cسپاری', 'برون\u200cسپاری'), ('درون\u200cسپاری', 'درون\u200cسپاری'), ('ترکیبی', 'ترکیبی')], default='ترکیبی', max_length=10, verbose_name='نحوه اجرا'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='phase',
            name='type',
            field=models.CharField(choices=[('پژوهشی', 'پژوهشی'), ('اجرایی', 'اجرایی')], default='اجرایی', max_length=10, verbose_name='نوع'),
            preserve_default=False,
        ),
    ]
