# Generated by Django 5.0.2 on 2024-02-22 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prj', '0002_phase_method_phase_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyupdatelog',
            options={'ordering': ['-start'], 'verbose_name': 'لاگ', 'verbose_name_plural': 'لاگ به\u200cروزرسانی روزانه'},
        ),
        migrations.AlterField(
            model_name='dailyupdatelog',
            name='updated_count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='تعداد پروژه به\u200cروز شده'),
        ),
    ]
