# Generated by Django 5.0.2 on 2024-02-24 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prj', '0003_alter_dailyupdatelog_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mission',
            options={'ordering': ['id'], 'verbose_name': 'مأموریت', 'verbose_name_plural': 'مأموریت\u200cها'},
        ),
        migrations.AddField(
            model_name='phase',
            name='hr',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='نیروی انسانی مورد نیاز'),
        ),
        migrations.AlterField(
            model_name='project',
            name='mission',
            field=models.ManyToManyField(blank=True, to='prj.mission', verbose_name='مأموریت'),
        ),
    ]
