# Generated by Django 5.0.2 on 2024-02-24 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prj', '0004_alter_mission_options_phase_hr_alter_project_mission'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='mission',
            new_name='missions',
        ),
    ]
