# Generated by Django 5.0.2 on 2024-02-24 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prj', '0005_rename_mission_project_missions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phase',
            name='goal',
            field=models.CharField(max_length=100, verbose_name='هدف کمی'),
        ),
    ]
