# Generated by Django 5.0.4 on 2024-04-09 05:17

import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prj', '0006_alter_phase_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='confirm_date',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ تأیید اولیه'),
        ),
        migrations.AddField(
            model_name='project',
            name='confirmed',
            field=models.BooleanField(default=False, verbose_name='تأیید اولیه'),
        ),
    ]
