# Generated by Django 5.0.4 on 2024-04-13 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prj', '0007_project_confirm_date_project_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phase',
            name='hr',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3, verbose_name='نیروی انسانی مورد نیاز'),
        ),
    ]
