# Generated by Django 5.0.4 on 2024-04-14 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_unit_parent'),
        ('prj', '0008_alter_phase_hr'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='units',
            field=models.ManyToManyField(blank=True, to='core.unit', verbose_name='واحدهای متولی'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='title',
            field=models.CharField(max_length=1000, unique=True, verbose_name='عنوان'),
        ),
    ]
