# Generated by Django 5.0.4 on 2024-04-23 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prj', '0009_mission_units_alter_mission_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phase',
            name='cost',
            field=models.BigIntegerField(default=0, help_text='میلیون تومان', verbose_name='هزینه'),
        ),
        migrations.AlterField(
            model_name='phase',
            name='hr',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='نیروی انسانی مورد نیاز'),
        ),
    ]
