# Generated by Django 5.0.4 on 2024-05-26 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prj', '0010_alter_phase_cost_alter_phase_hr'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='year',
            field=models.PositiveSmallIntegerField(default=1403, verbose_name='سال برنامه\u200cای'),
        ),
    ]
