# Generated by Django 5.0.4 on 2024-07-09 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prj', '0011_project_year'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allocation',
            options={'ordering': ['-id'], 'verbose_name': 'پرداخت', 'verbose_name_plural': 'پرداخت'},
        ),
        migrations.AddField(
            model_name='allocation',
            name='title',
            field=models.CharField(default='1', max_length=200, verbose_name='شرح پرداخت'),
            preserve_default=False,
        ),
    ]
