# Generated by Django 5.0.4 on 2024-08-24 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prj', '0012_alter_allocation_options_allocation_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='body',
            field=models.CharField(default='1', max_length=1000, verbose_name='متن'),
            preserve_default=False,
        ),
    ]
