# Generated by Django 5.0.4 on 2024-08-31 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_post_level'),
        ('prj', '0013_mission_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocation',
            name='unit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='core.unit', verbose_name='واحد'),
            preserve_default=False,
        ),
    ]
