# Generated by Django 5.0.4 on 2024-09-01 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prj', '0014_allocation_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allocation',
            name='unit',
        ),
    ]
