# Generated by Django 5.0.4 on 2024-09-15 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prj', '0015_remove_allocation_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mission',
            name='body',
        ),
        migrations.RemoveField(
            model_name='mission',
            name='units',
        ),
    ]
