# Generated by Django 5.0.4 on 2024-09-17 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prj', '0016_remove_mission_body_remove_mission_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='realization_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='سال تحقق'),
        ),
        migrations.AddField(
            model_name='mission',
            name='type',
            field=models.CharField(blank=True, choices=[('توصیه', 'توصیه'), ('مستمر', 'مستمر'), ('زمانمند', 'زمانمند')], max_length=10, null=True, verbose_name='نوع'),
        ),
    ]
