# Generated by Django 5.0.4 on 2024-10-20 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prj', '0017_mission_realization_year_mission_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=170, verbose_name='عنوان'),
        ),
    ]
