# Generated by Django 5.0.4 on 2024-11-11 03:57

import django.db.models.deletion
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prj', '0018_alter_project_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='اقدام کلان')),
                ('trustee', models.CharField(max_length=200, verbose_name='دستگاه متولی')),
                ('colleague', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None, verbose_name='دستگاه\u200cهای همکار')),
                ('get_draft', models.BooleanField(default=False, verbose_name='دریافت پیش\u200cنویس')),
                ('post_comments', models.BooleanField(default=False, verbose_name='ارسال نظرات به ا عضا')),
                ('post_to_commission', models.BooleanField(default=False, verbose_name='ارسال به کمیسیون')),
                ('post_to_approval_authority', models.BooleanField(default=False, verbose_name='ارسال به مرجع تصویب')),
                ('approve', models.BooleanField(default=False, verbose_name='تصویب در مرجع')),
                ('approval_authority', models.CharField(max_length=100, verbose_name='مرجع تصویب')),
            ],
            options={
                'verbose_name': 'سند راهبردی',
                'verbose_name_plural': 'سند راهبردی',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DocumentColleague',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='دستگاه')),
                ('commented', models.BooleanField(default=False, verbose_name='ارسال نظر')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prj.document', verbose_name='سند راهبردی')),
            ],
            options={
                'verbose_name': 'دستگاه همکار',
                'verbose_name_plural': 'دستگاه همکار',
                'ordering': ['id'],
            },
        ),
    ]
