# Generated by Django 5.0.4 on 2024-11-11 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prj', '0019_document_documentcolleague'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='colleague',
        ),
    ]
