# Generated by Django 5.0.4 on 2024-11-18 10:47

import django.db.models.deletion
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prj', '0020_remove_document_colleague'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='post_comments',
            field=models.BooleanField(default=False, verbose_name='ارسال نظرات به اعضا'),
        ),
        migrations.CreateModel(
            name='DocumentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(choices=[('دریافت پیش\u200cنویس', 'دریافت پیش\u200cنویس'), ('ارسال نظرات به اعضا', 'ارسال نظرات به اعضا'), ('ارسال به کمیسیون', 'ارسال به کمیسیون'), ('ارسال به مرجع تصویب', 'ارسال به مرجع تصویب'), ('تصویب در مرجع', 'تصویب در مرجع')], max_length=20, verbose_name='')),
                ('note', models.TextField(verbose_name='شرح')),
                ('date', django_jalali.db.models.jDateField(auto_now_add=True, verbose_name='تاریخ')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prj.document', verbose_name='سند راهبردی')),
            ],
            options={
                'verbose_name': 'لاگ اقدامات',
                'verbose_name_plural': 'لاگ اقدامات',
                'ordering': ['id'],
            },
        ),
    ]
