# Generated by Django 5.0.4 on 2024-11-18 10:59

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prj', '0021_alter_document_post_comments_documentlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentlog',
            name='date',
            field=django_jalali.db.models.jDateField(verbose_name='تاریخ'),
        ),
    ]
