# Generated by Django 5.0.4 on 2025-01-15 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prj', '0022_alter_documentlog_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='year',
            field=models.PositiveSmallIntegerField(choices=[(1403, 1403), (1404, 1404)], default=1404, verbose_name='سال برنامه\u200cای'),
        ),
    ]
