# Generated by Django 5.0.4 on 2025-01-26 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prj', '0023_alter_project_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='phase',
            name='ph',
            field=models.PositiveIntegerField(default=0, verbose_name='نفر ساعت'),
        ),
    ]
