# Generated by Django 5.0.4 on 2025-01-27 04:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prj', '0024_phase_ph'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='team',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='تیم پروژه'),
        ),
    ]
