# Generated by Django 5.0.4 on 2025-02-18 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prj', '0025_project_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='note1404',
            field=models.TextField(blank=True, null=True, verbose_name='نکات اصلاحی'),
        ),
    ]
