# Generated by Django 5.0.4 on 2025-02-22 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prj', '0026_project_note1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='phase',
            name='priority',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3)], default=1, verbose_name='اولویت'),
        ),
    ]
