# Generated by Django 5.0.4 on 2025-05-13 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prj', '0027_phase_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='commission_approve',
            field=models.BooleanField(default=False, verbose_name='تصویب در کمیسیون'),
        ),
        migrations.AddField(
            model_name='document',
            name='post_to_colleagues',
            field=models.BooleanField(default=False, verbose_name='ارسال به دستگاه\u200cهای همکار'),
        ),
        migrations.AlterField(
            model_name='document',
            name='post_to_approval_authority',
            field=models.BooleanField(default=False, verbose_name='بررسی در مرجع'),
        ),
        migrations.AlterField(
            model_name='document',
            name='post_to_commission',
            field=models.BooleanField(default=False, verbose_name='بررسی در کمیسیون'),
        ),
    ]
