# Generated by Django 5.0.4 on 2025-05-25 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0072_alter_proclamation_type'),
        ('prj', '0028_document_commission_approve_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='unit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.unit', verbose_name='واحد متولی'),
            preserve_default=False,
        ),
    ]
