# Generated by Django 5.0.4 on 2025-08-17 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prj', '0029_document_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='committee_approve',
            field=models.BooleanField(default=False, verbose_name='بررسی در کمیته'),
        ),
        migrations.AddField(
            model_name='document',
            name='status',
            field=models.TextField(blank=True, null=True, verbose_name='آخرین وضعیت'),
        ),
    ]
