# Generated by Django 5.0.4 on 2025-09-21 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prj', '0030_document_committee_approve_document_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['year', 'priority', 'unit', 'id'], 'verbose_name': 'برنامه', 'verbose_name_plural': 'برنامه\u200cها'},
        ),
    ]
