# Generated by Django 5.0.4 on 2026-02-01 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prj', '0032_projectsteam'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='priority_percentage',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='درصد اولویت در واحد'),
        ),
        migrations.AlterField(
            model_name='project',
            name='year',
            field=models.PositiveSmallIntegerField(choices=[(1403, 1403), (1404, 1404), (1405, 1405)], default=1404, verbose_name='سال برنامه\u200cای'),
        ),
    ]
