# Generated by Django 5.0.4 on 2026-02-02 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prj', '0033_project_priority_percentage_alter_project_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان نتیجه')),
                ('value', models.CharField(max_length=64, verbose_name='مقدار')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcomes', to='prj.project', verbose_name='برنامه')),
            ],
            options={
                'verbose_name': 'نتیجه برنامه',
                'verbose_name_plural': 'نتایج برنامه',
            },
        ),
    ]
