# Generated by Django 5.0.4 on 2026-02-02 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prj', '0034_projectoutcome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectoutcome',
            name='value',
            field=models.CharField(max_length=250, verbose_name='مقدار'),
        ),
    ]
