# Generated by Django 5.0.4 on 2026-02-02 11:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prj', '0035_alter_projectoutcome_value'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PhaseTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participation_percentage', models.PositiveSmallIntegerField()),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='prj.phase')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'تیم فاز',
                'verbose_name_plural': 'تیم فاز',
            },
        ),
    ]
