# Generated by Django 5.0.4 on 2026-02-07 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prj', '0036_phaseteam'),
    ]

    operations = [
        migrations.AddField(
            model_name='phase',
            name='goal_value',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='مقدار هدف کمی'),
        ),
    ]
