# Generated by Django 5.0.4 on 2026-02-09 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prj', '0037_phase_goal_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phase',
            name='goal_value',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='مقدار هدف کمی'),
        ),
    ]
