# Generated by Django 5.0.4 on 2026-02-17 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prj', '0038_alter_phase_goal_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phase',
            name='goal',
            field=models.CharField(max_length=200, verbose_name='هدف کمی'),
        ),
    ]
