# Generated by Django 5.0.4 on 2024-06-26 03:46

import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0025_post_has_lunch'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceCategory',
            fields=[
                ('id', models.PositiveBigIntegerField(primary_key=True, serialize=False, verbose_name='کد')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان')),
            ],
            options={
                'verbose_name': 'معین هزینه',
                'verbose_name_plural': 'معین هزینه',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceCover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.PositiveBigIntegerField(blank=True, null=True, unique=True, verbose_name='شماره')),
                ('begin_date', django_jalali.db.models.jDateField(verbose_name='از تاریخ')),
                ('end_date', django_jalali.db.models.jDateField(verbose_name='تا تاریخ')),
                ('locked', models.BooleanField(default=False, verbose_name='قفل شده')),
                ('lock_date', django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ قفل')),
                ('accepted', models.BooleanField(default=False, verbose_name='تأیید شده')),
                ('accept_date', django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ تأیید')),
                ('accept_note', models.TextField(blank=True, null=True, verbose_name='شرح تأیید')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.unit', verbose_name='واحد')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'روکش سند هزینه',
                'verbose_name_plural': 'روکش سند هزینه',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره سند')),
                ('date', django_jalali.db.models.jDateField(verbose_name='تاریخ')),
                ('has_paper', models.BooleanField(default=True, verbose_name='فاکتور فیزیکی دارد')),
                ('value_added', models.BooleanField(default=False, verbose_name='شامل ارزش افزوده')),
                ('issuer', models.CharField(blank=True, max_length=100, null=True, verbose_name='طرف مقابل')),
                ('description', models.TextField(blank=True, null=True, verbose_name='شرح فاکتور')),
                ('price', models.PositiveBigIntegerField(verbose_name='مبلغ')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fn.invoicecategory', verbose_name='کد معین')),
                ('cover', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fn.invoicecover', verbose_name='روکش')),
            ],
            options={
                'verbose_name': 'فاکتور',
                'verbose_name_plural': 'فاکتور',
                'ordering': ['id'],
            },
        ),
    ]
