# Generated by Django 5.0.4 on 2024-06-26 04:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fn', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='fn.invoicecategory', verbose_name='کد معین'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='cover',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='fn.invoicecover', verbose_name='روکش'),
        ),
    ]
