# Generated by Django 5.0.4 on 2024-06-29 03:07

import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fn', '0002_alter_invoice_category_alter_invoice_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicecover',
            name='accepted',
            field=models.BooleanField(blank=True, null=True, verbose_name='تأیید شده'),
        ),
        migrations.AlterField(
            model_name='invoicecover',
            name='begin_date',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='از تاریخ'),
        ),
        migrations.AlterField(
            model_name='invoicecover',
            name='end_date',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تا تاریخ'),
        ),
    ]
