# Generated by Django 5.0.4 on 2024-06-29 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fn', '0003_alter_invoicecover_accepted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoicecover',
            name='begin_date',
        ),
        migrations.RemoveField(
            model_name='invoicecover',
            name='end_date',
        ),
    ]
