# Generated by Django 5.0.4 on 2024-07-24 03:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_post_can_see_invoice'),
        ('fn', '0004_remove_invoicecover_begin_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='unit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.unit', verbose_name='واحد سازمانی'),
            preserve_default=False,
        ),
    ]
