# Generated by Django 5.0.4 on 2024-10-16 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fn', '0005_invoice_unit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoicecover',
            options={'ordering': ['-id'], 'verbose_name': 'روکش سند هزینه', 'verbose_name_plural': 'روکش سند هزینه'},
        ),
    ]
