# Generated by Django 5.0.4 on 2024-10-20 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_rename_interim_user_is_interim_user_is_soldier_and_more'),
        ('fn', '0006_alter_invoicecover_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.unit', verbose_name='واحد سازمانی'),
        ),
    ]
