# Generated by Django 5.0.4 on 2024-11-06 03:18

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fn', '0007_alter_invoice_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoicecover',
            name='accept_date',
        ),
        migrations.RemoveField(
            model_name='invoicecover',
            name='lock_date',
        ),
        migrations.AddField(
            model_name='invoicecover',
            name='accept_time',
            field=django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='تاریخ تأیید'),
        ),
        migrations.AddField(
            model_name='invoicecover',
            name='lock_time',
            field=django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='تاریخ قفل'),
        ),
    ]
