# Generated by Django 5.0.4 on 2025-06-01 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fn', '0008_remove_invoicecover_accept_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicecategory',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='فعال است'),
        ),
    ]
