# Generated by Django 5.0.4 on 2025-06-25 11:57

import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fn', '0009_invoicecategory_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicecover',
            name='business_license',
            field=models.FileField(blank=True, null=True, upload_to='invoice', verbose_name='جواز کسب'),
        ),
        migrations.AddField(
            model_name='invoicecover',
            name='confirm1',
            field=models.BooleanField(blank=True, null=True, verbose_name='تأیید خانم کرامتی'),
        ),
        migrations.AddField(
            model_name='invoicecover',
            name='confirm1_time',
            field=django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='زمان تأیید خانم کرامتی'),
        ),
        migrations.AddField(
            model_name='invoicecover',
            name='confirm2',
            field=models.BooleanField(blank=True, null=True, verbose_name='تأیید آقای حق\u200cبین'),
        ),
        migrations.AddField(
            model_name='invoicecover',
            name='confirm2_time',
            field=django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='زمان تأیید آقای حق\u200cبین'),
        ),
        migrations.AddField(
            model_name='invoicecover',
            name='confirm3',
            field=models.BooleanField(blank=True, null=True, verbose_name='تأیید آقای جاودانی'),
        ),
        migrations.AddField(
            model_name='invoicecover',
            name='confirm3_time',
            field=django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='زمان تأیید آقای جاودانی'),
        ),
        migrations.AddField(
            model_name='invoicecover',
            name='deposit_time',
            field=django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='زمان واریز'),
        ),
        migrations.AddField(
            model_name='invoicecover',
            name='factor',
            field=models.FileField(blank=True, null=True, upload_to='invoice', verbose_name='فاکتور'),
        ),
        migrations.AddField(
            model_name='invoicecover',
            name='id_card',
            field=models.FileField(blank=True, null=True, upload_to='invoice', verbose_name='کارت ملی'),
        ),
        migrations.AddField(
            model_name='invoicecover',
            name='setadiran',
            field=models.BooleanField(default=False, verbose_name='خرید از سامانه ستاد'),
        ),
        migrations.AddField(
            model_name='invoicecover',
            name='sheba',
            field=models.CharField(blank=True, max_length=24, null=True, verbose_name='شبا'),
        ),
        migrations.AddField(
            model_name='invoicecover',
            name='slip',
            field=models.FileField(blank=True, null=True, upload_to='invoice', verbose_name='فیش واریز'),
        ),
        migrations.AddField(
            model_name='invoicecover',
            name='type',
            field=models.CharField(choices=[('عادی', 'عادی'), ('مستقیم', 'مستقیم')], default='عادی', max_length=6, verbose_name='نوع'),
        ),
        migrations.AlterField(
            model_name='invoicecover',
            name='accepted',
            field=models.BooleanField(blank=True, help_text='در تنخواه مستقیم: آخرین تأیید، توسط اداره\u200cکل مالی', null=True, verbose_name='تأیید شده'),
        ),
    ]
