# Generated by Django 5.0.4 on 2025-07-01 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fn', '0010_invoicecover_business_license_invoicecover_confirm1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicecover',
            name='confirm1_note',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات خانم کرامتی'),
        ),
        migrations.AddField(
            model_name='invoicecover',
            name='confirm2_note',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات آقای حق\u200cبین'),
        ),
        migrations.AddField(
            model_name='invoicecover',
            name='confirm3_note',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات آقای جاودانی'),
        ),
    ]
