# Generated by Django 5.0.4 on 2025-09-13 13:00

import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fn', '0011_invoicecover_confirm1_note_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoicecover',
            options={'ordering': ['-lock_time', '-id'], 'verbose_name': 'روکش سند هزینه', 'verbose_name_plural': 'روکش سند هزینه'},
        ),
        migrations.AlterField(
            model_name='invoicecover',
            name='confirm2',
            field=models.BooleanField(blank=True, null=True, verbose_name='تأیید مدیر واحد'),
        ),
        migrations.AlterField(
            model_name='invoicecover',
            name='confirm2_note',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات مدیر واحد'),
        ),
        migrations.CreateModel(
            name='InvoiceCoverTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50, verbose_name='وضعیت')),
                ('accept', models.BooleanField(default=True, verbose_name='تأیید')),
                ('create_time', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('note', models.TextField(blank=True, null=True, verbose_name='پیام')),
                ('cover', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='fn.invoicecover', verbose_name='روکش')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'مراحل پرداخت',
                'verbose_name_plural': 'مراحل پرداخت',
                'ordering': ['id'],
            },
        ),
    ]
