# Generated by Django 5.0.4 on 2026-02-18 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fn', '0012_alter_invoicecover_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicecover',
            name='sheba_owner',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='نام صاحب شبا'),
        ),
    ]
