# Generated by Django 5.0.4 on 2025-10-22 08:59

import django.db.models.deletion
import django.utils.timezone
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام دسته\u200cبندی')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('created_at', django_jalali.db.models.jDateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی ویدیو',
                'verbose_name_plural': 'دسته\u200cبندی\u200cهای ویدیو',
            },
        ),
        migrations.CreateModel(
            name='VideoTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='نام تگ')),
                ('created_at', django_jalali.db.models.jDateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'تگ ویدیو',
                'verbose_name_plural': 'تگ\u200cهای ویدیو',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('poster', models.ImageField(upload_to='video_posters/', verbose_name='پوستر')),
                ('video_file', models.FileField(upload_to='videos/', verbose_name='فایل ویدیو')),
                ('created_at', django_jalali.db.models.jDateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ایجاد')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_published', models.BooleanField(default=True, verbose_name='منتشر شده')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='تعداد بازدید')),
                ('like_count', models.PositiveIntegerField(default=0, verbose_name='تعداد لایک')),
                ('comment_count', models.PositiveIntegerField(default=0, verbose_name='تعداد کامنت')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='آپلود کننده')),
            ],
            options={
                'verbose_name': 'ویدیو',
                'verbose_name_plural': 'ویدیوها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VideoComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='متن کامنت')),
                ('created_at', django_jalali.db.models.jDateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ کامنت')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_approved', models.BooleanField(default=True, verbose_name='تایید شده')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='video.videocomment', verbose_name='پاسخ به')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='video.video', verbose_name='ویدیو')),
            ],
            options={
                'verbose_name': 'کامنت ویدیو',
                'verbose_name_plural': 'کامنت\u200cهای ویدیو',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VideoCategoryRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video.videocategory', verbose_name='دسته\u200cبندی')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video.video', verbose_name='ویدیو')),
            ],
            options={
                'verbose_name': 'رابطه ویدیو و دسته\u200cبندی',
                'verbose_name_plural': 'رابطه\u200cهای ویدیو و دسته\u200cبندی',
                'unique_together': {('video', 'category')},
            },
        ),
        migrations.CreateModel(
            name='VideoLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_jalali.db.models.jDateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ لایک')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='video.video', verbose_name='ویدیو')),
            ],
            options={
                'verbose_name': 'لایک ویدیو',
                'verbose_name_plural': 'لایک\u200cهای ویدیو',
                'unique_together': {('user', 'video')},
            },
        ),
        migrations.CreateModel(
            name='VideoTagRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video.videotag', verbose_name='تگ')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video.video', verbose_name='ویدیو')),
            ],
            options={
                'verbose_name': 'رابطه ویدیو و تگ',
                'verbose_name_plural': 'رابطه\u200cهای ویدیو و تگ',
                'unique_together': {('video', 'tag')},
            },
        ),
    ]
