# Generated by Django 5.0.4 on 2025-10-25 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_alter_video_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='poster',
            field=models.ImageField(max_length=512, upload_to='video_posters/', verbose_name='پوستر'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(max_length=512, upload_to='videos/', verbose_name='فایل ویدیو'),
        ),
    ]
