# Generated by Django 5.0.4 on 2025-10-25 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_alter_video_poster_alter_video_video_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='poster',
            field=models.ImageField(blank=True, max_length=512, null=True, upload_to='video_posters/', verbose_name='پوستر'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(blank=True, max_length=512, null=True, upload_to='videos/', verbose_name='فایل ویدیو'),
        ),
    ]
