# Generated by Django 5.0.4 on 2025-10-25 11:04

import django.db.models.deletion
import django.utils.timezone
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0004_alter_video_poster_alter_video_video_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', django_jalali.db.models.jDateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ بازدید')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='video.video', verbose_name='ویدیو')),
            ],
            options={
                'verbose_name': 'بازدید ویدیو',
                'verbose_name_plural': 'بازدیدهای ویدیو',
                'ordering': ['-viewed_at'],
                'unique_together': {('user', 'video')},
            },
        ),
    ]
