# Generated by Django 5.0.4 on 2025-12-03 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0005_videoview'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='preview_file',
            field=models.FileField(blank=True, max_length=512, null=True, upload_to='videos/previews/', verbose_name='پیش نمایش'),
        ),
        migrations.CreateModel(
            name='VideoFileAppendix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('file', models.FileField(blank=True, max_length=512, null=True, upload_to='videos/appendix/', verbose_name='فایل پیوست')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='video.video', verbose_name='ویدیو')),
            ],
            options={
                'verbose_name': 'فایل پیوست ویدیو',
                'verbose_name_plural': 'فایل پیوست ویدیو',
            },
        ),
    ]
