# Generated by Django 5.0.4 on 2024-05-05 04:43

import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('note', models.TextField(blank=True, null=True, verbose_name='شرح')),
                ('deadline', django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='مهلت')),
                ('status', models.CharField(choices=[('todo', 'درنوبت'), ('doing', 'جاری'), ('done', 'خاتمه')], default='todo', max_length=20, verbose_name='وضعیت')),
                ('suspended', models.BooleanField(default=False, verbose_name='کار منتظر اقدام فرد دیکری است')),
                ('urgency', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3)], default=1, verbose_name='فوریت')),
                ('archive', models.BooleanField(default=False, verbose_name='بایگانی')),
                ('create_time', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
            ],
            options={
                'verbose_name': 'کار',
                'verbose_name_plural': 'کار',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='JobAppendix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان فایل')),
                ('file', models.FileField(upload_to='job_appendix', verbose_name='فایل')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pm.job', verbose_name='کار')),
            ],
            options={
                'verbose_name': 'کار - فایل پیوست',
                'verbose_name_plural': 'کار - فایل پیوست',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='مالک')),
            ],
            options={
                'verbose_name': 'تگ',
                'verbose_name_plural': 'تگ',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_owner', models.BooleanField(default=False, help_text='هر کار فقط یک مالک دارد', verbose_name='این کاربر مالک کار (دستور دهنده) است')),
                ('is_committed', models.BooleanField(default=True, help_text='این فیلد برای وقتی که یک فرد به خودش ارجاع می\u200cدهد پیش\u200cبینی شده', verbose_name='این کاربر مسئول انجام کار است')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب نمایش در تگ')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pm.job', verbose_name='کار')),
                ('tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='pm.tag', verbose_name='تگ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'کار - ارجاع',
                'verbose_name_plural': 'کار - ارجاع',
                'ordering': ('order', 'id'),
                'unique_together': {('job', 'user')},
            },
        ),
    ]
