# Generated by Django 5.0.4 on 2024-05-05 06:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FellowException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fellowed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fellowed', to=settings.AUTH_USER_MODEL, verbose_name='ارجاع گیرنده')),
                ('fellower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fellower', to=settings.AUTH_USER_MODEL, verbose_name='ارجاع دهنده')),
            ],
            options={
                'verbose_name': 'استثناء',
                'verbose_name_plural': 'استثنائات ارجاع',
                'ordering': ['id'],
                'unique_together': {('fellower', 'fellowed')},
            },
        ),
    ]
