# Generated by Django 5.0.4 on 2024-05-05 09:27

import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0002_fellowexception'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('date', django_jalali.db.models.jDateField(verbose_name='تاریخ')),
                ('location', models.CharField(blank=True, max_length=100, null=True, verbose_name='مکان')),
                ('create_time', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('registrar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='دبیر جلسه')),
            ],
            options={
                'verbose_name': 'جلسه',
                'verbose_name_plural': 'جلسات',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('deadline', django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='موعد')),
                ('status', models.CharField(choices=[('جاری', 'جاری'), ('خاتمه', 'خاتمه'), ('لغو', 'لغو')], verbose_name='وضعیت')),
                ('done_date', django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ اقدام')),
                ('members', models.ManyToManyField(related_name='approval_member_list', to=settings.AUTH_USER_MODEL, verbose_name='مسئولان مصوبه')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='pm.session', verbose_name='جلسه')),
            ],
            options={
                'verbose_name': 'مصوبه',
                'verbose_name_plural': 'مصوبات جلسات',
                'ordering': ('id',),
            },
        ),
    ]
