# Generated by Django 5.0.4 on 2024-05-08 03:17

import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0003_session_approval'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='approval',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='approval_member_list', to=settings.AUTH_USER_MODEL, verbose_name='مسئولان مصوبه'),
        ),
        migrations.CreateModel(
            name='JobChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(blank=True, null=True, verbose_name='متن پیام')),
                ('file', models.FileField(blank=True, null=True, upload_to='chat_files', verbose_name='فایل')),
                ('send_time', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='زمان ارسال')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pm.job', verbose_name='کار')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='فرستنده')),
            ],
            options={
                'verbose_name': 'وظیفه - گفتگو',
                'verbose_name_plural': 'وظیفه - گفتگو',
                'ordering': ['-id'],
            },
        ),
    ]
