# Generated by Django 5.0.4 on 2024-05-08 03:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0004_alter_approval_members_jobchat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobchat',
            old_name='sender',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='jobappendix',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appendices', to='pm.job', verbose_name='کار'),
        ),
        migrations.AlterField(
            model_name='jobchat',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='pm.job', verbose_name='کار'),
        ),
    ]
