# Generated by Django 5.0.4 on 2024-05-12 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0006_remove_task_is_committed_remove_task_is_owner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='user',
        ),
        migrations.AddField(
            model_name='task',
            name='is_committed',
            field=models.BooleanField(default=True, help_text='این فیلد برای وقتی که یک فرد به خودش ارجاع می\u200cدهد پیش\u200cبینی شده', verbose_name='این کاربر مسئول انجام کار است'),
        ),
        migrations.AddField(
            model_name='task',
            name='is_owner',
            field=models.BooleanField(default=False, help_text='هر کار فقط یک مالک دارد', verbose_name='این کاربر مالک کار (دستور دهنده) است'),
        ),
    ]
