# Generated by Django 5.0.4 on 2024-05-13 02:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0007_remove_job_user_task_is_committed_task_is_owner'),
        ('prj', '0010_alter_phase_cost_alter_phase_hr'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='complete',
            field=models.BooleanField(default=False, verbose_name='کامل شده'),
        ),
        migrations.AddField(
            model_name='job',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='prj.project', verbose_name='پروژه'),
        ),
    ]
