# Generated by Django 5.0.4 on 2024-05-18 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_post_tell_post_tell_local'),
        ('pm', '0008_job_complete_job_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان')),
                ('posts', models.ManyToManyField(blank=True, to='core.post', verbose_name='اعضا')),
            ],
            options={
                'verbose_name': 'نوع جلسه',
                'verbose_name_plural': 'نوع جلسه',
                'ordering': ['id'],
            },
        ),
    ]
