# Generated by Django 5.0.4 on 2024-05-18 03:13

import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_post_tell_post_tell_local'),
        ('pm', '0009_sessiontype'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['order', 'id'], 'verbose_name': 'کار - ارجاع', 'verbose_name_plural': 'کار - ارجاع'},
        ),
        migrations.RemoveField(
            model_name='session',
            name='registrar',
        ),
        migrations.RemoveField(
            model_name='session',
            name='title',
        ),
        migrations.RemoveField(
            model_name='sessiontype',
            name='posts',
        ),
        migrations.AddField(
            model_name='session',
            name='members',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='حاضران جلسه'),
        ),
        migrations.AddField(
            model_name='session',
            name='type',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='pm.sessiontype', verbose_name='عنوان'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='approval',
            name='deadline',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='مهلت اقدام'),
        ),
        migrations.AlterField(
            model_name='approval',
            name='done_date',
            field=django_jalali.db.models.jDateField(blank=True, help_text='خاتمه و لغو، هردو اقدام محسوب می\u200cشوند', null=True, verbose_name='تاریخ اقدام'),
        ),
        migrations.AlterField(
            model_name='approval',
            name='members',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='مسئولان مصوبه'),
        ),
        migrations.AlterField(
            model_name='approval',
            name='status',
            field=models.CharField(choices=[('جاری', 'جاری'), ('خاتمه', 'خاتمه'), ('لغو', 'لغو')], default='جاری', verbose_name='وضعیت'),
        ),
        migrations.CreateModel(
            name='SessionPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_secretary', models.BooleanField(default=False, help_text='دسترسی ویرایش دارد', verbose_name='دبیر جلسه')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='core.post', verbose_name='پست\u200cها')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pm.sessiontype', verbose_name='عنوان')),
            ],
            options={
                'verbose_name': 'اعضای جلسه',
                'verbose_name_plural': 'اعضای جلسه',
                'ordering': ['type', 'post'],
                'unique_together': {('type', 'post')},
            },
        ),
    ]
