# Generated by Django 5.0.4 on 2024-05-18 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_post_tell_post_tell_local'),
        ('pm', '0010_alter_task_options_remove_session_registrar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='no',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='شماره جلسه'),
        ),
        migrations.AlterField(
            model_name='sessionpost',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.post', verbose_name='پست\u200cها'),
        ),
        migrations.AlterField(
            model_name='sessionpost',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='pm.sessiontype', verbose_name='عنوان'),
        ),
    ]
