# Generated by Django 5.0.4 on 2024-05-21 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_post_tell_post_tell_local'),
        ('pm', '0011_session_no_alter_sessionpost_post_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='approval',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pm.approval', verbose_name='مصوبه'),
        ),
        migrations.AlterField(
            model_name='sessionpost',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.post', verbose_name='پست'),
        ),
        migrations.AlterUniqueTogether(
            name='session',
            unique_together={('type', 'no')},
        ),
    ]
