# Generated by Django 5.0.4 on 2024-05-26 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0012_job_approval_alter_sessionpost_post_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approval',
            name='done_date',
        ),
        migrations.RemoveField(
            model_name='approval',
            name='status',
        ),
        migrations.RemoveField(
            model_name='session',
            name='location',
        ),
        migrations.AddField(
            model_name='approval',
            name='percent',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='درصد انجام'),
        ),
    ]
