# Generated by Django 5.0.4 on 2024-05-28 09:31

import django.contrib.postgres.fields
import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_proclamationappendix_options_and_more'),
        ('pm', '0013_remove_approval_done_date_remove_approval_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, verbose_name='عنوان')),
                ('type', models.CharField(choices=[('text', 'متن'), ('number', 'عدد'), ('radio', 'انتخاب - رادیویی'), ('select', 'انتخاب - کشویی'), ('multi-select', 'چندانتخابی'), ('date', 'تاریخ'), ('datetime', 'زمان'), ('duration', 'مدت زمان'), ('file', 'فایل'), ('rich-text', 'متن چندخطی')], max_length=12, verbose_name='نوع')),
                ('choices', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, help_text='مخصوص نوع «انتخاب»', size=None, verbose_name='انتخاب\u200cها')),
                ('table', models.CharField(blank=True, help_text='مخصوص سرستونهای جدول - می\u200cتواند در یک فرآیند چندین پاسخ داشته باشد', max_length=50, null=True, verbose_name='نام جدول')),
                ('row_min', models.PositiveSmallIntegerField(default=1, help_text='برای نوع «جدول»', verbose_name='تعداد حداقل ردیف')),
                ('row_max', models.PositiveSmallIntegerField(default=10, help_text='برای نوع «جدول»', verbose_name='تعداد حداکثر ردیف')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب نمایش در فرم')),
            ],
            options={
                'verbose_name': 'Field',
                'verbose_name_plural': 'Fields',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AlterField(
            model_name='approval',
            name='title',
            field=models.CharField(max_length=300, verbose_name='عنوان'),
        ),
        migrations.CreateModel(
            name='Dispatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_to_owner', models.BooleanField(default=False, verbose_name='ارسال به کاربر')),
                ('send_to_parent', models.BooleanField(default=False, verbose_name='ارسال به مدیر مستقیم')),
                ('send_to_manager', models.BooleanField(default=False, verbose_name='ارسال به مدیر واحد')),
                ('if_operator', models.CharField(choices=[('and', 'and'), ('or', 'or')], default='and', help_text='برای حالت اتصال مشروط', max_length=3, verbose_name='نوع شرط')),
                ('send_to_posts', models.ManyToManyField(blank=True, to='core.post', verbose_name='پست\u200cهای مقصد')),
            ],
            options={
                'verbose_name': 'Dispatch',
                'verbose_name_plural': 'Dispatch',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DispatchIf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('خالی', 'خالی'), ('دارای مقدار', 'دارای مقدار'), ('مساوی', 'مساوی'), ('نامساوی', 'نامساوی'), ('بزرگتر', 'بزرگتر'), ('بزرگتر یا مساوی', 'بزرگتر یا مساوی'), ('کوچکتر', 'کوچکتر'), ('کوچکتر یا مساوی', 'کوچکتر یا مساوی'), ('موجود در لیست', 'موجود در لیست'), ('ناموجود در لیست', 'ناموجود در لیست')], max_length=20, verbose_name='نوع شرط')),
                ('value', models.CharField(blank=True, max_length=100, null=True, verbose_name='مقدار شرط')),
                ('values', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None, verbose_name='مقادیر شرط')),
                ('dispatch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ifs', to='pm.dispatch', verbose_name='اتصال')),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pm.field', verbose_name='فیلد شرط')),
            ],
            options={
                'verbose_name': 'شرط',
                'verbose_name_plural': 'شرط',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Flow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flows', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'درخواست',
                'verbose_name_plural': 'فرآیند',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(blank=True, null=True, verbose_name='پاسخ')),
                ('file', models.FileField(blank=True, null=True, upload_to='flow_files', verbose_name='')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='شماره ردیف در جدول')),
                ('create_time', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='pm.field', verbose_name='فیلد')),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='pm.flow', verbose_name='درخواست')),
            ],
            options={
                'verbose_name': 'پاسخ',
                'verbose_name_plural': 'فرآیند - پاسخ',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='FlowPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان فرآیند')),
                ('form_width', models.PositiveSmallIntegerField(default=500, verbose_name='پهنای فرم')),
                ('quota_per_user', models.PositiveSmallIntegerField(default=1, verbose_name='تعداد مجاز ثبت فرآیند توسط کاربر')),
                ('active', models.BooleanField(default=False, verbose_name='فرآیند فعال است')),
                ('preamble', models.TextField(default='', verbose_name='مقدمه (توضیحات)')),
                ('posts', models.ManyToManyField(blank=True, to='core.post', verbose_name='پست\u200cهای مجاز شروع فرآیند')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده')),
            ],
            options={
                'verbose_name': 'Flow',
                'verbose_name_plural': 'Flows',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='flow',
            name='flow_pattern',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flows', to='pm.flowpattern', verbose_name='فرآیند'),
        ),
        migrations.AddField(
            model_name='field',
            name='flow_pattern',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='pm.flowpattern', verbose_name='فرآیند'),
        ),
        migrations.CreateModel(
            name='NodePattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان')),
                ('is_first', models.BooleanField(default=False, verbose_name='گره آغاز فرآیند')),
                ('is_last', models.BooleanField(default=False, verbose_name='گره پایان فرآیند')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب نمایش در فرم')),
                ('sms', models.BooleanField(default=False, verbose_name='نیاز به یادآوری پیامکی')),
                ('flow_pattern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='pm.flowpattern', verbose_name='فرآیند')),
                ('next', models.ForeignKey(blank=True, help_text='فقط وقتی که کاربر می\u200cخواهد ارجاع شوندگان را از fellowlist انتخاب کند. ضمناً باید گره بعدی، گره خاتمه باشد و ادامه پیدا نکند', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pm.nodepattern', verbose_name='گره بعدی')),
            ],
            options={
                'verbose_name': 'Node',
                'verbose_name_plural': 'Nodes',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('seen_time', django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='زمان مشاهده توسط کاربر')),
                ('done_time', django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='زمان تأیید توسط کاربر')),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='pm.flow', verbose_name='درخواست')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('node_pattern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='pm.nodepattern', verbose_name='گره')),
            ],
            options={
                'verbose_name': 'فرآیند',
                'verbose_name_plural': 'فرآیند - گره',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='dispatch',
            name='end',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatches_out', to='pm.nodepattern', verbose_name='گره پایان'),
        ),
        migrations.AddField(
            model_name='dispatch',
            name='start',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatches_in', to='pm.nodepattern', verbose_name='گره آغاز'),
        ),
        migrations.CreateModel(
            name='NodeField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('editable', models.BooleanField(default=False, verbose_name='قابل ویرایش')),
                ('required', models.BooleanField(default=False, verbose_name='اجباری')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pm.field', verbose_name='فیلد')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='pm.nodepattern', verbose_name='گره')),
            ],
            options={
                'verbose_name': 'Node Field',
                'verbose_name_plural': 'Node Field',
                'ordering': ['field', 'id'],
                'unique_together': {('node', 'field')},
            },
        ),
    ]
