# Generated by Django 5.0.4 on 2024-05-29 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0014_field_alter_approval_title_dispatch_dispatchif_flow_and_more'),
        ('prj', '0011_project_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='prj.project', verbose_name='پروژه'),
        ),
    ]
