# Generated by Django 5.0.4 on 2024-05-29 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0015_alter_job_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(max_length=300, verbose_name='عنوان'),
        ),
    ]
