# Generated by Django 5.0.4 on 2024-06-01 02:44

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0016_alter_job_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='complete_date',
            field=django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='زمان کامل شدن'),
        ),
    ]
