# Generated by Django 5.0.4 on 2024-06-09 04:37

import django.utils.timezone
import django.contrib.postgres.fields
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0017_job_complete_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='create_time',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dispatchif',
            name='values',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None, verbose_name='مقادیر شرط'),
        ),
        migrations.AlterField(
            model_name='field',
            name='choices',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, help_text='مخصوص نوع «انتخاب»', size=None, verbose_name='انتخاب\u200cها'),
        ),
    ]
