# Generated by Django 5.0.4 on 2024-06-23 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0018_task_create_time_alter_dispatchif_values_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='session',
            options={'ordering': ['-date'], 'verbose_name': 'جلسه', 'verbose_name_plural': 'جلسات'},
        ),
        migrations.RemoveField(
            model_name='flowpattern',
            name='user',
        ),
    ]
