# Generated by Django 5.0.4 on 2024-07-21 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0020_session_title_session_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='session',
            unique_together=set(),
        ),
        migrations.DeleteModel(
            name='SessionPost',
        ),
        migrations.RemoveField(
            model_name='session',
            name='no',
        ),
        migrations.RemoveField(
            model_name='session',
            name='type',
        ),
        migrations.DeleteModel(
            name='SessionType',
        ),
    ]
