# Generated by Django 5.0.4 on 2024-07-21 06:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0021_alter_session_unique_together_delete_sessionpost_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='title',
            field=models.CharField(default='a', max_length=50, verbose_name='عنوان جلسه'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='session',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL, verbose_name='مالک جلسه'),
            preserve_default=False,
        ),
    ]
