# Generated by Django 5.0.4 on 2024-07-21 07:20

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0022_alter_session_title_alter_session_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='guests',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None, verbose_name='میهمانان'),
        ),
    ]
