# Generated by Django 5.0.4 on 2024-07-24 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0023_session_guests'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_seen',
            field=models.BooleanField(default=False, help_text='برای نمایش تعداد تسک جدید کاربر', verbose_name='مشاهده شد'),
        ),
        migrations.AlterField(
            model_name='field',
            name='type',
            field=models.CharField(choices=[('text', 'متن'), ('number', 'عدد'), ('radio', 'انتخاب - رادیویی'), ('select', 'انتخاب - کشویی'), ('toggle', 'انتخاب - دکمه\u200cای'), ('multi-select', 'چندانتخابی'), ('date', 'تاریخ'), ('datetime', 'زمان'), ('duration', 'مدت زمان'), ('file', 'فایل'), ('rich-text', 'متن چندخطی'), ('projects', 'لیست پروژه\u200cها')], max_length=12, verbose_name='نوع'),
        ),
    ]
