# Generated by Django 5.0.4 on 2024-07-27 06:43

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0024_task_is_seen_alter_field_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='guests',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None, verbose_name='میهمانان'),
        ),
    ]
