# Generated by Django 5.0.4 on 2024-07-29 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0025_alter_session_guests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='title',
            field=models.CharField(max_length=100, verbose_name='عنوان جلسه'),
        ),
    ]
