# Generated by Django 5.0.4 on 2024-08-12 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0026_alter_session_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowpattern',
            name='type',
            field=models.CharField(choices=[('درخواست\u200cهای عمومی', 'درخواست\u200cهای عمومی'), ('فرآیندهای مالی', 'فرآیندهای مالی'), ('فرآیندهای منابع انسانی', 'فرآیندهای منابع انسانی'), ('نظرسنجی و ارزیابی', 'نظرسنجی و ارزیابی')], default='درخواست\u200cهای عمومی', max_length=50, verbose_name='نوع'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='approval',
            name='title',
            field=models.TextField(max_length=300, verbose_name='عنوان'),
        ),
    ]
