# Generated by Django 5.0.4 on 2024-08-24 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0027_flowpattern_type_alter_approval_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowpattern',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='تصویر فرآیند'),
        ),
        migrations.AlterField(
            model_name='field',
            name='type',
            field=models.CharField(choices=[('text', 'متن'), ('number', 'عدد'), ('currency', 'مبلغ'), ('radio', 'انتخاب - رادیویی'), ('select', 'انتخاب - کشویی'), ('toggle', 'انتخاب - دکمه\u200cای'), ('multi-select', 'چندانتخابی'), ('date', 'تاریخ'), ('datetime', 'زمان'), ('duration', 'مدت زمان'), ('file', 'فایل'), ('rich-text', 'متن چندخطی'), ('projects', 'لیست پروژه\u200cها'), ('colleagues', 'لیست همکاران')], max_length=12, verbose_name='نوع'),
        ),
    ]
