# Generated by Django 5.0.4 on 2024-08-27 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_post_level'),
        ('pm', '0028_flowpattern_image_alter_field_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowpattern',
            name='type',
            field=models.CharField(choices=[('درخواست\u200cهای عمومی', 'درخواست\u200cهای عمومی'), ('فرآیندهای مالی', 'فرآیندهای مالی'), ('فرآیندهای منابع انسانی', 'فرآیندهای منابع انسانی'), ('نظرسنجی و ارزیابی', 'نظرسنجی و ارزیابی')], default='درخواست\u200cهای عمومی', max_length=50, verbose_name='نوع'),
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان')),
                ('location', models.CharField(max_length=50, verbose_name='مکان')),
                ('capacity', models.PositiveSmallIntegerField(verbose_name='ظرفیت')),
                ('facilities', models.TextField(blank=True, null=True, verbose_name='امکانات')),
                ('units', models.ManyToManyField(blank=True, to='core.unit', verbose_name='واحدهای مجاز')),
            ],
            options={
                'verbose_name': 'اتاق جلسه',
                'verbose_name_plural': 'اتاق جلسه',
                'ordering': ['id'],
            },
        ),
    ]
