# Generated by Django 5.0.4 on 2024-08-27 04:03

import django.db.models.deletion
import django.contrib.postgres.fields
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0029_alter_flowpattern_type_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='agenda',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None, verbose_name='دستور جلسه'),
        ),
        migrations.CreateModel(
            name='Visitant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('lunch', models.PositiveSmallIntegerField(choices=[(0, 'ناهار نمی\u200cماند'), (1, 'ناهار برنجی'), (2, 'ناهار نانی')], default=0, verbose_name='ناهار')),
                ('enter_time', django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='زمان ورود')),
                ('exit_time', django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='زمان خروج')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitants', to='pm.session', verbose_name='جلسه')),
            ],
            options={
                'verbose_name': 'میهمانان جلسه',
                'verbose_name_plural': 'میهمانان جلسه',
                'ordering': ['id'],
            },
        ),
    ]
