# Generated by Django 5.0.4 on 2024-08-27 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0030_session_agenda_visitant'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='color',
            field=models.CharField(default='cyan-lighten-3', max_length=20, verbose_name='color'),
        ),
        migrations.AddField(
            model_name='session',
            name='end',
            field=models.DurationField(blank=True, null=True, verbose_name='پایان'),
        ),
        migrations.AddField(
            model_name='session',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pm.room', verbose_name='اتاق'),
        ),
        migrations.AddField(
            model_name='session',
            name='start',
            field=models.DurationField(blank=True, null=True, verbose_name='آغاز'),
        ),
    ]
