# Generated by Django 5.0.4 on 2024-08-27 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0031_session_color_session_end_session_room_session_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='week',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='شماره هفته'),
        ),
    ]
