# Generated by Django 5.0.4 on 2024-08-28 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0032_session_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitant',
            name='lunch_accept',
            field=models.BooleanField(default=False, verbose_name='تأیید رزرو ناهار'),
        ),
        migrations.AlterField(
            model_name='visitant',
            name='lunch',
            field=models.PositiveSmallIntegerField(choices=[(0, 'ناهار نمی\u200cماند'), (1, 'ناهار برنجی'), (2, 'ناهار نانی')], default=0, verbose_name='رزرو ناهار'),
        ),
    ]
