# Generated by Django 5.0.4 on 2024-08-28 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0033_visitant_lunch_accept_alter_visitant_lunch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='color',
            field=models.CharField(choices=[('teal-lighten-4', 'سبزآبی'), ('blue-lighten-4', 'آبی'), ('cyan-lighten-4', 'فیروزه\u200cای'), ('green-lighten-4', 'سبز'), ('amber-lighten-4', 'نارنجی'), ('pink-lighten-5', 'صورتی'), ('purple-lighten-5', 'بنفش'), ('blue-grey-lighten-4', 'خاکستری')], default='cyan-lighten-4', max_length=20, verbose_name='رنگ'),
        ),
        migrations.AlterField(
            model_name='visitant',
            name='lunch_accept',
            field=models.BooleanField(blank=True, null=True, verbose_name='تأیید رزرو ناهار'),
        ),
    ]
