# Generated by Django 5.0.4 on 2024-09-01 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0034_alter_session_color_alter_visitant_lunch_accept'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='color',
        ),
    ]
