# Generated by Django 5.0.4 on 2024-09-01 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0035_remove_session_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='units',
        ),
        migrations.AddField(
            model_name='room',
            name='public',
            field=models.BooleanField(default=True, verbose_name='اتاق جلسه عمومی است'),
        ),
    ]
