# Generated by Django 5.0.4 on 2024-09-01 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_user_interim'),
        ('pm', '0036_remove_room_units_room_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='posts',
            field=models.ManyToManyField(blank=True, to='core.post', verbose_name='پست\u200cهای مجاز'),
        ),
    ]
