# Generated by Django 5.0.4 on 2024-09-03 04:31

import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0037_room_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='accept_filming',
            field=models.BooleanField(blank=True, null=True, verbose_name='تأیید تصویربرداری'),
        ),
        migrations.AddField(
            model_name='session',
            name='accept_news',
            field=models.BooleanField(blank=True, null=True, verbose_name='تأیید تهیه خبر'),
        ),
        migrations.AddField(
            model_name='session',
            name='accept_photography',
            field=models.BooleanField(blank=True, null=True, verbose_name='تأیید عکسبرداری'),
        ),
        migrations.AddField(
            model_name='session',
            name='accept_recording',
            field=models.BooleanField(blank=True, null=True, verbose_name='تأیید ضبط جلسه'),
        ),
        migrations.AddField(
            model_name='session',
            name='accept_room',
            field=models.BooleanField(blank=True, null=True, verbose_name='تأیید رزرو اتاق'),
        ),
        migrations.AddField(
            model_name='session',
            name='cancel_time',
            field=django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='زمان اعلام لغو جلسه'),
        ),
        migrations.AddField(
            model_name='session',
            name='confirm',
            field=models.BooleanField(default=False, help_text='در صورت عدم قبول، متقاضی می\u200cتواند جلسه را حذف یا ویرایش کند', verbose_name='قبول شرایط'),
        ),
        migrations.AddField(
            model_name='session',
            name='need_filming',
            field=models.BooleanField(default=False, verbose_name='نیاز به تصویربرداری'),
        ),
        migrations.AddField(
            model_name='session',
            name='need_news',
            field=models.BooleanField(default=False, verbose_name='نیاز به تهیه خبر'),
        ),
        migrations.AddField(
            model_name='session',
            name='need_photography',
            field=models.BooleanField(default=False, verbose_name='نیاز به عکسبرداری'),
        ),
        migrations.AddField(
            model_name='session',
            name='need_recording',
            field=models.BooleanField(default=False, verbose_name='نیاز به ضبط جلسه'),
        ),
    ]
