# Generated by Django 5.0.4 on 2024-09-11 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0039_room_color_alter_room_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='accept_presentation',
            field=models.BooleanField(blank=True, null=True, verbose_name='تأیید ارائه'),
        ),
        migrations.AddField(
            model_name='session',
            name='need_presentation',
            field=models.BooleanField(default=False, verbose_name='نیاز به ارائه'),
        ),
    ]
