# Generated by Django 5.0.4 on 2024-09-11 06:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0040_session_accept_presentation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pm.session', verbose_name='جلسه'),
        ),
        migrations.AddField(
            model_name='session',
            name='filming_agents',
            field=models.ManyToManyField(blank=True, related_name='filming_sessions', to=settings.AUTH_USER_MODEL, verbose_name='مسئولان هماهنگی تصویربرداری'),
        ),
        migrations.AddField(
            model_name='session',
            name='news_agents',
            field=models.ManyToManyField(blank=True, related_name='news_sessions', to=settings.AUTH_USER_MODEL, verbose_name='مسئولان هماهنگی خبر'),
        ),
        migrations.AddField(
            model_name='session',
            name='photography_agents',
            field=models.ManyToManyField(blank=True, related_name='photography_sessions', to=settings.AUTH_USER_MODEL, verbose_name='مسئولان هماهنگی عکسبرداری'),
        ),
        migrations.AddField(
            model_name='session',
            name='presentation_agents',
            field=models.ManyToManyField(blank=True, related_name='presentation_sessions', to=settings.AUTH_USER_MODEL, verbose_name='مسئولان هماهنگی ارائه'),
        ),
        migrations.AddField(
            model_name='session',
            name='recording_agents',
            field=models.ManyToManyField(blank=True, related_name='recording_sessions', to=settings.AUTH_USER_MODEL, verbose_name='مسئولان هماهنگی ضبط'),
        ),
    ]
