# Generated by Django 5.0.4 on 2024-09-11 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0041_job_session_session_filming_agents_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='guests',
        ),
    ]
