# Generated by Django 5.0.4 on 2024-09-15 06:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0042_remove_session_guests'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='room_agents',
            field=models.ManyToManyField(blank=True, related_name='room_sessions', to=settings.AUTH_USER_MODEL, verbose_name='مسئولان هماهنگی سالن'),
        ),
    ]
