# Generated by Django 5.0.4 on 2024-09-15 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0043_session_room_agents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowpattern',
            name='title',
            field=models.CharField(max_length=100, verbose_name='عنوان فرآیند'),
        ),
        migrations.AlterField(
            model_name='job',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='pm.session', verbose_name='جلسه'),
        ),
    ]
