# Generated by Django 5.0.4 on 2024-09-16 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0044_alter_flowpattern_title_alter_job_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowpattern',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='پوستر'),
        ),
    ]
