# Generated by Django 5.0.4 on 2024-09-25 04:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fd', '0014_remove_nutrition_food1_remove_nutrition_food2_and_more'),
        ('pm', '0045_flowpattern_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitant',
            name='nf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fd.nutritionfood', verbose_name='رزرو ناهار'),
        ),
        migrations.AddField(
            model_name='visitant',
            name='nf_accept',
            field=models.BooleanField(blank=True, null=True, verbose_name='تأیید رزرو ناهار'),
        ),
        migrations.AlterField(
            model_name='flowpattern',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='flow_pattern', verbose_name='تصویر فرآیند'),
        ),
        migrations.AlterField(
            model_name='flowpattern',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='flow_pattern', verbose_name='پوستر'),
        ),
    ]
