# Generated by Django 5.0.4 on 2024-09-25 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0046_visitant_nf_visitant_nf_accept_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitant',
            name='lunch',
        ),
        migrations.RemoveField(
            model_name='visitant',
            name='lunch_accept',
        ),
    ]
