# Generated by Django 5.0.4 on 2024-10-12 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0047_remove_visitant_lunch_remove_visitant_lunch_accept'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='hint',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='راهنما'),
        ),
        migrations.AlterField(
            model_name='field',
            name='type',
            field=models.CharField(choices=[('text', 'متن'), ('number', 'عدد'), ('currency', 'مبلغ'), ('radio', 'انتخاب - رادیویی'), ('select', 'انتخاب - کشویی'), ('toggle', 'انتخاب - دکمه\u200cای'), ('multi-select', 'چندانتخابی'), ('date', 'تاریخ'), ('datetime', 'زمان'), ('time', 'ساعت'), ('duration', 'مدت زمان'), ('file', 'فایل'), ('rich-text', 'متن چندخطی'), ('projects', 'لیست پروژه\u200cها'), ('colleagues', 'لیست همکاران')], max_length=12, verbose_name='نوع'),
        ),
        migrations.AlterField(
            model_name='flowpattern',
            name='type',
            field=models.CharField(choices=[('درخواست\u200cهای عمومی', 'درخواست\u200cهای عمومی'), ('اداری و مالی', 'اداری و مالی'), ('پشتیبانی و تدارکات', 'پشتیبانی و تدارکات'), ('نظرسنجی و ارزیابی', 'نظرسنجی و ارزیابی')], default='درخواست\u200cهای عمومی', max_length=50, verbose_name='نوع'),
        ),
    ]
