# Generated by Django 5.0.4 on 2024-10-16 03:58

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0048_field_hint_alter_field_type_alter_flowpattern_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowpattern',
            name='preamble',
            field=django_ckeditor_5.fields.CKEditor5Field(default='', verbose_name='مقدمه (توضیحات)'),
        ),
    ]
