# Generated by Django 5.0.4 on 2024-11-17 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0049_alter_flowpattern_preamble'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowpattern',
            name='type',
            field=models.CharField(choices=[('فناوری اطلاعات', 'فناوری اطلاعات'), ('اداری و مالی', 'اداری و مالی'), ('پشتیبانی و تدارکات', 'پشتیبانی و تدارکات'), ('نظرسنجی و ارزیابی', 'نظرسنجی و ارزیابی'), ('روابط عمومی', 'روابط عمومی')], default='فناوری اطلاعات', max_length=50, verbose_name='نوع'),
        ),
    ]
