# Generated by Django 5.0.4 on 2024-11-19 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0050_alter_flowpattern_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='breakfast',
            field=models.CharField(blank=True, choices=[('حلیم', 'حلیم'), ('آش', 'آش'), ('عدسی', 'عدسی'), ('گوجه خیار پنیر گردو', 'گوجه خیار پنیر گردو')], max_length=20, null=True, verbose_name='صبحانه'),
        ),
        migrations.AddField(
            model_name='session',
            name='catering',
            field=models.CharField(blank=True, choices=[('شیرینی', 'شیرینی'), ('آبمیوه', 'آبمیوه'), ('آب هویج بستنی', 'آب هویج بستنی'), ('میوه', 'میوه')], max_length=20, null=True, verbose_name='پذیرایی'),
        ),
    ]
