# Generated by Django 5.0.4 on 2024-12-18 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0051_session_breakfast_session_catering'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flow',
            options={'ordering': ['id'], 'verbose_name': 'فرآیند', 'verbose_name_plural': 'فرآیند'},
        ),
    ]
