# Generated by Django 5.0.4 on 2025-01-15 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0052_alter_flow_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowpattern',
            name='type',
            field=models.CharField(choices=[('فناوری اطلاعات', 'فناوری اطلاعات'), ('مکاتبه با معاونت', 'مکاتبه با معاونت'), ('اداری و مالی', 'اداری و مالی'), ('پشتیبانی و تدارکات', 'پشتیبانی و تدارکات'), ('نظرسنجی و ارزیابی', 'نظرسنجی و ارزیابی'), ('روابط عمومی', 'روابط عمومی'), ('حراست', 'حراست')], default='فناوری اطلاعات', max_length=50, verbose_name='نوع'),
        ),
    ]
