# Generated by Django 5.0.4 on 2025-01-25 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0053_alter_flowpattern_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='approval',
            name='is_done',
            field=models.BooleanField(default=False, help_text='از وظیفه مربوطه آپدیت می\u200cشود', verbose_name='انجام شد'),
        ),
        migrations.AlterField(
            model_name='job',
            name='session',
            field=models.ForeignKey(blank=True, help_text='مربوط به وظایف رزرو سالن', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='pm.session', verbose_name='جلسه'),
        ),
    ]
