# Generated by Django 5.0.4 on 2025-01-27 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0054_approval_is_done_alter_job_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approval',
            name='percent',
        ),
    ]
