# Generated by Django 5.0.4 on 2025-01-27 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0055_remove_approval_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='approval',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pm.approval', verbose_name='مصوبه'),
        ),
    ]
