# Generated by Django 5.0.4 on 2025-02-09 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0056_alter_job_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='sms',
            field=models.BooleanField(default=False, verbose_name='یادآوری پیامکی'),
        ),
    ]
