# Generated by Django 5.0.4 on 2025-02-09 10:23

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0057_session_sms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='breakfast',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, default=list, size=None, verbose_name='صبحانه'),
        ),
        migrations.AlterField(
            model_name='session',
            name='catering',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, default=list, size=None, verbose_name='پذیرایی'),
        ),
    ]
