# Generated by Django 5.0.4 on 2025-02-17 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0058_alter_session_breakfast_alter_session_catering'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='attendee_count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='flowpattern',
            name='type',
            field=models.CharField(choices=[('فناوری اطلاعات', 'فناوری اطلاعات'), ('مکاتبه با معاونت', 'مکاتبه با معاونت'), ('مالی و سرمایه\u200cهای انسانی', 'مالی و سرمایه\u200cهای انسانی'), ('پشتیبانی و تدارکات', 'پشتیبانی و تدارکات'), ('نظرسنجی و ارزیابی', 'نظرسنجی و ارزیابی'), ('روابط عمومی', 'روابط عمومی'), ('حراست', 'حراست')], default='فناوری اطلاعات', max_length=50, verbose_name='نوع'),
        ),
    ]
