# Generated by Django 5.0.4 on 2025-02-18 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0059_session_attendee_count_alter_flowpattern_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='attendee_count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='تعداد پذیرایی'),
        ),
    ]
