# Generated by Django 5.0.4 on 2025-04-08 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0060_alter_session_attendee_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='type',
            field=models.CharField(choices=[('text', 'متن'), ('number', 'عدد'), ('currency', 'مبلغ'), ('radio', 'انتخاب - رادیویی'), ('select', 'انتخاب - کشویی'), ('autocomplete', 'انتخاب - قابل جستجو'), ('toggle', 'انتخاب - دکمه\u200cای'), ('multi-select', 'چندانتخابی'), ('date', 'تاریخ'), ('datetime', 'زمان'), ('time', 'ساعت'), ('duration', 'مدت زمان'), ('file', 'فایل'), ('rich-text', 'متن چندخطی'), ('projects', 'لیست پروژه\u200cها'), ('colleagues', 'لیست همکاران')], max_length=12, verbose_name='نوع'),
        ),
    ]
