# Generated by Django 5.0.4 on 2025-04-14 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0061_alter_field_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nodepattern',
            name='is_last',
        ),
        migrations.AddField(
            model_name='field',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='بایگانی شده'),
        ),
        migrations.AddField(
            model_name='nodepattern',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='بایگانی شده'),
        ),
    ]
