# Generated by Django 5.0.4 on 2025-04-15 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0062_remove_nodepattern_is_last_field_is_archived_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='complete',
        ),
        migrations.RemoveField(
            model_name='job',
            name='complete_date',
        ),
    ]
