# Generated by Django 5.0.4 on 2025-04-16 10:17

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0063_remove_job_complete_remove_job_complete_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='done_time',
            field=django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='زمان انجام'),
        ),
    ]
