# Generated by Django 5.0.4 on 2025-04-20 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0064_job_done_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='confirm',
            field=models.BooleanField(default=False, verbose_name='تأیید انجام توسط مدیر'),
        ),
    ]
