# Generated by Django 5.0.4 on 2025-04-27 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0065_job_confirm'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodepattern',
            name='is_bottleneck',
            field=models.BooleanField(default=False, verbose_name='گلوگاه'),
        ),
    ]
