# Generated by Django 5.0.4 on 2025-05-25 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0066_nodepattern_is_bottleneck'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodepattern',
            name='respite',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='مهلت اقدام'),
        ),
    ]
