# Generated by Django 5.0.4 on 2025-05-28 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0073_alter_computer_ram'),
        ('pm', '0067_nodepattern_respite'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='core.unit', verbose_name='واحد سازمانی'),
        ),
    ]
