# Generated by Django 5.0.4 on 2025-05-28 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0073_alter_computer_ram'),
        ('pm', '0068_session_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='unit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='core.unit', verbose_name='واحد سازمانی'),
            preserve_default=False,
        ),
    ]
