# Generated by Django 5.0.4 on 2025-06-03 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0069_alter_session_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitant',
            name='enter_time',
        ),
        migrations.RemoveField(
            model_name='visitant',
            name='exit_time',
        ),
        migrations.AddField(
            model_name='visitant',
            name='lunch',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='ناهار'),
        ),
    ]
