# Generated by Django 5.0.4 on 2025-06-09 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0070_remove_visitant_enter_time_remove_visitant_exit_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='breakfast',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='صبحانه'),
        ),
    ]
