# Generated by Django 5.0.4 on 2025-08-19 11:17

import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fd', '0022_alter_inventory_unique_together_alter_inventory_type_and_more'),
        ('pm', '0071_alter_session_breakfast'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='breakfast_agents',
            field=models.ManyToManyField(blank=True, related_name='breakfast_sessions', to=settings.AUTH_USER_MODEL, verbose_name='مسئولان صبحانه'),
        ),
        migrations.AddField(
            model_name='session',
            name='catering_agents',
            field=models.ManyToManyField(blank=True, related_name='catering_sessions', to=settings.AUTH_USER_MODEL, verbose_name='مسئولان پذیرایی'),
        ),
        migrations.AddField(
            model_name='session',
            name='lunch_agents',
            field=models.ManyToManyField(blank=True, related_name='lunch_sessions', to=settings.AUTH_USER_MODEL, verbose_name='مسئولان ناهار'),
        ),
        migrations.AddField(
            model_name='session',
            name='need_breakfast',
            field=models.BooleanField(default=False, verbose_name='درخواست صبحانه'),
        ),
        migrations.AddField(
            model_name='session',
            name='need_catering',
            field=models.BooleanField(default=False, verbose_name='درخواست پذیرایی'),
        ),
        migrations.AddField(
            model_name='session',
            name='need_lunch',
            field=models.BooleanField(default=False, verbose_name='درخواست ناهار'),
        ),
        migrations.AddField(
            model_name='session',
            name='nf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fd.nutritionfood', verbose_name='ناهار'),
        ),
        migrations.AddField(
            model_name='session',
            name='order_time',
            field=django_jalali.db.models.jDateTimeField(blank=True, help_text='خالی یعنی هنوز بررسی نشده', null=True, verbose_name='زمان بررسی'),
        ),
        migrations.AddField(
            model_name='session',
            name='type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'جلسه با مدیران ارشد'), (2, 'جلسه با مدیران میانی'), (3, 'جلسه کارشناسی')], null=True, verbose_name='نوع جلسه'),
        ),
    ]
