# Generated by Django 5.0.4 on 2025-08-19 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0081_alter_theme_bg_alter_theme_main_alter_theme_tint1_and_more'),
        ('pm', '0072_session_breakfast_agents_session_catering_agents_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='post',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.post', verbose_name='پست'),
        ),
    ]
