# Generated by Django 5.0.4 on 2025-08-20 07:44

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0074_alter_node_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='guests',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None, verbose_name='میهمانان'),
        ),
    ]
