# Generated by Django 5.0.4 on 2025-08-25 12:58

import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0075_session_guests'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='request_time',
            field=django_jalali.db.models.jDateTimeField(blank=True, help_text='با هربار ویرایش ریست میشود', null=True, verbose_name='زمان درخواست پذیرایی'),
        ),
        migrations.AlterField(
            model_name='session',
            name='type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'مهمانان ویژه'), (2, 'جلسه مدیریتی'), (3, 'جلسه کارشناسی')], null=True, verbose_name='نوع جلسه'),
        ),
    ]
