# Generated by Django 5.0.4 on 2025-08-31 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0076_session_request_time_alter_session_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='lunch',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='ناهار'),
        ),
    ]
