# Generated by Django 5.0.4 on 2025-08-31 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0077_session_lunch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='nf',
        ),
    ]
