# Generated by Django 5.0.4 on 2025-09-21 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0078_remove_session_nf'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='last_seen_chat_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pm.jobchat', verbose_name='آخرین گفتگوی مشاهده شده'),
        ),
    ]
