# Generated by Django 5.0.4 on 2025-09-21 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0079_task_last_seen_chat_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='last_seen_chat_id',
            new_name='last_seen_chat',
        ),
    ]
