# Generated by Django 5.0.4 on 2025-10-14 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0080_rename_last_seen_chat_id_task_last_seen_chat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowpattern',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='flow_pattern', verbose_name='شمای کلی فرآیند'),
        ),
    ]
