# Generated by Django 5.0.4 on 2025-11-02 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0081_alter_flowpattern_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approval',
            name='title',
            field=models.TextField(verbose_name='عنوان'),
        ),
    ]
