# Generated by Django 5.0.4 on 2025-11-02 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0082_alter_approval_title'),
        ('prj', '0031_alter_project_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='project',
            field=models.ManyToManyField(blank=True, to='prj.project', verbose_name='پروژه'),
        ),
    ]
