# Generated by Django 5.0.4 on 2025-11-02 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0083_session_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='project',
            new_name='projects',
        ),
    ]
