# Generated by Django 5.0.4 on 2025-11-05 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0084_rename_project_session_projects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(max_length=400, verbose_name='عنوان'),
        ),
    ]
