# Generated by Django 5.0.4 on 2025-11-12 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0085_alter_job_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='guest_count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='تعداد میهمان'),
        ),
    ]
