# Generated by Django 5.0.4 on 2025-11-17 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0086_session_guest_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='deputy_accept',
            field=models.BooleanField(blank=True, null=True, verbose_name='نظر معاون توسعه درمورد پذیرایی'),
        ),
        migrations.AddField(
            model_name='session',
            name='manager_accept',
            field=models.BooleanField(blank=True, null=True, verbose_name='نظر مدیر واحد درمورد پذیرایی'),
        ),
        migrations.AddField(
            model_name='session',
            name='need_deputy',
            field=models.BooleanField(default=False, verbose_name='پذیرایی نیاز به تأیید معاونت دارد'),
        ),
        migrations.AddField(
            model_name='session',
            name='need_manager',
            field=models.BooleanField(default=False, verbose_name='درخواست پذیرایی نیاز به تأیید مدیر واحد دارد'),
        ),
        migrations.AddField(
            model_name='session',
            name='need_room',
            field=models.BooleanField(default=False, verbose_name='درخواست رزرو سالن'),
        ),
        migrations.AddField(
            model_name='session',
            name='place',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='مکان برگزاری جلسه'),
        ),
    ]
