# Generated by Django 5.0.4 on 2025-11-17 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0087_session_deputy_accept_session_manager_accept_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='confirm',
        ),
        migrations.RemoveField(
            model_name='session',
            name='need_room',
        ),
    ]
