# Generated by Django 5.0.4 on 2025-11-18 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0088_remove_session_confirm_remove_session_need_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='manager_accept',
            field=models.CharField(choices=[('نامشخص', 'نامشخص'), ('تأیید', 'تأیید'), ('عدم تأیید', 'عدم تأیید'), ('عودت جهت اصلاح', 'عودت جهت اصلاح')], default='نامشخص', max_length=14, verbose_name='نظر مدیر واحد درمورد پذیرایی'),
        ),
        migrations.AlterField(
            model_name='session',
            name='need_deputy',
            field=models.CharField(choices=[('نامشخص', 'نامشخص'), ('تأیید', 'تأیید'), ('عدم تأیید', 'عدم تأیید'), ('عودت جهت اصلاح', 'عودت جهت اصلاح')], default='نامشخص', max_length=14, verbose_name='پذیرایی نیاز به تأیید معاونت دارد'),
        ),
    ]
