# Generated by Django 5.0.4 on 2025-11-18 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0089_alter_session_manager_accept_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='deputy_accept',
            field=models.CharField(choices=[('نامشخص', 'نامشخص'), ('تأیید', 'تأیید'), ('عدم تأیید', 'عدم تأیید'), ('عودت جهت اصلاح', 'عودت جهت اصلاح')], default='نامشخص', max_length=14, verbose_name='نظر معاون توسعه درمورد پذیرایی'),
        ),
        migrations.AlterField(
            model_name='session',
            name='need_deputy',
            field=models.BooleanField(default=False, verbose_name='پذیرایی نیاز به تأیید معاونت دارد'),
        ),
    ]
