# Generated by Django 5.0.4 on 2025-11-18 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0090_alter_session_deputy_accept_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='deputy_note',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='توضیحات معاون توسعه'),
        ),
        migrations.AddField(
            model_name='session',
            name='manager_note',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='توضیحات مدیر واحد'),
        ),
    ]
