# Generated by Django 5.0.4 on 2025-12-03 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0091_session_deputy_note_session_manager_note'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['order', 'id'], 'verbose_name': 'تگ', 'verbose_name_plural': 'تگ'},
        ),
        migrations.AddField(
            model_name='tag',
            name='order',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
