# Generated by Django 5.0.4 on 2025-12-23 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0092_alter_tag_options_tag_order'),
        ('prj', '0031_alter_project_options'),
    ]

    operations = [

    ]
