# Generated by Django 5.0.4 on 2025-12-23 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0093_remove_session_projects_session_projects'),
        ('prj', '0031_alter_project_options'),
    ]

    operations = [

    ]
