# Generated by Django 5.0.4 on 2025-12-27 10:31

import django.db.models.deletion
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0095_remove_session_projects_session_projects'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlowPatternType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('update_time', django_jalali.db.models.jDateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100, verbose_name='عنوان فرآیند')),
                ('active', models.BooleanField(default=False, verbose_name='فرآیند فعال است')),
            ],
            options={
                'verbose_name': 'Flow Type',
                'verbose_name_plural': 'Flow Types',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='flowpattern',
            name='flow_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pm.flowpatterntype'),
        ),
    ]
