# Generated by Django 5.0.4 on 2026-01-11 08:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0096_flowpatterntype_flowpattern_flow_type'),
        ('prj', '0031_alter_project_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [

        migrations.AddField(
            model_name='job',
            name='informees',
            field=models.ManyToManyField(blank=True, null=True, related_name='informees_job', to=settings.AUTH_USER_MODEL, verbose_name='مطلعین کار'),
        ),

    ]
