# Generated by Django 5.0.4 on 2026-01-11 11:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0097_remove_session_projects_job_informees_and_more'),
        ('prj', '0031_alter_project_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [

        migrations.AddField(
            model_name='session',
            name='secretaries',
            field=models.ManyToManyField(blank=True, related_name='secretaries_sessions', to=settings.AUTH_USER_MODEL, verbose_name='دبیران جلسه'),
        ),
    ]
