# Generated by Django 5.0.4 on 2026-01-11 12:25

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0098_remove_session_projects_session_project_and_more'),
        ('prj', '0031_alter_project_options'),
    ]

    operations = [

    ]
