# Generated by Django 5.0.4 on 2026-01-12 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0099_remove_session_projects_session_project_session_rate_and_more'),
        ('prj', '0031_alter_project_options'),
    ]

    operations = [



    ]
