# Generated by Django 5.0.4 on 2026-01-12 12:49

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0100_remove_session_projects_remove_session_rate_members_and_more'),
    ]

    operations = [

    ]
