# Generated by Django 5.0.4 on 2026-01-13 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0101_session_rate_members'),
        ('prj', '0031_alter_project_options'),
    ]

    operations = [

    ]
