# Generated by Django 5.0.4 on 2026-01-18 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0103_session_secretaries'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='حذف شده'),
        ),
    ]
